"""
CP4 Appender for PAPER_708 -- PillarsOfCreationM16UQFF (CP4 #292)
Auto-generated by _gen_cp4_appenders_702_715.py
"""
import os

CP4 = r"C:\Users\tmsjd\source\repos\Daniel8Murphy0007\Star-Magic\CondensedPhysics4.py"

ENTRY = """

class PillarsOfCreationM16UQFF(object):
    # PAPER_708: Pillars of Creation Eagle Nebula M16 photoevaporation Ug1 Ug4 Lambda UQFF MUGE

    # UQFF universal constants
    G       = 6.6743e-11
    c       = 3.0e8
    hbar    = 1.0546e-34
    mu_0    = 1.2566e-6
    k_B     = 1.3806e-23
    M_sun   = 1.989e30
    kpc     = 3.086e19
    Mpc     = 3.086e22
    rho_UA  = 7.09e-36
    rho_SCm = 7.09e-37
    f_TRZ   = 0.1
    kappa   = 5.0e-4
    SSq     = 0.57
    mu_J    = 3.38e23
    Lambda  = 1.1e-52
    H_0     = 2.269e-18
    t_H     = 4.35e17

    def __init__(self, dataset=None):
        self.dataset = dataset or {}
        self.version = "Session175"

    def compute(self, dataset=None):
        d = dataset or self.dataset
        return {
            "paper":     "PAPER_708",
            "cp4_entry": 292,
            "class":     "PillarsOfCreationM16UQFF",
            "domain":    "Pillars of Creation Eagle Nebula M16 photoevaporation Ug1 Ug4 Lambda UQFF MUGE",
            "equations": self._primary_equations(d),
        }

    def _primary_equations(self, d):
        return {
            "G":           self.G,
            "rho_UA":      self.rho_UA,
            "rho_SCm":     self.rho_SCm,
            "f_TRZ":       self.f_TRZ,
            "UQFF_factor": 1.0 + self.rho_SCm / self.rho_UA,
        }

    def self_update(self): pass
    def self_expand(self): pass

"""


def _append():
    if not os.path.exists(CP4):
        print(f"ERROR: CondensedPhysics4.py not found at {CP4}")
        return
    with open(CP4, "r", encoding="latin-1") as f:
        content = f.read()
    marker = "class PillarsOfCreationM16UQFF"
    if marker in content:
        print(f"SKIP: PillarsOfCreationM16UQFF already present in CondensedPhysics4.py")
        return
    with open(CP4, "a", encoding="utf-8") as f:
        f.write(ENTRY)
    print(f"OK: Appended PillarsOfCreationM16UQFF (PAPER_708, CP4 #292)")


if __name__ == "__main__":
    _append()
