"""Generate arXiv bundle metadata: 00README.txt, abstracts/, bundle_index.csv.

Reads frontmatter + body from each whitepaper .md, extracts the title, abstract,
session, status, cvw fields, and writes the three metadata artifacts.

Idempotent: re-run any time the bundle contents change.
"""
from __future__ import annotations
import csv
import re
from pathlib import Path

BUNDLE = Path(__file__).resolve().parent / "arxiv_submission_1159_1170"
MD_DIR = BUNDLE / "md"
ABS_DIR = BUNDLE / "abstracts"
ABS_DIR.mkdir(exist_ok=True)


def parse_md(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="ignore")
    fm = {}
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end > 0:
            for line in text[3:end].splitlines():
                if ":" in line:
                    k, _, v = line.partition(":")
                    fm[k.strip()] = v.strip().strip('"').strip("'")
            text = text[end + 4:]
    # Find Abstract section
    m = re.search(r"^##\s+Abstract\s*\n(.+?)(?=^##\s+|\Z)", text, re.M | re.S)
    abstract = m.group(1).strip() if m else "(no abstract section found)"
    abstract = re.sub(r"\s+", " ", abstract).strip()
    return {
        "paper_id":  fm.get("paper_id",  path.stem.split("_")[0] + "_" + path.stem.split("_")[1]),
        "title":     fm.get("title",     path.stem),
        "session":   fm.get("session",   ""),
        "status":    fm.get("status",    ""),
        "cvw":       fm.get("cvw",       ""),
        "sm_anchor": fm.get("sm_anchor", ""),
        "date":      fm.get("date",      ""),
        "abstract":  abstract,
        "filename":  path.name,
    }


def main() -> None:
    rows = []
    for md in sorted(MD_DIR.glob("PAPER_*.md")):
        meta = parse_md(md)
        rows.append(meta)
        # Per-paper abstract.txt
        abs_file = ABS_DIR / (md.stem + "_abstract.txt")
        abs_file.write_text(
            f"{meta['paper_id']}: {meta['title']}\n\n{meta['abstract']}\n",
            encoding="utf-8",
        )

    # bundle_index.csv
    idx = BUNDLE / "bundle_index.csv"
    with idx.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["paper_id", "title", "session", "date",
                    "status", "cvw", "sm_anchor", "filename"])
        for r in rows:
            w.writerow([r["paper_id"], r["title"], r["session"], r["date"],
                        r["status"], r["cvw"], r["sm_anchor"], r["filename"]])

    # 00README.txt
    paper_lines = "\n".join(
        f"  {r['paper_id']:10s}  {r['title']}" for r in rows
    )
    readme = BUNDLE / "00README.txt"
    readme.write_text(f"""arXiv submission bundle: PAPER_1159 - PAPER_1170 (Sessions 246-255)
================================================================================

Contents
--------
  md/         {len(rows)} markdown source files (canonical)
  pdf/        {len(rows)} PDFs rendered with pandoc + pdflatex
  tex/        {len(rows)} standalone LaTeX files (pandoc -s output)
  abstracts/  {len(rows)} per-paper abstract.txt extracts
  bundle_index.csv   tabular index of all papers in this bundle
  manifest.json      JSON manifest mapping paper_id -> {{md, pdf, tex}}

Papers
------
{paper_lines}

Compile recipe
--------------
PDF generation uses pandoc + pdflatex ONLY (xelatex is NOT supported):

  pandoc whitepapers/PAPER_XXXX_*.md \\
         -o pdf/PAPER_XXXX_*.pdf \\
         --pdf-engine=pdflatex \\
         -V geometry:margin=1in \\
         -V fontsize=11pt \\
         -V colorlinks=true

For arXiv submission, upload the .tex + .pdf pairs from tex/ and pdf/.
The manifest.json file lists the canonical association.

Dependencies
------------
- pandoc (any recent version; tested with 3.x)
- pdflatex (MiKTeX or TeX Live; tested with MiKTeX 24.x)
- bibtex (for arXiv four-pass workflow when references are added)

CVW gate compliance
-------------------
All papers in this bundle carry frontmatter
  cvw: v2.0.0
  sm_anchor: G6_SM_Anchor_Gate (or equivalent gate-specific anchor)

Closed Lagrangian status (PAPER_1167 master synthesis)
------------------------------------------------------
All eight UQFF Lagrangian gaps are closed using only integer-rational constants
sourced from uqff_closed_constants.py. The 27-decade vacuum-energy ledger is
saturated to <0.5% by R_26 + KK tower + BSFG back-reaction (PAPER_1170).
Five no-free-parameter falsifiable predictions (PAPER_1168) were
numerically confronted against archival data (PAPER_1169): 0/5 falsifications.

Generated by _arxiv_bundle_metadata.py.
""", encoding="utf-8")
    print(f"[OK] wrote {idx.relative_to(BUNDLE.parent)}")
    print(f"[OK] wrote {readme.relative_to(BUNDLE.parent)}")
    print(f"[OK] wrote {len(rows)} per-paper abstracts in abstracts/")


if __name__ == "__main__":
    main()
