#include <cstdio>
#include <cmath>
#include "uqff_exact_closures.cpp"

int main() {
    { double v = static_cast<double>(uqff::F_TRZ_identity()); std::printf("F_TRZ_identity=%.17g\n", v); }
    { double v = static_cast<double>(uqff::solar_nu_e_fraction()); std::printf("solar_nu_e_fraction=%.17g\n", v); }
    { double v = static_cast<double>(uqff::monty_hall_switch_p()); std::printf("monty_hall_switch_p=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sleeping_beauty_p()); std::printf("sleeping_beauty_p=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bertrand_uniform_p()); std::printf("bertrand_uniform_p=%.17g\n", v); }
    { double v = static_cast<double>(uqff::szilard_W_over_kT()); std::printf("szilard_W_over_kT=%.17g\n", v); }
    { double v = static_cast<double>(uqff::glass_T_g_over_T_m()); std::printf("glass_T_g_over_T_m=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_pasta_ratio()); std::printf("nuclear_pasta_ratio=%.17g\n", v); }
    { double v = static_cast<double>(uqff::faber_jackson_exp()); std::printf("faber_jackson_exp=%.17g\n", v); }
    { double v = static_cast<double>(uqff::su3_color_N()); std::printf("su3_color_N=%.17g\n", v); }
    { double v = static_cast<double>(uqff::n_fermion_generations()); std::printf("n_fermion_generations=%.17g\n", v); }
    { double v = static_cast<double>(uqff::delta_CP_lepton()); std::printf("delta_CP_lepton=%.17g\n", v); }
    { double v = static_cast<double>(uqff::solar_dynamo_T_yr()); std::printf("solar_dynamo_T_yr=%.17g\n", v); }
    { double v = static_cast<double>(uqff::z_reion()); std::printf("z_reion=%.17g\n", v); }
    { double v = static_cast<double>(uqff::pop3_IMF_M_sun()); std::printf("pop3_IMF_M_sun=%.17g\n", v); }
    { double v = static_cast<double>(uqff::tsirelson_bound()); std::printf("tsirelson_bound=%.17g\n", v); }
    { double v = static_cast<double>(uqff::proto_iron_Z()); std::printf("proto_iron_Z=%.17g\n", v); }
    { double v = static_cast<double>(uqff::proto_silicon_Z()); std::printf("proto_silicon_Z=%.17g\n", v); }
    { double v = static_cast<double>(uqff::multimessenger_dt_s()); std::printf("multimessenger_dt_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::aharonov_bohm_phase()); std::printf("aharonov_bohm_phase=%.17g\n", v); }
    { double v = static_cast<double>(uqff::aharonov_casher_phase()); std::printf("aharonov_casher_phase=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hayflick_limit()); std::printf("hayflick_limit=%.17g\n", v); }
    { double v = static_cast<double>(uqff::genetic_code_n_codons()); std::printf("genetic_code_n_codons=%.17g\n", v); }
    { double v = static_cast<double>(uqff::genetic_code_n_aa()); std::printf("genetic_code_n_aa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::cosmological_constant()); std::printf("cosmological_constant=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dpm_resonance_Hz()); std::printf("dpm_resonance_Hz=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dT_pulse_ms()); std::printf("dT_pulse_ms=%.17g\n", v); }
    { double v = static_cast<double>(uqff::heaviside_R_t_ohms()); std::printf("heaviside_R_t_ohms=%.17g\n", v); }
    { double v = static_cast<double>(uqff::island_of_stability_Z()); std::printf("island_of_stability_Z=%.17g\n", v); }
    { double v = static_cast<double>(uqff::proton_orbital_Hz()); std::printf("proton_orbital_Hz=%.17g\n", v); }
    { double v = static_cast<double>(uqff::level_13_BH_r_m()); std::printf("level_13_BH_r_m=%.17g\n", v); }
    { double v = static_cast<double>(uqff::f_UMR_Hz()); std::printf("f_UMR_Hz=%.17g\n", v); }
    { double v = static_cast<double>(uqff::V_little_V_big_ratio()); std::printf("V_little_V_big_ratio=%.17g\n", v); }
    { double v = static_cast<double>(uqff::f_Ub_buoyancy_Hz()); std::printf("f_Ub_buoyancy_Hz=%.17g\n", v); }
    { double v = static_cast<double>(uqff::cross_section_A2()); std::printf("cross_section_A2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::heaviside_amp_factor()); std::printf("heaviside_amp_factor=%.17g\n", v); }
    { double v = static_cast<double>(uqff::f_fluid_Hz()); std::printf("f_fluid_Hz=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sun_quiet_B_T()); std::printf("sun_quiet_B_T=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sun_peak_modulation_T()); std::printf("sun_peak_modulation_T=%.17g\n", v); }
    { double v = static_cast<double>(uqff::distance_spooky_m()); std::printf("distance_spooky_m=%.17g\n", v); }
    { double v = static_cast<double>(uqff::spin_precession_30_deg()); std::printf("spin_precession_30_deg=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sin_spin_precession()); std::printf("sin_spin_precession=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubble_omega_per_Gyr()); std::printf("hubble_omega_per_Gyr=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ni62_Z()); std::printf("ni62_Z=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ni62_N()); std::printf("ni62_N=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ni62_A()); std::printf("ni62_A=%.17g\n", v); }
    { double v = static_cast<double>(uqff::proton_core_density()); std::printf("proton_core_density=%.17g\n", v); }
    { double v = static_cast<double>(uqff::rho_vac_total_877_J_m3()); std::printf("rho_vac_total_877_J_m3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dpm_completeness_axiom()); std::printf("dpm_completeness_axiom=%.17g\n", v); }
    { double v = static_cast<double>(uqff::twenty_six_pre_mass_states()); std::printf("twenty_six_pre_mass_states=%.17g\n", v); }
    { double v = static_cast<double>(uqff::cdf_w_mass_shift_MeV()); std::printf("cdf_w_mass_shift_MeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::r_k_lepton_uni()); std::printf("r_k_lepton_uni=%.17g\n", v); }
    { double v = static_cast<double>(uqff::r_d_lepton_uni()); std::printf("r_d_lepton_uni=%.17g\n", v); }
    { double v = static_cast<double>(uqff::koto_BR()); std::printf("koto_BR=%.17g\n", v); }
    { double v = static_cast<double>(uqff::t_violation_meson()); std::printf("t_violation_meson=%.17g\n", v); }
    { double v = static_cast<double>(uqff::higgs_invisible_BR()); std::printf("higgs_invisible_BR=%.17g\n", v); }
    { double v = static_cast<double>(uqff::fcnc_b_s_mumu_BR()); std::printf("fcnc_b_s_mumu_BR=%.17g\n", v); }
    { double v = static_cast<double>(uqff::proton_PRad_radius_fm()); std::printf("proton_PRad_radius_fm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::gw_memory_fraction()); std::printf("gw_memory_fraction=%.17g\n", v); }
    { double v = static_cast<double>(uqff::schwinger_limit_Vm()); std::printf("schwinger_limit_Vm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::qgp_R_AA()); std::printf("qgp_R_AA=%.17g\n", v); }
    { double v = static_cast<double>(uqff::pulsar_glitch()); std::printf("pulsar_glitch=%.17g\n", v); }
    { double v = static_cast<double>(uqff::crab_TeV_cutoff()); std::printf("crab_TeV_cutoff=%.17g\n", v); }
    { double v = static_cast<double>(uqff::cr_ankle_eV()); std::printf("cr_ankle_eV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::cfl_gap_MeV()); std::printf("cfl_gap_MeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::cnub_temp_K()); std::printf("cnub_temp_K=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dark_flow_v_kms()); std::printf("dark_flow_v_kms=%.17g\n", v); }
    { double v = static_cast<double>(uqff::missing_satellites_n()); std::printf("missing_satellites_n=%.17g\n", v); }
    { double v = static_cast<double>(uqff::salpeter_alpha()); std::printf("salpeter_alpha=%.17g\n", v); }
    { double v = static_cast<double>(uqff::reionization_z()); std::printf("reionization_z=%.17g\n", v); }
    { double v = static_cast<double>(uqff::glueball_0pp_GeV()); std::printf("glueball_0pp_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::v_higgs_GeV()); std::printf("v_higgs_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lambda_QCD_GeV()); std::printf("lambda_QCD_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::inflaton_n_s()); std::printf("inflaton_n_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubble_bubble_pct()); std::printf("hubble_bubble_pct=%.17g\n", v); }
    { double v = static_cast<double>(uqff::v_SCm_one_third_c_m_per_s()); std::printf("v_SCm_one_third_c_m_per_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::U_UA_coupling_constant()); std::printf("U_UA_coupling_constant=%.17g\n", v); }
    { double v = static_cast<double>(uqff::F_U_genesis_n_components()); std::printf("F_U_genesis_n_components=%.17g\n", v); }
    { double v = static_cast<double>(uqff::tde_outflow_velocity_m_per_s()); std::printf("tde_outflow_velocity_m_per_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::d_crit_feedback_loops()); std::printf("d_crit_feedback_loops=%.17g\n", v); }
    { double v = static_cast<double>(uqff::monopole_suppression_exp()); std::printf("monopole_suppression_exp=%.17g\n", v); }
    { double v = static_cast<double>(uqff::gw_damping_BNS()); std::printf("gw_damping_BNS=%.17g\n", v); }
    { double v = static_cast<double>(uqff::gw_damping_BBH()); std::printf("gw_damping_BBH=%.17g\n", v); }
    { double v = static_cast<double>(uqff::T_SCm_activation_K()); std::printf("T_SCm_activation_K=%.17g\n", v); }
    { double v = static_cast<double>(uqff::R_d_duality_range_exp()); std::printf("R_d_duality_range_exp=%.17g\n", v); }
    { double v = static_cast<double>(uqff::F_U_alpha_decay_per_day()); std::printf("F_U_alpha_decay_per_day=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ramanujan_hyperconv_exp()); std::printf("ramanujan_hyperconv_exp=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kerr_ringdown_offset_coeff()); std::printf("kerr_ringdown_offset_coeff=%.17g\n", v); }
    { double v = static_cast<double>(uqff::gw170817_phonon_prefactor()); std::printf("gw170817_phonon_prefactor=%.17g\n", v); }
    { double v = static_cast<double>(uqff::neutron_star_radius_m()); std::printf("neutron_star_radius_m=%.17g\n", v); }
    { double v = static_cast<double>(uqff::neutron_star_mu_s_T_m3()); std::printf("neutron_star_mu_s_T_m3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_ln_10()); std::printf("transcendental_ln_10=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_ln_2()); std::printf("transcendental_ln_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_pi_squared()); std::printf("transcendental_pi_squared=%.17g\n", v); }
    { double v = static_cast<double>(uqff::mad_efficiency_eta_EM()); std::printf("mad_efficiency_eta_EM=%.17g\n", v); }
    { double v = static_cast<double>(uqff::pcr_quantum_triadic()); std::printf("pcr_quantum_triadic=%.17g\n", v); }
    { double v = static_cast<double>(uqff::peters_mathews_coeff()); std::printf("peters_mathews_coeff=%.17g\n", v); }
    { double v = static_cast<double>(uqff::d_bsfg_derived_from_d_crit()); std::printf("d_bsfg_derived_from_d_crit=%.17g\n", v); }
    { double v = static_cast<double>(uqff::k_mex_derived_from_phi_5_6()); std::printf("k_mex_derived_from_phi_5_6=%.17g\n", v); }
    { double v = static_cast<double>(uqff::f221_f220_qnm_ratio()); std::printf("f221_f220_qnm_ratio=%.17g\n", v); }
    { double v = static_cast<double>(uqff::f_geom_one_eighth()); std::printf("f_geom_one_eighth=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_e()); std::printf("transcendental_e=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_e_squared()); std::printf("transcendental_e_squared=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_pi_over_4()); std::printf("transcendental_pi_over_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_catalan_g()); std::printf("transcendental_catalan_g=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_zeta_2()); std::printf("transcendental_zeta_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_zeta_3()); std::printf("transcendental_zeta_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_gamma()); std::printf("transcendental_gamma=%.17g\n", v); }
    { double v = static_cast<double>(uqff::h2o_molar_mass_18()); std::printf("h2o_molar_mass_18=%.17g\n", v); }
    { double v = static_cast<double>(uqff::c_atomic_mass_12()); std::printf("c_atomic_mass_12=%.17g\n", v); }
    { double v = static_cast<double>(uqff::n_atomic_mass_14()); std::printf("n_atomic_mass_14=%.17g\n", v); }
    { double v = static_cast<double>(uqff::o_atomic_mass_16()); std::printf("o_atomic_mass_16=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hemoglobin_15()); std::printf("hemoglobin_15=%.17g\n", v); }
    { double v = static_cast<double>(uqff::heart_rate_70()); std::printf("heart_rate_70=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bp_systolic_120()); std::printf("bp_systolic_120=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bp_diastolic_80()); std::printf("bp_diastolic_80=%.17g\n", v); }
    { double v = static_cast<double>(uqff::breathing_rate_16()); std::printf("breathing_rate_16=%.17g\n", v); }
    { double v = static_cast<double>(uqff::karman_line_100()); std::printf("karman_line_100=%.17g\n", v); }
    { double v = static_cast<double>(uqff::continental_crust_35()); std::printf("continental_crust_35=%.17g\n", v); }
    { double v = static_cast<double>(uqff::oceanic_moho_7()); std::printf("oceanic_moho_7=%.17g\n", v); }
    { double v = static_cast<double>(uqff::rydberg_E_R_eV()); std::printf("rydberg_E_R_eV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::stefan_sigma_lead()); std::printf("stefan_sigma_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hartree_E_h_eV_lead()); std::printf("hartree_E_h_eV_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::z0_vacuum_impedance()); std::printf("z0_vacuum_impedance=%.17g\n", v); }
    { double v = static_cast<double>(uqff::alpha_inverse()); std::printf("alpha_inverse=%.17g\n", v); }
    { double v = static_cast<double>(uqff::compton_lambda_lead()); std::printf("compton_lambda_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::mariana_trench_km()); std::printf("mariana_trench_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::z_recomb_1090()); std::printf("z_recomb_1090=%.17g\n", v); }
    { double v = static_cast<double>(uqff::h0_planck()); std::printf("h0_planck=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_w_GeV()); std::printf("m_w_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_z_GeV()); std::printf("m_z_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_t_GeV()); std::printf("m_t_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_h_higgs_GeV()); std::printf("m_h_higgs_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_tau_GeV()); std::printf("m_tau_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_mu_GeV()); std::printf("m_mu_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_pi_FF()); std::printf("transcendental_pi_FF=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_phi_golden()); std::printf("transcendental_phi_golden=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_sqrt_2()); std::printf("transcendental_sqrt_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_sqrt_3()); std::printf("transcendental_sqrt_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_sqrt_5()); std::printf("transcendental_sqrt_5=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_o16_be_a()); std::printf("nuclear_o16_be_a=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_deuteron_be()); std::printf("nuclear_deuteron_be=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_alpha_be_a()); std::printf("nuclear_alpha_be_a=%.17g\n", v); }
    { double v = static_cast<double>(uqff::co2_atmospheric_ppm()); std::printf("co2_atmospheric_ppm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_bond_albedo()); std::printf("earth_bond_albedo=%.17g\n", v); }
    { double v = static_cast<double>(uqff::steel_yield_MPa()); std::printf("steel_yield_MPa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::steel_youngs_GPa()); std::printf("steel_youngs_GPa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::concrete_density_kg_m3()); std::printf("concrete_density_kg_m3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubble_h0_sh0es()); std::printf("hubble_h0_sh0es=%.17g\n", v); }
    { double v = static_cast<double>(uqff::r_sun_over_r_earth()); std::printf("r_sun_over_r_earth=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_sun_over_m_earth()); std::printf("m_sun_over_m_earth=%.17g\n", v); }
    { double v = static_cast<double>(uqff::concrete_fc_MPa()); std::printf("concrete_fc_MPa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::diamond_mohs()); std::printf("diamond_mohs=%.17g\n", v); }
    { double v = static_cast<double>(uqff::speed_of_sound_air()); std::printf("speed_of_sound_air=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_sun_distance_Gm()); std::printf("earth_sun_distance_Gm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sidereal_year_days()); std::printf("sidereal_year_days=%.17g\n", v); }
    { double v = static_cast<double>(uqff::body_temp_celsius()); std::printf("body_temp_celsius=%.17g\n", v); }
    { double v = static_cast<double>(uqff::blood_glucose_mg_dl()); std::printf("blood_glucose_mg_dl=%.17g\n", v); }
    { double v = static_cast<double>(uqff::adult_height_cm()); std::printf("adult_height_cm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_radius_km()); std::printf("earth_radius_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_core_radius_km()); std::printf("earth_core_radius_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::epsilon_0_lead()); std::printf("epsilon_0_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::mu_0_lead()); std::printf("mu_0_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::coulomb_ke_lead()); std::printf("coulomb_ke_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bohr_radius_a0_lead()); std::printf("bohr_radius_a0_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::rydberg_r_inf_lead()); std::printf("rydberg_r_inf_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::electron_g_factor()); std::printf("electron_g_factor=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bohr_magneton_lead()); std::printf("bohr_magneton_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::wien_b_lead()); std::printf("wien_b_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::planck_h_lead()); std::printf("planck_h_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::speed_of_light_lead()); std::printf("speed_of_light_lead=%.17g\n", v); }
    { double v = static_cast<double>(uqff::solar_constant_Wm2()); std::printf("solar_constant_Wm2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::atm_pressure_kPa()); std::printf("atm_pressure_kPa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::standard_gravity_ms2()); std::printf("standard_gravity_ms2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::carbon_steel_density()); std::printf("carbon_steel_density=%.17g\n", v); }
    { double v = static_cast<double>(uqff::aluminum_density()); std::printf("aluminum_density=%.17g\n", v); }
    { double v = static_cast<double>(uqff::pine_wood_density()); std::printf("pine_wood_density=%.17g\n", v); }
    { double v = static_cast<double>(uqff::moon_distance_ratio()); std::printf("moon_distance_ratio=%.17g\n", v); }
    { double v = static_cast<double>(uqff::jupiter_mass_ratio()); std::printf("jupiter_mass_ratio=%.17g\n", v); }
    { double v = static_cast<double>(uqff::blood_ph()); std::printf("blood_ph=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dna_bp_per_turn()); std::printf("dna_bp_per_turn=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_b_bottom_GeV()); std::printf("m_b_bottom_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_c_charm_GeV()); std::printf("m_c_charm_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_s_strange_GeV()); std::printf("m_s_strange_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_e_electron_GeV()); std::printf("m_e_electron_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_fe56_be_a()); std::printf("nuclear_fe56_be_a=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_ni62_be_a()); std::printf("nuclear_ni62_be_a=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_u235_be_a()); std::printf("nuclear_u235_be_a=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_u238_be_a()); std::printf("nuclear_u238_be_a=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_c12_be_a()); std::printf("nuclear_c12_be_a=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_pb208_be_a()); std::printf("nuclear_pb208_be_a=%.17g\n", v); }
    { double v = static_cast<double>(uqff::omega_m_matter()); std::printf("omega_m_matter=%.17g\n", v); }
    { double v = static_cast<double>(uqff::omega_lambda_dark()); std::printf("omega_lambda_dark=%.17g\n", v); }
    { double v = static_cast<double>(uqff::t_cmb_K()); std::printf("t_cmb_K=%.17g\n", v); }
    { double v = static_cast<double>(uqff::universe_age_Gyr()); std::printf("universe_age_Gyr=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sigma_8_clustering()); std::printf("sigma_8_clustering=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lapse_rate_K_per_km()); std::printf("lapse_rate_K_per_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::au_over_r_earth()); std::printf("au_over_r_earth=%.17g\n", v); }
    { double v = static_cast<double>(uqff::synodic_month_days()); std::printf("synodic_month_days=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_orbital_v_km_s()); std::printf("earth_orbital_v_km_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_age_Gyr()); std::printf("earth_age_Gyr=%.17g\n", v); }
    { double v = static_cast<double>(uqff::avogadro_n_a_aa()); std::printf("avogadro_n_a_aa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::gas_constant_r()); std::printf("gas_constant_r=%.17g\n", v); }
    { double v = static_cast<double>(uqff::h_atomic_mass()); std::printf("h_atomic_mass=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ev_lead_aa()); std::printf("ev_lead_aa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ocean_depth_km()); std::printf("ocean_depth_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::mt_everest_km()); std::printf("mt_everest_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ocean_salinity_ppt()); std::printf("ocean_salinity_ppt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::parsec_per_lightyear()); std::printf("parsec_per_lightyear=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_h3_tritium_be()); std::printf("nuclear_h3_tritium_be=%.17g\n", v); }
    { double v = static_cast<double>(uqff::atm_scale_height_km()); std::printf("atm_scale_height_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::higgs_vev_GeV()); std::printf("higgs_vev_GeV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::neutrino_mass_sum_eV()); std::printf("neutrino_mass_sum_eV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::higgs_trilinear_klam()); std::printf("higgs_trilinear_klam=%.17g\n", v); }
    { double v = static_cast<double>(uqff::top_yukawa_y_t()); std::printf("top_yukawa_y_t=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ckm_row1_unitarity()); std::printf("ckm_row1_unitarity=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lepton_cp_delta()); std::printf("lepton_cp_delta=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hadron_complexity_max()); std::printf("hadron_complexity_max=%.17g\n", v); }
    { double v = static_cast<double>(uqff::string_tension_GeV2()); std::printf("string_tension_GeV2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::br_mu_to_e_gamma()); std::printf("br_mu_to_e_gamma=%.17g\n", v); }
    { double v = static_cast<double>(uqff::uhecr_e_max_eV()); std::printf("uhecr_e_max_eV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::psr_crab_gamma()); std::printf("psr_crab_gamma=%.17g\n", v); }
    { double v = static_cast<double>(uqff::schwarzschild_criterion()); std::printf("schwarzschild_criterion=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bh_seed_mass_msun()); std::printf("bh_seed_mass_msun=%.17g\n", v); }
    { double v = static_cast<double>(uqff::cosmic_filament_dim()); std::printf("cosmic_filament_dim=%.17g\n", v); }
    { double v = static_cast<double>(uqff::pop_iii_imf_max()); std::printf("pop_iii_imf_max=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nfw_concentration()); std::printf("nfw_concentration=%.17g\n", v); }
    { double v = static_cast<double>(uqff::braid_gate_max()); std::printf("braid_gate_max=%.17g\n", v); }
    { double v = static_cast<double>(uqff::quantum_supremacy_qubits()); std::printf("quantum_supremacy_qubits=%.17g\n", v); }
    { double v = static_cast<double>(uqff::tau_entangle_ps()); std::printf("tau_entangle_ps=%.17g\n", v); }
    { double v = static_cast<double>(uqff::holographic_bdy_dim()); std::printf("holographic_bdy_dim=%.17g\n", v); }
    { double v = static_cast<double>(uqff::wc_over_j_phase()); std::printf("wc_over_j_phase=%.17g\n", v); }
    { double v = static_cast<double>(uqff::high_tc_sc_K()); std::printf("high_tc_sc_K=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubbard_u_over_t()); std::printf("hubbard_u_over_t=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ising_universality()); std::printf("ising_universality=%.17g\n", v); }
    { double v = static_cast<double>(uqff::glass_tg_over_tm()); std::printf("glass_tg_over_tm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::jamming_phi_j()); std::printf("jamming_phi_j=%.17g\n", v); }
    { double v = static_cast<double>(uqff::flocking_density()); std::printf("flocking_density=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ee_coupling_fraction()); std::printf("ee_coupling_fraction=%.17g\n", v); }
    { double v = static_cast<double>(uqff::clifford_bundle_qualia()); std::printf("clifford_bundle_qualia=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubbard_mbl_u_t()); std::printf("hubbard_mbl_u_t=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hayflick_a5()); std::printf("hayflick_a5=%.17g\n", v); }
    { double v = static_cast<double>(uqff::t_coherence_K()); std::printf("t_coherence_K=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_field_threshold()); std::printf("earth_field_threshold=%.17g\n", v); }
    { double v = static_cast<double>(uqff::room_temp_sc_max_K()); std::printf("room_temp_sc_max_K=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lawson_uqff()); std::printf("lawson_uqff=%.17g\n", v); }
    { double v = static_cast<double>(uqff::vacuum_breakdown_Vm()); std::printf("vacuum_breakdown_Vm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sigma_lbl_lambda4()); std::printf("sigma_lbl_lambda4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::h0_planck_canonical()); std::printf("h0_planck_canonical=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubble_tension()); std::printf("hubble_tension=%.17g\n", v); }
    { double v = static_cast<double>(uqff::late_isw_amplitude()); std::printf("late_isw_amplitude=%.17g\n", v); }
    { double v = static_cast<double>(uqff::flatness_omega_k()); std::printf("flatness_omega_k=%.17g\n", v); }
    { double v = static_cast<double>(uqff::inflation_efolds()); std::printf("inflation_efolds=%.17g\n", v); }
    { double v = static_cast<double>(uqff::inertia_origin_scale()); std::printf("inertia_origin_scale=%.17g\n", v); }
    { double v = static_cast<double>(uqff::monopole_suppression()); std::printf("monopole_suppression=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dm_direct_floor()); std::printf("dm_direct_floor=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hierarchy_mw_mpl()); std::printf("hierarchy_mw_mpl=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ew_vacuum_stability()); std::printf("ew_vacuum_stability=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ew_vacuum_decay_rate()); std::printf("ew_vacuum_decay_rate=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_w_alt_a5()); std::printf("m_w_alt_a5=%.17g\n", v); }
    { double v = static_cast<double>(uqff::page_curve_recovery()); std::printf("page_curve_recovery=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lorenz_dim()); std::printf("lorenz_dim=%.17g\n", v); }
    { double v = static_cast<double>(uqff::knot_max_crossings()); std::printf("knot_max_crossings=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ks_min_dim()); std::printf("ks_min_dim=%.17g\n", v); }
    { double v = static_cast<double>(uqff::erdos_straus_solvable()); std::printf("erdos_straus_solvable=%.17g\n", v); }
    { double v = static_cast<double>(uqff::w_neg_one_stable()); std::printf("w_neg_one_stable=%.17g\n", v); }
    { double v = static_cast<double>(uqff::time_absolute_f_u1()); std::printf("time_absolute_f_u1=%.17g\n", v); }
    { double v = static_cast<double>(uqff::axiom_count_18()); std::printf("axiom_count_18=%.17g\n", v); }
    { double v = static_cast<double>(uqff::holographic_bulk_bdy()); std::printf("holographic_bulk_bdy=%.17g\n", v); }
    { double v = static_cast<double>(uqff::omega_lambda_6_5_ssq()); std::printf("omega_lambda_6_5_ssq=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lambda_uqff_m_neg2()); std::printf("lambda_uqff_m_neg2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::h0_asymmetry()); std::printf("h0_asymmetry=%.17g\n", v); }
    { double v = static_cast<double>(uqff::phi_res_5_6_ratio()); std::printf("phi_res_5_6_ratio=%.17g\n", v); }
    { double v = static_cast<double>(uqff::factorial_26()); std::printf("factorial_26=%.17g\n", v); }
    { double v = static_cast<double>(uqff::d_crit_4_plus_22()); std::printf("d_crit_4_plus_22=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sum_beta_i_3_2()); std::printf("sum_beta_i_3_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kk_regulator_sum()); std::printf("kk_regulator_sum=%.17g\n", v); }
    { double v = static_cast<double>(uqff::phi_res_anti_omega()); std::printf("phi_res_anti_omega=%.17g\n", v); }
    { double v = static_cast<double>(uqff::d_phys_vs_d_compact_22()); std::printf("d_phys_vs_d_compact_22=%.17g\n", v); }
    { double v = static_cast<double>(uqff::iter_r_a()); std::printf("iter_r_a=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bohm_prefactor()); std::printf("bohm_prefactor=%.17g\n", v); }
    { double v = static_cast<double>(uqff::q_edge_iter()); std::printf("q_edge_iter=%.17g\n", v); }
    { double v = static_cast<double>(uqff::iter_fusion_gain_q()); std::printf("iter_fusion_gain_q=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dt_e_sigma_keV()); std::printf("dt_e_sigma_keV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::troyon_beta_n()); std::printf("troyon_beta_n=%.17g\n", v); }
    { double v = static_cast<double>(uqff::triple_product_nTtau()); std::printf("triple_product_nTtau=%.17g\n", v); }
    { double v = static_cast<double>(uqff::coulomb_log_lnL()); std::printf("coulomb_log_lnL=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lawson_n_tau()); std::printf("lawson_n_tau=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sheath_phi_te()); std::printf("sheath_phi_te=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hierarchy_d_phys_d_crit_21()); std::printf("hierarchy_d_phys_d_crit_21=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lithium_7_factor()); std::printf("lithium_7_factor=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hodge_d_plus_dbsfg_so5()); std::printf("hodge_d_plus_dbsfg_so5=%.17g\n", v); }
    { double v = static_cast<double>(uqff::atiyah_singer_index()); std::printf("atiyah_singer_index=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bh_4_laws_prefactor()); std::printf("bh_4_laws_prefactor=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hierarchy_exponent()); std::printf("hierarchy_exponent=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dpm_pair_k_minus_2()); std::printf("dpm_pair_k_minus_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::taylor_green_nu()); std::printf("taylor_green_nu=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ua_canonical()); std::printf("ua_canonical=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lambda_obs_J_m3()); std::printf("lambda_obs_J_m3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::neutron_lifetime_s()); std::printf("neutron_lifetime_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::neutron_baseline_s()); std::printf("neutron_baseline_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::smooth_poincare_25_3()); std::printf("smooth_poincare_25_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dark_flow_km_s()); std::printf("dark_flow_km_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::muonic_h_radius_fm()); std::printf("muonic_h_radius_fm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::grb_bimodality_s()); std::printf("grb_bimodality_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kk_d_crit_22_alt()); std::printf("kk_d_crit_22_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ledger_100_s_scaling()); std::printf("ledger_100_s_scaling=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kbasis_25_3()); std::printf("kbasis_25_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::neutron_correction_s()); std::printf("neutron_correction_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::n_s_scalar_tilt()); std::printf("n_s_scalar_tilt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kepler_eta_max()); std::printf("kepler_eta_max=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bqp_bound()); std::printf("bqp_bound=%.17g\n", v); }
    { double v = static_cast<double>(uqff::u_i_sun()); std::printf("u_i_sun=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lambda_canonical()); std::printf("lambda_canonical=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ds_phase_inverted()); std::printf("ds_phase_inverted=%.17g\n", v); }
    { double v = static_cast<double>(uqff::goldbach_weak()); std::printf("goldbach_weak=%.17g\n", v); }
    { double v = static_cast<double>(uqff::beal_gcd_gt_1()); std::printf("beal_gcd_gt_1=%.17g\n", v); }
    { double v = static_cast<double>(uqff::np_neq_co_np()); std::printf("np_neq_co_np=%.17g\n", v); }
    { double v = static_cast<double>(uqff::wheeler_dewitt_f_u_0()); std::printf("wheeler_dewitt_f_u_0=%.17g\n", v); }
    { double v = static_cast<double>(uqff::surface_code_threshold()); std::printf("surface_code_threshold=%.17g\n", v); }
    { double v = static_cast<double>(uqff::log_2_e()); std::printf("log_2_e=%.17g\n", v); }
    { double v = static_cast<double>(uqff::pi_over_2()); std::printf("pi_over_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::omega_w1()); std::printf("omega_w1=%.17g\n", v); }
    { double v = static_cast<double>(uqff::khinchin_k()); std::printf("khinchin_k=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sqrt_2pi()); std::printf("sqrt_2pi=%.17g\n", v); }
    { double v = static_cast<double>(uqff::paper_1199_count()); std::printf("paper_1199_count=%.17g\n", v); }
    { double v = static_cast<double>(uqff::direct_locking_count()); std::printf("direct_locking_count=%.17g\n", v); }
    { double v = static_cast<double>(uqff::f_trz_squared()); std::printf("f_trz_squared=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ln_2_alt_phi()); std::printf("ln_2_alt_phi=%.17g\n", v); }
    { double v = static_cast<double>(uqff::flat_rotation_beta_i()); std::printf("flat_rotation_beta_i=%.17g\n", v); }
    { double v = static_cast<double>(uqff::galaxy_types()); std::printf("galaxy_types=%.17g\n", v); }
    { double v = static_cast<double>(uqff::galaxy_subtypes()); std::printf("galaxy_subtypes=%.17g\n", v); }
    { double v = static_cast<double>(uqff::baryon_fraction()); std::printf("baryon_fraction=%.17g\n", v); }
    { double v = static_cast<double>(uqff::z_reion_7_0()); std::printf("z_reion_7_0=%.17g\n", v); }
    { double v = static_cast<double>(uqff::t_21cm_mK()); std::printf("t_21cm_mK=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sf_efficiency()); std::printf("sf_efficiency=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubble_bubble()); std::printf("hubble_bubble=%.17g\n", v); }
    { double v = static_cast<double>(uqff::rvb_threshold()); std::printf("rvb_threshold=%.17g\n", v); }
    { double v = static_cast<double>(uqff::frustration_dim()); std::printf("frustration_dim=%.17g\n", v); }
    { double v = static_cast<double>(uqff::gw_memory_frac()); std::printf("gw_memory_frac=%.17g\n", v); }
    { double v = static_cast<double>(uqff::schwinger_enhanced()); std::printf("schwinger_enhanced=%.17g\n", v); }
    { double v = static_cast<double>(uqff::t_neg_seconds()); std::printf("t_neg_seconds=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sphaleron_energy_eV()); std::printf("sphaleron_energy_eV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dm_suppression()); std::printf("dm_suppression=%.17g\n", v); }
    { double v = static_cast<double>(uqff::d_crit_universal()); std::printf("d_crit_universal=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nfw_c_vir_alt()); std::printf("nfw_c_vir_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sfe_boost_alt()); std::printf("sfe_boost_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::gw_memory_paired()); std::printf("gw_memory_paired=%.17g\n", v); }
    { double v = static_cast<double>(uqff::u_ua_alt()); std::printf("u_ua_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bertrand_p_1_4()); std::printf("bertrand_p_1_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::z_reion_alt()); std::printf("z_reion_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::r_aa_qgp()); std::printf("r_aa_qgp=%.17g\n", v); }
    { double v = static_cast<double>(uqff::e_ankle_eV()); std::printf("e_ankle_eV=%.17g\n", v); }
    { double v = static_cast<double>(uqff::szilard_w_kt()); std::printf("szilard_w_kt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::solar_nu_e_alt()); std::printf("solar_nu_e_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hale_22_alt()); std::printf("hale_22_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::su3_colors_alt()); std::printf("su3_colors_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::delta_cp_alt()); std::printf("delta_cp_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::spin_hall_e2h()); std::printf("spin_hall_e2h=%.17g\n", v); }
    { double v = static_cast<double>(uqff::jamming_alt()); std::printf("jamming_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ee_coupling_alt()); std::printf("ee_coupling_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::codons_64()); std::printf("codons_64=%.17g\n", v); }
    { double v = static_cast<double>(uqff::amino_acids_20()); std::printf("amino_acids_20=%.17g\n", v); }
    { double v = static_cast<double>(uqff::planck_l_qg()); std::printf("planck_l_qg=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_t_over_m_e()); std::printf("m_t_over_m_e=%.17g\n", v); }
    { double v = static_cast<double>(uqff::majorana_via_ftrz()); std::printf("majorana_via_ftrz=%.17g\n", v); }
    { double v = static_cast<double>(uqff::high_tc_alt()); std::printf("high_tc_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kk_d_bsfg_minus_1_alt()); std::printf("kk_d_bsfg_minus_1_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::k_100_s_ledger_scaling()); std::printf("k_100_s_ledger_scaling=%.17g\n", v); }
    { double v = static_cast<double>(uqff::adult_height_170_cm()); std::printf("adult_height_170_cm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::alpha_inverse_137_036()); std::printf("alpha_inverse_137_036=%.17g\n", v); }
    { double v = static_cast<double>(uqff::aluminum_density_2700()); std::printf("aluminum_density_2700=%.17g\n", v); }
    { double v = static_cast<double>(uqff::amino_acids_20_paired()); std::printf("amino_acids_20_paired=%.17g\n", v); }
    { double v = static_cast<double>(uqff::atiyah_singer_dirac_index_22()); std::printf("atiyah_singer_dirac_index_22=%.17g\n", v); }
    { double v = static_cast<double>(uqff::atm_pressure_101_325_kpa()); std::printf("atm_pressure_101_325_kpa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::atm_scale_height_8_5()); std::printf("atm_scale_height_8_5=%.17g\n", v); }
    { double v = static_cast<double>(uqff::au_over_r_earth_23481()); std::printf("au_over_r_earth_23481=%.17g\n", v); }
    { double v = static_cast<double>(uqff::avogadro_n_a_6_022()); std::printf("avogadro_n_a_6_022=%.17g\n", v); }
    { double v = static_cast<double>(uqff::axiom_count_18_v2()); std::printf("axiom_count_18_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::baryon_fraction_50_6()); std::printf("baryon_fraction_50_6=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bayesian_delta_bic_uqff_wins()); std::printf("bayesian_delta_bic_uqff_wins=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bayesian_k_diff_17()); std::printf("bayesian_k_diff_17=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bayesian_k_sm_lcdm_26()); std::printf("bayesian_k_sm_lcdm_26=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bayesian_k_uqff_9()); std::printf("bayesian_k_uqff_9=%.17g\n", v); }
    { double v = static_cast<double>(uqff::beal_gcd_gt_1_v2()); std::printf("beal_gcd_gt_1_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bertrand_uniform_p_1_4()); std::printf("bertrand_uniform_p_1_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bh_4_laws_prefactor_3_125()); std::printf("bh_4_laws_prefactor_3_125=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bh_seed_mass_56160_msun()); std::printf("bh_seed_mass_56160_msun=%.17g\n", v); }
    { double v = static_cast<double>(uqff::blood_glucose_100_mg_dl()); std::printf("blood_glucose_100_mg_dl=%.17g\n", v); }
    { double v = static_cast<double>(uqff::blood_ph_7_4()); std::printf("blood_ph_7_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::body_temp_37_celsius()); std::printf("body_temp_37_celsius=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bohm_prefactor_1_16()); std::printf("bohm_prefactor_1_16=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bohr_magneton_mu_b_9_274()); std::printf("bohr_magneton_mu_b_9_274=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bohr_radius_a0_5_292()); std::printf("bohr_radius_a0_5_292=%.17g\n", v); }
    { double v = static_cast<double>(uqff::bqp_bound_2_pow_d_2()); std::printf("bqp_bound_2_pow_d_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::br_mu_to_e_gamma_127e_13()); std::printf("br_mu_to_e_gamma_127e_13=%.17g\n", v); }
    { double v = static_cast<double>(uqff::braid_gate_max_26()); std::printf("braid_gate_max_26=%.17g\n", v); }
    { double v = static_cast<double>(uqff::carbon_steel_density_7850()); std::printf("carbon_steel_density_7850=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ckm_unitarity_sum_1()); std::printf("ckm_unitarity_sum_1=%.17g\n", v); }
    { double v = static_cast<double>(uqff::clifford_bundle_qualia_8192()); std::printf("clifford_bundle_qualia_8192=%.17g\n", v); }
    { double v = static_cast<double>(uqff::cnub_temp_1_954_k()); std::printf("cnub_temp_1_954_k=%.17g\n", v); }
    { double v = static_cast<double>(uqff::co2_atmospheric_420()); std::printf("co2_atmospheric_420=%.17g\n", v); }
    { double v = static_cast<double>(uqff::codons_64_paired()); std::printf("codons_64_paired=%.17g\n", v); }
    { double v = static_cast<double>(uqff::compton_lambda_2_426()); std::printf("compton_lambda_2_426=%.17g\n", v); }
    { double v = static_cast<double>(uqff::concrete_density_2400()); std::printf("concrete_density_2400=%.17g\n", v); }
    { double v = static_cast<double>(uqff::concrete_fc_30_mpa()); std::printf("concrete_fc_30_mpa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::cosmic_filament_dim_2()); std::printf("cosmic_filament_dim_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::coulomb_ke_lead_8_988()); std::printf("coulomb_ke_lead_8_988=%.17g\n", v); }
    { double v = static_cast<double>(uqff::coulomb_log_17()); std::printf("coulomb_log_17=%.17g\n", v); }
    { double v = static_cast<double>(uqff::d_crit_26_universal_count()); std::printf("d_crit_26_universal_count=%.17g\n", v); }
    { double v = static_cast<double>(uqff::d_crit_4_plus_22_v2()); std::printf("d_crit_4_plus_22_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::d_phys_vs_d_compact_22_v2()); std::printf("d_phys_vs_d_compact_22_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dark_flow_600_km_s()); std::printf("dark_flow_600_km_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::delta_cp_neg_pi2_alt()); std::printf("delta_cp_neg_pi2_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::diamond_mohs_10()); std::printf("diamond_mohs_10=%.17g\n", v); }
    { double v = static_cast<double>(uqff::direct_locking_8_count()); std::printf("direct_locking_8_count=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dm2_21_solar_7_42e_5_ev2()); std::printf("dm2_21_solar_7_42e_5_ev2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dm2_31_atmospheric_2_515e_3_ev2()); std::printf("dm2_31_atmospheric_2_515e_3_ev2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dm31_dm21_ratio_33()); std::printf("dm31_dm21_ratio_33=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dm_direct_floor_lambda4()); std::printf("dm_direct_floor_lambda4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dm_suppression_factor_3()); std::printf("dm_suppression_factor_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dna_bp_per_turn_10_5()); std::printf("dna_bp_per_turn_10_5=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dpm_pair_k_minus_2_1_over_12()); std::printf("dpm_pair_k_minus_2_1_over_12=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ds_phase_inverted_k_mex()); std::printf("ds_phase_inverted_k_mex=%.17g\n", v); }
    { double v = static_cast<double>(uqff::dt_e_sigma_64_kev()); std::printf("dt_e_sigma_64_kev=%.17g\n", v); }
    { double v = static_cast<double>(uqff::e_ankle_3_62e18_ev()); std::printf("e_ankle_3_62e18_ev=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_age_4_54_gyr()); std::printf("earth_age_4_54_gyr=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_bond_albedo_0_3()); std::printf("earth_bond_albedo_0_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_core_radius_3485_km()); std::printf("earth_core_radius_3485_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_field_threshold_50_6()); std::printf("earth_field_threshold_50_6=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_orbital_v_29_78()); std::printf("earth_orbital_v_29_78=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_radius_6371_km()); std::printf("earth_radius_6371_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::earth_sun_distance_149_6_gm()); std::printf("earth_sun_distance_149_6_gm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ee_coupling_alt_6_pct()); std::printf("ee_coupling_alt_6_pct=%.17g\n", v); }
    { double v = static_cast<double>(uqff::electron_electron_frac_6_pct()); std::printf("electron_electron_frac_6_pct=%.17g\n", v); }
    { double v = static_cast<double>(uqff::electron_g_factor_2_0023()); std::printf("electron_g_factor_2_0023=%.17g\n", v); }
    { double v = static_cast<double>(uqff::epsilon_0_lead_8_854()); std::printf("epsilon_0_lead_8_854=%.17g\n", v); }
    { double v = static_cast<double>(uqff::erdos_straus_n_gt_1()); std::printf("erdos_straus_n_gt_1=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ev_lead_1_602()); std::printf("ev_lead_1_602=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ew_vacuum_decay_rate_0()); std::printf("ew_vacuum_decay_rate_0=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ew_vacuum_stability_1()); std::printf("ew_vacuum_stability_1=%.17g\n", v); }
    { double v = static_cast<double>(uqff::f_trz_squared_1_100()); std::printf("f_trz_squared_1_100=%.17g\n", v); }
    { double v = static_cast<double>(uqff::factorial_26_4_03e26()); std::printf("factorial_26_4_03e26=%.17g\n", v); }
    { double v = static_cast<double>(uqff::faraday_f_96485()); std::printf("faraday_f_96485=%.17g\n", v); }
    { double v = static_cast<double>(uqff::flat_rotation_beta_i_6029()); std::printf("flat_rotation_beta_i_6029=%.17g\n", v); }
    { double v = static_cast<double>(uqff::flatness_1_over_d_crit_7()); std::printf("flatness_1_over_d_crit_7=%.17g\n", v); }
    { double v = static_cast<double>(uqff::flocking_rho_0_506()); std::printf("flocking_rho_0_506=%.17g\n", v); }
    { double v = static_cast<double>(uqff::frustration_dim_5()); std::printf("frustration_dim_5=%.17g\n", v); }
    { double v = static_cast<double>(uqff::galaxy_subtypes_24()); std::printf("galaxy_subtypes_24=%.17g\n", v); }
    { double v = static_cast<double>(uqff::galaxy_types_4()); std::printf("galaxy_types_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::gas_constant_r_8_314()); std::printf("gas_constant_r_8_314=%.17g\n", v); }
    { double v = static_cast<double>(uqff::glass_tg_over_tm_3_4()); std::printf("glass_tg_over_tm_3_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::glueball_0pp_1_736_gev()); std::printf("glueball_0pp_1_736_gev=%.17g\n", v); }
    { double v = static_cast<double>(uqff::goldbach_weak_odd_3_primes()); std::printf("goldbach_weak_odd_3_primes=%.17g\n", v); }
    { double v = static_cast<double>(uqff::grb_bimodality_2_s()); std::printf("grb_bimodality_2_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::gw_memory_fraction_6_pct()); std::printf("gw_memory_fraction_6_pct=%.17g\n", v); }
    { double v = static_cast<double>(uqff::gw_memory_paired_h_peak()); std::printf("gw_memory_paired_h_peak=%.17g\n", v); }
    { double v = static_cast<double>(uqff::h0_asymmetry_1_0385()); std::printf("h0_asymmetry_1_0385=%.17g\n", v); }
    { double v = static_cast<double>(uqff::h0_planck_67_41()); std::printf("h0_planck_67_41=%.17g\n", v); }
    { double v = static_cast<double>(uqff::h0_planck_canonical_67_4()); std::printf("h0_planck_canonical_67_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::h_mass_1_008()); std::printf("h_mass_1_008=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hadron_complexity_26()); std::printf("hadron_complexity_26=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hale_22_alt_v2()); std::printf("hale_22_alt_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hartree_e_h_4_36()); std::printf("hartree_e_h_4_36=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hayflick_a5_60_div()); std::printf("hayflick_a5_60_div=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hierarchy_d_phys_over_d_crit_21()); std::printf("hierarchy_d_phys_over_d_crit_21=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hierarchy_exponent_21()); std::printf("hierarchy_exponent_21=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hierarchy_mw_over_mpl_1e_17()); std::printf("hierarchy_mw_over_mpl_1e_17=%.17g\n", v); }
    { double v = static_cast<double>(uqff::higgs_trilinear_kappa_lambda()); std::printf("higgs_trilinear_kappa_lambda=%.17g\n", v); }
    { double v = static_cast<double>(uqff::higgs_vev_246_gev()); std::printf("higgs_vev_246_gev=%.17g\n", v); }
    { double v = static_cast<double>(uqff::high_tc_alt_125_k()); std::printf("high_tc_alt_125_k=%.17g\n", v); }
    { double v = static_cast<double>(uqff::high_tc_superconductor_125_k()); std::printf("high_tc_superconductor_125_k=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hodge_d_plus_dbsfg_over_so5_1()); std::printf("hodge_d_plus_dbsfg_over_so5_1=%.17g\n", v); }
    { double v = static_cast<double>(uqff::holographic_boundary_dim_5()); std::printf("holographic_boundary_dim_5=%.17g\n", v); }
    { double v = static_cast<double>(uqff::holographic_bulk_bdy_6_5()); std::printf("holographic_bulk_bdy_6_5=%.17g\n", v); }
    { double v = static_cast<double>(uqff::horizon_problem_60_efolds()); std::printf("horizon_problem_60_efolds=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubbard_mbl_u_over_t_4()); std::printf("hubbard_mbl_u_over_t_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubbard_u_over_t_4()); std::printf("hubbard_u_over_t_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubble_bubble_30_pct()); std::printf("hubble_bubble_30_pct=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubble_h0_sh0es_70()); std::printf("hubble_h0_sh0es_70=%.17g\n", v); }
    { double v = static_cast<double>(uqff::hubble_tension_5_6_km_s_mpc()); std::printf("hubble_tension_5_6_km_s_mpc=%.17g\n", v); }
    { double v = static_cast<double>(uqff::inertia_origin_10()); std::printf("inertia_origin_10=%.17g\n", v); }
    { double v = static_cast<double>(uqff::information_closure_count_157()); std::printf("information_closure_count_157=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ising_universality_classes_10()); std::printf("ising_universality_classes_10=%.17g\n", v); }
    { double v = static_cast<double>(uqff::iter_q_10()); std::printf("iter_q_10=%.17g\n", v); }
    { double v = static_cast<double>(uqff::iter_r_a_3_1()); std::printf("iter_r_a_3_1=%.17g\n", v); }
    { double v = static_cast<double>(uqff::jamming_phi_j_2_3()); std::printf("jamming_phi_j_2_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::jamming_phi_j_alt_2_3()); std::printf("jamming_phi_j_alt_2_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::jupiter_mass_ratio_317_8()); std::printf("jupiter_mass_ratio_317_8=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kbasis_25_3_universal()); std::printf("kbasis_25_3_universal=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kepler_eta_max_0_7405()); std::printf("kepler_eta_max_0_7405=%.17g\n", v); }
    { double v = static_cast<double>(uqff::khinchin_k_2_6854()); std::printf("khinchin_k_2_6854=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kk_d_bsfg_minus_1_5_paired()); std::printf("kk_d_bsfg_minus_1_5_paired=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kk_d_crit_22_dirac_match()); std::printf("kk_d_crit_22_dirac_match=%.17g\n", v); }
    { double v = static_cast<double>(uqff::kk_regulator_sum_1_624e_37()); std::printf("kk_regulator_sum_1_624e_37=%.17g\n", v); }
    { double v = static_cast<double>(uqff::knot_crossings_bound_26()); std::printf("knot_crossings_bound_26=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ks_contextuality_dim_3()); std::printf("ks_contextuality_dim_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lambda_canonical_rho_scm()); std::printf("lambda_canonical_rho_scm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lambda_obs_5_957e_10()); std::printf("lambda_obs_5_957e_10=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lambda_uqff_1_089e_52()); std::printf("lambda_uqff_1_089e_52=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lapse_rate_6_5_k_km()); std::printf("lapse_rate_6_5_k_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::late_isw_f_trz()); std::printf("late_isw_f_trz=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lawson_n_tau_1_5()); std::printf("lawson_n_tau_1_5=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lawson_uqff_1_44e21()); std::printf("lawson_uqff_1_44e21=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lepton_cp_delta_minus_pi_2()); std::printf("lepton_cp_delta_minus_pi_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lithium_7_factor_3()); std::printf("lithium_7_factor_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ln_2_alt_phi_minus_form()); std::printf("ln_2_alt_phi_minus_form=%.17g\n", v); }
    { double v = static_cast<double>(uqff::log_2_e_1_4427()); std::printf("log_2_e_1_4427=%.17g\n", v); }
    { double v = static_cast<double>(uqff::lorenz_attractor_dim_2_06()); std::printf("lorenz_attractor_dim_2_06=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_2_neutrino_8_5_mev()); std::printf("m_2_neutrino_8_5_mev=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_b_bottom_4_18()); std::printf("m_b_bottom_4_18=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_c_charm_1_27()); std::printf("m_c_charm_1_27=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_d_down_quark_4_67_mev()); std::printf("m_d_down_quark_4_67_mev=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_e_electron_0_000511()); std::printf("m_e_electron_0_000511=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_h_higgs_125_10()); std::printf("m_h_higgs_125_10=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_mu_muon_0_10566()); std::printf("m_mu_muon_0_10566=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_s_strange_0_095()); std::printf("m_s_strange_0_095=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_sun_over_m_earth_333000()); std::printf("m_sun_over_m_earth_333000=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_t_172_76()); std::printf("m_t_172_76=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_t_over_m_e_338000()); std::printf("m_t_over_m_e_338000=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_tau_1_777()); std::printf("m_tau_1_777=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_u_up_quark_2_16_mev()); std::printf("m_u_up_quark_2_16_mev=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_w_80_379()); std::printf("m_w_80_379=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_w_alt_a5_plus_a5_3()); std::printf("m_w_alt_a5_plus_a5_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::m_z_91_188()); std::printf("m_z_91_188=%.17g\n", v); }
    { double v = static_cast<double>(uqff::majorana_via_f_trz()); std::printf("majorana_via_f_trz=%.17g\n", v); }
    { double v = static_cast<double>(uqff::mariana_trench_11()); std::printf("mariana_trench_11=%.17g\n", v); }
    { double v = static_cast<double>(uqff::monopole_count_exp_60()); std::printf("monopole_count_exp_60=%.17g\n", v); }
    { double v = static_cast<double>(uqff::moon_distance_60_336()); std::printf("moon_distance_60_336=%.17g\n", v); }
    { double v = static_cast<double>(uqff::mt_everest_8_848_km()); std::printf("mt_everest_8_848_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::mu_0_lead_1_257()); std::printf("mu_0_lead_1_257=%.17g\n", v); }
    { double v = static_cast<double>(uqff::muonic_h_radius_0_84_fm()); std::printf("muonic_h_radius_0_84_fm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::n_fermion_generations_3()); std::printf("n_fermion_generations_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::n_s_scalar_tilt_0_96468()); std::printf("n_s_scalar_tilt_0_96468=%.17g\n", v); }
    { double v = static_cast<double>(uqff::neutrino_mass_sum_0_0639()); std::printf("neutrino_mass_sum_0_0639=%.17g\n", v); }
    { double v = static_cast<double>(uqff::neutron_correction_46_s()); std::printf("neutron_correction_46_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::neutron_lifetime_879_4_s()); std::printf("neutron_lifetime_879_4_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::neutron_lifetime_baseline_833()); std::printf("neutron_lifetime_baseline_833=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nfw_c_vir_d_bsfg_beta_995()); std::printf("nfw_c_vir_d_bsfg_beta_995=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nfw_concentration_9_95()); std::printf("nfw_concentration_9_95=%.17g\n", v); }
    { double v = static_cast<double>(uqff::np_neq_co_np_v2()); std::printf("np_neq_co_np_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_alpha_be_a_7_0739()); std::printf("nuclear_alpha_be_a_7_0739=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_c12_be_a_7_6802()); std::printf("nuclear_c12_be_a_7_6802=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_deuteron_be_2_2246()); std::printf("nuclear_deuteron_be_2_2246=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_fe56_be_a_8_7903()); std::printf("nuclear_fe56_be_a_8_7903=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_h3_tritium_2_827()); std::printf("nuclear_h3_tritium_2_827=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_ni62_be_a_8_7946()); std::printf("nuclear_ni62_be_a_8_7946=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_o16_be_a_7_9762()); std::printf("nuclear_o16_be_a_7_9762=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_pb208_be_a_7_8675()); std::printf("nuclear_pb208_be_a_7_8675=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_u235_be_a_7_591()); std::printf("nuclear_u235_be_a_7_591=%.17g\n", v); }
    { double v = static_cast<double>(uqff::nuclear_u238_be_a_7_570()); std::printf("nuclear_u238_be_a_7_570=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ocean_depth_3_7_km()); std::printf("ocean_depth_3_7_km=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ocean_salinity_35_ppt()); std::printf("ocean_salinity_35_ppt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::omega_lambda_6_5_ssq_v2()); std::printf("omega_lambda_6_5_ssq_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::omega_lambda_dark_0_685()); std::printf("omega_lambda_dark_0_685=%.17g\n", v); }
    { double v = static_cast<double>(uqff::omega_m_matter_0_315()); std::printf("omega_m_matter_0_315=%.17g\n", v); }
    { double v = static_cast<double>(uqff::omega_w1_0_5671()); std::printf("omega_w1_0_5671=%.17g\n", v); }
    { double v = static_cast<double>(uqff::page_curve_recovery_99596()); std::printf("page_curve_recovery_99596=%.17g\n", v); }
    { double v = static_cast<double>(uqff::parsec_per_lightyear_3_26()); std::printf("parsec_per_lightyear_3_26=%.17g\n", v); }
    { double v = static_cast<double>(uqff::phi_res_5_6_d_minus_1_over_d()); std::printf("phi_res_5_6_d_minus_1_over_d=%.17g\n", v); }
    { double v = static_cast<double>(uqff::phi_res_anti_omega_lambda()); std::printf("phi_res_anti_omega_lambda=%.17g\n", v); }
    { double v = static_cast<double>(uqff::pi_over_2_1_5708()); std::printf("pi_over_2_1_5708=%.17g\n", v); }
    { double v = static_cast<double>(uqff::pine_wood_density_500()); std::printf("pine_wood_density_500=%.17g\n", v); }
    { double v = static_cast<double>(uqff::planck_h_lead_6_626()); std::printf("planck_h_lead_6_626=%.17g\n", v); }
    { double v = static_cast<double>(uqff::planck_l_qg_2_2e_35_m()); std::printf("planck_l_qg_2_2e_35_m=%.17g\n", v); }
    { double v = static_cast<double>(uqff::pop_iii_imf_max_120()); std::printf("pop_iii_imf_max_120=%.17g\n", v); }
    { double v = static_cast<double>(uqff::psr_crab_gamma_302()); std::printf("psr_crab_gamma_302=%.17g\n", v); }
    { double v = static_cast<double>(uqff::q_edge_2()); std::printf("q_edge_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::quantum_supremacy_qubits_60()); std::printf("quantum_supremacy_qubits_60=%.17g\n", v); }
    { double v = static_cast<double>(uqff::r_aa_qgp_0_208()); std::printf("r_aa_qgp_0_208=%.17g\n", v); }
    { double v = static_cast<double>(uqff::r_sun_over_r_earth_109()); std::printf("r_sun_over_r_earth_109=%.17g\n", v); }
    { double v = static_cast<double>(uqff::room_temp_sc_500_k()); std::printf("room_temp_sc_500_k=%.17g\n", v); }
    { double v = static_cast<double>(uqff::rvb_threshold_0_506()); std::printf("rvb_threshold_0_506=%.17g\n", v); }
    { double v = static_cast<double>(uqff::rydberg_e_r_13_6057()); std::printf("rydberg_e_r_13_6057=%.17g\n", v); }
    { double v = static_cast<double>(uqff::rydberg_r_inf_1_0974()); std::printf("rydberg_r_inf_1_0974=%.17g\n", v); }
    { double v = static_cast<double>(uqff::schwarzschild_criterion_0_84()); std::printf("schwarzschild_criterion_0_84=%.17g\n", v); }
    { double v = static_cast<double>(uqff::schwinger_enhanced_1_22e18_vm()); std::printf("schwinger_enhanced_1_22e18_vm=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sf_efficiency_1_75()); std::printf("sf_efficiency_1_75=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sfe_boost_k_phi_1_75()); std::printf("sfe_boost_k_phi_1_75=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sheath_phi_te_2_84()); std::printf("sheath_phi_te_2_84=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sidereal_year_365_25_days()); std::printf("sidereal_year_365_25_days=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sigma_8_clustering_0_811()); std::printf("sigma_8_clustering_0_811=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sigma_lbl_lambda_pow_4()); std::printf("sigma_lbl_lambda_pow_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::smooth_poincare_4d_25_3()); std::printf("smooth_poincare_4d_25_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::solar_constant_1361()); std::printf("solar_constant_1361=%.17g\n", v); }
    { double v = static_cast<double>(uqff::solar_nu_e_1_3_alt()); std::printf("solar_nu_e_1_3_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::speed_of_light_c_2_998()); std::printf("speed_of_light_c_2_998=%.17g\n", v); }
    { double v = static_cast<double>(uqff::speed_of_sound_air_343()); std::printf("speed_of_sound_air_343=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sphaleron_energy_0_875_ev()); std::printf("sphaleron_energy_0_875_ev=%.17g\n", v); }
    { double v = static_cast<double>(uqff::spin_hall_e2_h_paired()); std::printf("spin_hall_e2_h_paired=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sqrt_2pi_2_5066()); std::printf("sqrt_2pi_2_5066=%.17g\n", v); }
    { double v = static_cast<double>(uqff::standard_gravity_9_81()); std::printf("standard_gravity_9_81=%.17g\n", v); }
    { double v = static_cast<double>(uqff::steel_yield_250_mpa()); std::printf("steel_yield_250_mpa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::steel_youngs_200_gpa()); std::printf("steel_youngs_200_gpa=%.17g\n", v); }
    { double v = static_cast<double>(uqff::stefan_sigma_5_67()); std::printf("stefan_sigma_5_67=%.17g\n", v); }
    { double v = static_cast<double>(uqff::string_tension_0_098()); std::printf("string_tension_0_098=%.17g\n", v); }
    { double v = static_cast<double>(uqff::su3_colors_3_alt()); std::printf("su3_colors_3_alt=%.17g\n", v); }
    { double v = static_cast<double>(uqff::sum_beta_i_3_2_v2()); std::printf("sum_beta_i_3_2_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::surface_code_threshold_1_pct()); std::printf("surface_code_threshold_1_pct=%.17g\n", v); }
    { double v = static_cast<double>(uqff::synodic_month_29_53()); std::printf("synodic_month_29_53=%.17g\n", v); }
    { double v = static_cast<double>(uqff::szilard_w_kt_ln_2()); std::printf("szilard_w_kt_ln_2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::t_21cm_minus_289_mk()); std::printf("t_21cm_minus_289_mk=%.17g\n", v); }
    { double v = static_cast<double>(uqff::t_cmb_2_725_k()); std::printf("t_cmb_2_725_k=%.17g\n", v); }
    { double v = static_cast<double>(uqff::t_coherence_99_5_k()); std::printf("t_coherence_99_5_k=%.17g\n", v); }
    { double v = static_cast<double>(uqff::t_neg_minus_2512_s()); std::printf("t_neg_minus_2512_s=%.17g\n", v); }
    { double v = static_cast<double>(uqff::tau_entangle_109_6_ps()); std::printf("tau_entangle_109_6_ps=%.17g\n", v); }
    { double v = static_cast<double>(uqff::taylor_green_nu_1_over_1600()); std::printf("taylor_green_nu_1_over_1600=%.17g\n", v); }
    { double v = static_cast<double>(uqff::time_absolute_f_u_1()); std::printf("time_absolute_f_u_1=%.17g\n", v); }
    { double v = static_cast<double>(uqff::top_yukawa_y_t_natural()); std::printf("top_yukawa_y_t_natural=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_phi_golden_v2()); std::printf("transcendental_phi_golden_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_pi_3_14159()); std::printf("transcendental_pi_3_14159=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_sqrt_2_v2()); std::printf("transcendental_sqrt_2_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_sqrt_3_v2()); std::printf("transcendental_sqrt_3_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::transcendental_sqrt_5_v2()); std::printf("transcendental_sqrt_5_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::triple_product_n_t_tau_3()); std::printf("triple_product_n_t_tau_3=%.17g\n", v); }
    { double v = static_cast<double>(uqff::troyon_beta_n_2_8()); std::printf("troyon_beta_n_2_8=%.17g\n", v); }
    { double v = static_cast<double>(uqff::u_i_sun_2_75e_7()); std::printf("u_i_sun_2_75e_7=%.17g\n", v); }
    { double v = static_cast<double>(uqff::u_ua_canonical_1e_4()); std::printf("u_ua_canonical_1e_4=%.17g\n", v); }
    { double v = static_cast<double>(uqff::ua_canonical_4816()); std::printf("ua_canonical_4816=%.17g\n", v); }
    { double v = static_cast<double>(uqff::uhecr_e_max_7e20_ev()); std::printf("uhecr_e_max_7e20_ev=%.17g\n", v); }
    { double v = static_cast<double>(uqff::universe_age_13_78_gyr()); std::printf("universe_age_13_78_gyr=%.17g\n", v); }
    { double v = static_cast<double>(uqff::vacuum_breakdown_7e13_v_m()); std::printf("vacuum_breakdown_7e13_v_m=%.17g\n", v); }
    { double v = static_cast<double>(uqff::vacuum_stable_w_neg1()); std::printf("vacuum_stable_w_neg1=%.17g\n", v); }
    { double v = static_cast<double>(uqff::wc_over_j_4_phase_transition()); std::printf("wc_over_j_4_phase_transition=%.17g\n", v); }
    { double v = static_cast<double>(uqff::wheeler_dewitt_f_u_0_v2()); std::printf("wheeler_dewitt_f_u_0_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::wien_b_2_898()); std::printf("wien_b_2_898=%.17g\n", v); }
    { double v = static_cast<double>(uqff::z0_vacuum_impedance_v2()); std::printf("z0_vacuum_impedance_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::z_recomb_1090_v2()); std::printf("z_recomb_1090_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::z_reion_7_0_v2()); std::printf("z_reion_7_0_v2=%.17g\n", v); }
    { double v = static_cast<double>(uqff::z_reion_alt_7_70()); std::printf("z_reion_alt_7_70=%.17g\n", v); }
    return 0;
}
