"""
Session 175 -- Generate CP4 appender scripts for PAPER_702-715 / CP4 #286-299.
Follows the same pattern as _gen_cp4_appenders_688_701.py
"""
import os

ROOT = r"C:\Users\tmsjd\source\repos\Daniel8Murphy0007\Star-Magic"
os.chdir(ROOT)

MODULES = [
    (286, "SaturnRingSystemUQFF",              702, "Saturn ring system MUGE2 planetary UQFF gravity equatorial ring tidal EM aether wind"),
    (287, "NGC1275MagneticMonsterUQFF",         703, "NGC 1275 Perseus A magnetic monster Seyfert 1.5 filaments BH feedback MUGE UQFF"),
    (288, "HorseheadNebulaBarnard33UQFF",       704, "Horsehead Nebula Barnard 33 dark nebula radiation pressure erosion infrared UQFF"),
    (289, "NGC3603StarCluster2UQFF",            705, "NGC 3603 star cluster variant 2 Bok globule secondary SF stellar wind UQFF MUGE"),
    (290, "NGC3603StarClusterPrimaryUQFF",      706, "NGC 3603 primary star cluster Carina arm OB stars gas conversion hubble UQFF"),
    (291, "NGC2525BarredSpiral2UQFF",           707, "NGC 2525 barred spiral galaxy variant 2 SN2018gv Type Ia feedback dark matter UQFF"),
    (292, "PillarsOfCreationM16UQFF",           708, "Pillars of Creation Eagle Nebula M16 photoevaporation Ug1 Ug4 Lambda UQFF MUGE"),
    (293, "Westerlund2StarClusterUQFF",         709, "Westerlund 2 super star cluster LMC rapid gas conversion OB winds Ug Lambda UQFF"),
    (294, "NGC2014NGC2020StarformingUQFF",      710, "NGC 2014 NGC 2020 Tapestry Blazing Starbirth LMC WR OB secondary SF UQFF MUGE"),
    (295, "NGC2014NGC2020Variant2UQFF",         711, "NGC 2014 NGC 2020 variant 2 Wolf-Rayet cone oxygen gas 11000K ejecta UQFF"),
    (296, "PillarsOfCreationM16v2UQFF",         712, "Pillars of Creation M16 variant 2 post-supernova protostar jets shockwave UQFF"),
    (297, "UQFFKnowledgeBaseKB19",              713, "UQFF KB19 THz q-scope signals 1-50 bundle integral ACE DCE flow inversion"),
    (298, "UQFFKnowledgeBaseKB18",              714, "UQFF KB18 THz q-scope signals 41-50 set-50 oscilloscope 200ns 500mV flow state"),
    (299, "UQFFKnowledgeBaseKB17",              715, "UQFF KB17 THz q-scope signals 31-40 set-40 Ug1 thread strength U_bi buoyancy"),
]

for cp4_num, cls, paper, desc in MODULES:
    script_name = f"_append_cp4_{cp4_num}.py"
    script_path = os.path.join(ROOT, script_name)
    content = f'''"""
CP4 Appender for PAPER_{paper} -- {cls} (CP4 #{cp4_num})
Auto-generated by _gen_cp4_appenders_702_715.py
"""
import os

CP4 = r"C:\\Users\\tmsjd\\source\\repos\\Daniel8Murphy0007\\Star-Magic\\CondensedPhysics4.py"

ENTRY = """

class {cls}(object):
    # PAPER_{paper}: {desc}

    # UQFF universal constants
    G       = 6.6743e-11
    c       = 3.0e8
    hbar    = 1.0546e-34
    mu_0    = 1.2566e-6
    k_B     = 1.3806e-23
    M_sun   = 1.989e30
    kpc     = 3.086e19
    Mpc     = 3.086e22
    rho_UA  = 7.09e-36
    rho_SCm = 7.09e-37
    f_TRZ   = 0.1
    kappa   = 5.0e-4
    SSq     = 0.57
    mu_J    = 3.38e23
    Lambda  = 1.1e-52
    H_0     = 2.269e-18
    t_H     = 4.35e17

    def __init__(self, dataset=None):
        self.dataset = dataset or {{}}
        self.version = "Session175"

    def compute(self, dataset=None):
        d = dataset or self.dataset
        return {{
            "paper":     "PAPER_{paper}",
            "cp4_entry": {cp4_num},
            "class":     "{cls}",
            "domain":    "{desc}",
            "equations": self._primary_equations(d),
        }}

    def _primary_equations(self, d):
        return {{
            "G":           self.G,
            "rho_UA":      self.rho_UA,
            "rho_SCm":     self.rho_SCm,
            "f_TRZ":       self.f_TRZ,
            "UQFF_factor": 1.0 + self.rho_SCm / self.rho_UA,
        }}

    def self_update(self): pass
    def self_expand(self): pass

"""


def _append():
    if not os.path.exists(CP4):
        print(f"ERROR: CondensedPhysics4.py not found at {{CP4}}")
        return
    with open(CP4, "r", encoding="latin-1") as f:
        content = f.read()
    marker = "class {cls}"
    if marker in content:
        print(f"SKIP: {cls} already present in CondensedPhysics4.py")
        return
    with open(CP4, "a", encoding="utf-8") as f:
        f.write(ENTRY)
    print(f"OK: Appended {cls} (PAPER_{paper}, CP4 #{cp4_num})")


if __name__ == "__main__":
    _append()
'''
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Created {script_name}")

print(f"\nDone. 14 appender scripts created for CP4 #286-299.")
