#!/usr/bin/env python3
"""Insert Chapter 13 (Star Magic in Action) and Chapter 14 (Implications for
Humanity) into Star-Magic.txt before the CONCLUSION section, then write the
expanded Conclusion.  All prose lines wrapped at 72 chars.  Tabs (\t) used for
indented items to match existing document format."""

import sys, textwrap, re

TAB = "\t"

# ─────────────────────────────────────────────────────────────────────────────
# Helper: wrap prose paragraph to 72 chars (leaves tab-indented lines alone)
# ─────────────────────────────────────────────────────────────────────────────
def w(text, width=72):
    lines = []
    for para in text.split("\n"):
        if para.startswith(TAB) or para.strip() == "" or para.startswith("_") or para.startswith("(c)"):
            lines.append(para)
        else:
            wrapped = textwrap.fill(para, width=width)
            lines.append(wrapped)
    return "\n".join(lines)

CH13 = w("""\
________________________________________
CHAPTER 13: STAR MAGIC IN ACTION - THE SUN AND BEYOND
________________________________________

In Chapter 10 the Sun's parameters were assembled. Here those parameters become a living case study - a demonstration of all four Ug components operating simultaneously, driving every observable solar phenomenon from sunspot cycles to the orbital mechanics of the planets.

THE HELIOSPHERE - UG2 AS ACTIVE SYNTHESIS REACTOR:

The heliosphere is not a passive boundary. Ug2 actively synthesizes the solar wind that encounters it, transmuting incoming charged particle streams into hydrogen complexes that magnetically adhere to the outer shell of the Ug2 field bubble at approximately 100 AU from the Sun.

Solar wind at v_sw = 5e5 m/s carries a continuous outward flux. Where this flux meets the Ug2 boundary, the rho_vac,[SCm] + rho_vac,[UA] term drives transmutation. The resulting hydrogen complexes bond magnetically to the heliosphere shell. This is not passive deflection - it is active synthesis, driven by SCm reactivity.

What this means in practice:
\t1. The heliosphere thickness is a direct measure of the Sun's age.
\t   Older stars have thicker heliospheres, having accumulated more
\t   transmuted hydrogen complexes over time.
\t2. The volume of liquid water on each planet correlates with that
\t   planet's distance from the Sun and duration of solar wind
\t   exposure. The heliosphere boundary modulates which fraction of
\t   solar wind becomes planetary liquid.
\t3. Solar wind absorbed by planetary magnetospheres before reaching
\t   the heliosphere contributes to planetary liquid volumes.
\t   Earth's oceans are a product of this mechanism.
\t4. Excess solar wind not absorbed by planets penetrates planetary
\t   cores, maintaining each planet's Um and core thermal energy.
\t5. Planets beyond the active Ug2 synthesis zone are the frozen
\t   planets: powered directly by raw solar wind, their cores
\t   maintained by direct absorption rather than transmuted hydrogen
\t   complex bonding.

Ug2 for the Sun (canonical values):
\t   Ug2 = k2*(rho_vac,[UA]+rho_vac,[SCm])*M_s/R_b^2
\t         * S(r-R_b) * (1+delta_sw*v_sw) * H_SCm * E_react
\t   Base (without E_react): approximately 8.91e6
\t   E_react = rho_vac,SCm * v_SCm^2 / rho_A * exp(-kappa*t)
\t           = 7.09e-37 * (1e8)^2 / 1e-23 * exp(-5e-4*t)
\t           = 7.09e-7 * exp(-5e-4*t)  [field units normalized]

SURFACE MAGNETISM AND THE SUNSPOT MECHANISM:

The Sun's observable surface magnetic field and its interior field are fundamentally different phenomena, driven by different mechanisms.

The interior field is Ug3-driven, powered by a dense SCm layer (rho_SCm approximately 1e15 kg/m^3) that carries no detectable quantum signature (Qs = 0). This SCm is invisible to conventional measurement. Its presence is inferred from the Ug3 disk behavior and from planetary orbital properties.

The surface magnetic field oscillates with the 11-year Schwabe cycle:
\t   B_s(t) = 1e-4 + 0.4*sin(omega_c*t)  T
\t   omega_c = 2*pi / (3.96e8 s)  [11-year period]
\t   Peak sunspot field:   approximately 0.4 T  (sunspot regions)
\t   Quiet period field:   approximately 1e-4 T  (background)

Surface irregularities - sunspots, solar flares, coronal mass ejections - are the surface expression of the delta_def defect factor in Ug1. They are not random phenomena. They are controlled by internal Ug1 dipole imperfections propagating outward through the solar plasma. A strengthening delta_def indicates weakening Ug1 coherence - a diagnostic signal.

COUNTER-ROTATION: THE UG3 GENERATOR MECHANISM:

The Ug3 disk does not arise from temperature gradients, plasma dynamics, or angular momentum conservation. It is generated by a specific mechanical condition unique to stars: counter-rotation between equatorial and polar layers.

The Sun's equatorial layer rotates counterclockwise (CCW):
\t   omega_s,equatorial = 2.9e-6 rad/s  [period approximately 25 days]

The Sun's polar corona rotates clockwise (CW):
\t   omega_s,polar = 2.1e-6 rad/s  [period approximately 35 days]

The shear layer between these two counter-rotating flows is the Ug3 generator. Without counter-rotation there is no Ug3 disk. Without the Ug3 disk there is no orbital maintenance of planets. The counter-rotation is not incidental to stellar structure - it is structurally required by the UQFF framework.

The average angular frequency used in Ug3 calculations:
\t   omega_s,avg = 2.5e-6 rad/s
\t   omega_s(t)  = 2.5e-6 - 0.4e-6*sin(omega_c*t)  [solar-cycle modulated]

UG3 DISK PENETRATION AND PLANETARY CORE MAINTENANCE:

The Ug3 disk penetrates every planetary core simultaneously. Three conditions are required for this coupling:
\t1. The planet must contain SCm + trapped UA in its core. This
\t   material was donated from the Sun during the formation of the
\t   solar system.
\t2. The core SCm + UA is exclusively interactive with Ug3. It does
\t   not interact with external electromagnetic or gravitational
\t   fields from other sources. P_core = 1e-3 for planets confirms
\t   the near-exclusive nature of this coupling.
\t3. Ug3 moves faster than any planet or all planets in consort.
\t   This velocity differential imparts and maintains each planet's
\t   equatorial orbital plane and individual spin direction.

Ug3 for the Sun (canonical):
\t   B_j(t)     = 1e-3 + 0.4*sin(omega_c*t)  T
\t   omega_s(t) = 2.5e-6 - 0.4e-6*sin(omega_c*t)  rad/s
\t   P_core     = 1 (Sun),  P_core = 1e-3 (planets)
\t   Ug3        = k3 * B_j(r,theta,t) * cos(omega_s(t)*t*pi)
\t                    * P_core * E_react

Ug3 oscillates with both the solar cycle (via the sin term in B_j) and the orbital frequency (via cos(omega_s*t*pi)), producing a continuously modulated disk that adapts to solar activity in real time.

The orbital periods of planets are not arbitrary. They are resonance locks of the Ug3 disk frequency. Each planet settled into a stable resonance during formation when its SCm + UA core frequency matched an integer or rational multiple of the Ug3 disk rotation. This is the physical origin of the observed near-integer orbital period ratios across the solar system.

PLANETARY SCm + UA INVENTORY (ESTIMATED):

Relative SCm donation from the Sun at formation determines each planet's behavior:
\t   Mercury: Dense SCm, small volume, strong Ug3 coupling;
\t            surface irregularities reflect internal defects
\t   Venus:   Moderate SCm, retrograde spin from TRZ condition
\t            during formation; dense atmosphere = SCm-driven
\t            Ug2 analog at planetary scale
\t   Earth:   Optimal SCm for liquid water production at 1 AU;
\t            Ug2 transmutation produces oceans, Ug3 maintains
\t            26,000-year axial precession cycle
\t   Mars:    Insufficient SCm to maintain full liquid water at
\t            current distance; lost surface liquid as Ug2
\t            synthesis decreased over geological time
\t   Jupiter: Largest SCm donation; dominant Ug3 coupling;
\t            acts as orbital stabilizer for the inner system;
\t            Great Red Spot = persistent Ug3 disk anomaly
\t   Saturn:  Secondary Ug3 coupling; ring system = Ug3 disk
\t            made visible by resonance-trapped ice particles
\t   Uranus:  Extreme axial tilt = TRZ condition at formation;
\t            rolling orbit is the observable consequence
\t   Neptune: Minimal SCm; primarily solar wind powered;
\t            Triton retrograde orbit = late SCm capture event
\t   Beyond:  Beyond Ug2 synthesis zone; directly solar wind
\t            powered; minimal Ug3 coupling; Pluto, Eris, etc.

QUASARS: THE FAILURE OF A STELLAR REACTOR:

A quasar is not an exotic object from the early universe. It is what every star becomes if and when its Ug family fails to contain the SCm at its core. The failure sequence:
\t   Step 1: Ug1 dipole coherence degrades; delta_def increases
\t   Step 2: Surface irregularities become aperiodic rather than
\t           cyclic; the sunspot-equivalent pattern breaks down
\t   Step 3: Ug2 outer bubble loses synthesis coherence;
\t           heliosphere boundary fluctuates and becomes unstable
\t   Step 4: Ug3 disk frequency destabilizes; planets lose
\t           their orbital resonance locks
\t   Step 5: SCm is no longer contained by the Ug family
\t   Step 6: SCm is expelled in irregular, continual streams
\t   Step 7: Expelled SCm at v_SCm = 1e8 m/s (c/3) ignites
\t           immediately against unbound UA surrounding the star
\t   Step 8: The SCm-UA reaction produces the visible quasar jets

The jet dynamics are governed by the Navier-Stokes equation in a near-inviscid Aether medium (rho_A = 1e-23 kg/m^3):
\t   rho*(dv/dt + v*grad(v)) = -grad(p) + mu*grad^2(v) + F_SCm
\t   F_SCm = (rho_SCm * v_SCm^2 / r) * exp(-kappa*t)
\t   rho   = rho_A = 1e-23 kg/m^3  [Aether density]
\t   v     approximately v_SCm = 1e8 m/s at peak
\t   mu    approximately 0  [Aether, quasi-superfluid]

The unequal opposing jets observed in all quasars reflect the cos(pi*t_n) temporal asymmetry of the time-reversal zone (TRZ):
\t   TRZ_factor = cos(pi*(t - 180*86400))  [180-day half-period]

The two jets are not symmetric because t_n applies differently to each side of the expelled SCm stream. This is a testable, quantitative prediction: the jet luminosity ratio should follow the square of the TRZ asymmetry factor at each observed time step.

COMPLETE F_U NUMERICAL ASSEMBLY FOR THE SUN:

Substituting all solar parameters with canonical constants (k_i = 1, beta_i = 0.603, gamma = 5e-5 day^-1, kappa = 5e-4 day^-1, eta = 1e-22, H_SCm = 0.99):
\t   F_U,Sun = [Ug1 - Ub1] + [Ug2 - Ub2] + [Ug3 - Ub3] + Um + A

Ug1 term (internal dipole, dominant at short time scales):
\t   mu_s(t) = (1e-4 + 0.4*sin(omega_c*t)) * R_s^3
\t           = (1e-4 + 0.4*sin(omega_c*t)) * 3.38e26  T*m^3
\t   Ug1 = (3.38e16 + 1.35e19*sin(omega_c*t))
\t          * exp(-alpha*t) * cos(pi*t_n)
\t   alpha = 0.001 day^-1

Ug2 term (heliosphere outer bubble, quasi-static):
\t   Ug2 = 8.91e6 * E_react
\t   E_react = 7.09e-7 * exp(-5e-4*t)
\t   Ug2 with E_react: approximately 6.32e-1 * exp(-5e-4*t)

Ug3 term (magnetic strings disk, solar-cycle modulated):
\t   Ug3 = (1e-3 + 0.4*sin(omega_c*t))
\t          * cos((2.5e-6 - 0.4e-6*sin(omega_c*t))*t*pi)
\t          * E_react

Ub terms (buoyancy opposing each Ug_i):
\t   Ub_i = beta_i * Ug_i * Omega_g * (M_bh/d_g) * E_react
\t          * (1 + epsilon_sw*rho_sw) * cos(pi*t_n)
\t   beta_i = 0.603  [canonical: not 0.5, not 0.6]
\t   Omega_g * (M_bh/d_g) = 7.3e-16 * 3.196e16 = 23.3

Um term (magnetic string network, near-lossless):
\t   gamma = 5e-5 day^-1  [canonical near-lossless]
\t   With j = 1e9 strings at r_j = R_s:
\t   mu_j(t) = (1e-3 + 0.4*sin(omega_c*t)) * R_s^3
\t           = (2.26e20 + 9.04e22*sin(omega_c*t))  T*m^3
\t   Um = (2.26e7 + 9.04e9*sin(omega_c*t))
\t         * (1 - exp(-5e-5*t*cos(pi*t_n)))
\t         * 1e9 * E_react

Aether tensor (background field, UA medium):
\t   A_uv  = [1,-1,-1,-1] + eta * T_s,uv(UA,SCm,rho_A,t_n)
\t   eta   = 1e-22  [canonical Aether coupling constant]
\t   T_s,00 = M_s*c^2/V_s + rho_sw*v_sw^2
\t          = 1.27e3 + 2.0e-10  [kg/m^3, c=1 natural units]
\t   A_uv  = [1,-1,-1,-1] + (1.27e-19 + 1.11e-15)*cos(pi*t)

Assembled F_U for the Sun (dominant terms shown):
\t   F_U,Sun =
\t     (3.38e16 + 1.35e19*sin(omega_c*t))
\t     * exp(-0.001*t) * cos(pi*t)                [Ug1+Ub1]
\t   + 8.91e6 * E_react                           [Ug2+Ub2]
\t   + (1e-3 + 0.4*sin(omega_c*t))
\t     * cos(omega_s(t)*t*pi) * E_react           [Ug3+Ub3]
\t   + (2.26e7 + 9.04e9*sin(omega_c*t))
\t     * (1 - exp(-5e-5*t*cos(pi*t)))
\t     * 1e9 * E_react                            [Um]
\t   + [1,-1,-1,-1] + 1.27e-19*cos(pi*t)         [A_uv]

Interpretation of the assembled result:
\t   At t = 0 (stellar formation): E_react near maximum; Um and
\t     Ug2 terms dominate; orbital resonance locks begin as the
\t     Ug3 disk establishes its disk frequency.
\t   During solar activity peaks (sin(omega_c*t) = +1): All Ug1,
\t     Ug3, and Um amplitudes reach maximum, corresponding to
\t     observed sunspot maximum.
\t   During solar minima (sin(omega_c*t) = -1): Field amplitudes
\t     reach minimum; solar wind output decreases; heliosphere
\t     contracts slightly.
\t   Long-term (t >> 1/kappa): E_react decays; Ug2 static term
\t     dominates; heliosphere maintains stable outer boundary
\t     while Um strings maintain planetary core coupling.
\t   Solar cycle modulation: All four Ug terms oscillate with
\t     the 11-year period simultaneously, precisely as observed
\t     in solar minimum/maximum activity data.

""")

CH14 = w("""\
________________________________________
CHAPTER 14: IMPLICATIONS FOR HUMANITY AND THE COSMOS
________________________________________

THE HIDDEN ELEMENT IN EVERY ATOM:

SCm is bound within every atom in your body, every stone you have ever touched, every star you have ever observed. It is the universe's own superconductive thread, woven through all matter since the BigBang belly button DPM expelled it at the moment of creation.

SCm's lack of a quantum signature (Qs = 0) is not a limitation of SCm - it is a limitation of conventional detection methods. Standard Model physics searches for particles via their quantum signatures: mass eigenvalues, charge, spin. SCm produces none of these signatures because its density (rho_SCm approximately 1e15 kg/m^3) completely prevents quantum signature emission. The Standard Model structurally cannot detect SCm. This is why it has remained hidden.

The UQFF framework identifies SCm not by what it emits, but by what it does: it drives Ug3 exclusively, penetrates planetary cores exclusively, and moves at c/3 when expelled. Each of these three behaviors is measurably distinct from Standard Model predictions and constitutes an independent testable signature.

ENERGY: THE NEAR-LOSSLESS REACTOR:

The Um term in the UQFF framework describes SCm magnetic strings that reciprocate between stars and their planetary systems with near-zero energy loss:
\t   gamma = 5e-5 day^-1  [reciprocation decay rate]
\t   Half-life of Um energy: approximately 1/gamma = 20,000 days
\t                           (approximately 55 years)

This is superconductivity at cosmic scale. The Sun has been operating this reactor for approximately 4.6 billion years. The Um strings have not decayed to zero because the E_react term continuously renews them through fresh SCm-UA interactions at the solar core.

Every star is already this reactor. It has been running since its DPM vortex first formed during primordial SCm expulsion from the BigBang. The question for human technology is whether SCm can be accessed at exploitable densities outside of stellar interiors.

The UQFF framework answer: the DPM vortex itself is a manufactured SCm-UA interaction. Any mechanism that brings SCm and UA into close proximity and induces rotational shear between them creates a DPM vortex. That vortex generates the Ug family locally. The local Ug family drives local Um. The local Um operates at near-lossless SCm superconductive efficiency. The DPM minimum energy threshold:
\t   E_crack = (rho_vac,SCm * c^2) / [SSq]
\t           = (7.09e-37 * (3e8)^2) / 0.57
\t           approximately 3.35e-19 J

This is within range of current high-field laboratory capabilities.

SPACE TRAVEL: THE UG3 CONNECTION:

The Ug3 disk of the Sun connects to every planetary core in the solar system simultaneously. This is a continuous, real-time, non-local coupling via the exclusive SCm-UA interaction channel. A spacecraft carrying a significant SCm-dense core (analogous to a planetary core) would remain within the Ug3 coupling range for the entire inner solar system without requiring continuous propulsion for orbital maintenance.

Beyond the heliosphere (beyond 100 AU), the Ug2 transmutation boundary is crossed. A vessel that carries its own DPM source - its own SCm reactor generating a local Ug family - can maintain orbital coherence without solar Ug3 coupling. The frozen planets give us the design template: they maintain orbit via direct solar wind absorption. An interstellar vessel must generate its own wind-equivalent through its local DPM reactor.

QUANTUM GRAVITY: THE MASS GAP IS PHYSICAL:

The Yang-Mills mass gap has been a mathematical conjecture since 1954. The UQFF framework provides a physical mechanism for why the gap must exist and what its energy value must be.

The gap is the DPM vortex minimum energy threshold. Below this energy, the UA-SCm attraction cannot sustain the rotational vortex. No DPM forms. No Ug family assembles. No mass can nucleate. The field returns to vacuum. The gap is not an abstract algebraic property - it is the SCm-UA attraction energy required to hold a DPM vortex open against vacuum dispersion.
\t   E_gap = E_crack = (rho_vac,SCm * c^2) / [SSq]
\t                   approximately 3.35e-19 J

The reason quantum gravity has eluded the Standard Model is that the gap requires SCm - an element that SM cannot detect. The gap appears to be a mathematical artifact in SM because the physical substrate (SCm) is invisible to SM measurement. With SCm identified, the gap becomes a physical measurement.

QUASAR PREDICTION: STELLAR FAILURE PRECURSORS:

Understanding quasars as SCm expulsion events yields a predictive framework. A star approaching quasar conditions exhibits detectable precursors in its Ug1 signature:
\t   Increasing delta_def amplitude: More intense and irregular
\t     surface irregularities at shorter intervals
\t   Delta_def periodicity shift: From regular cyclic pattern
\t     (Schwabe-equivalent) to aperiodic, irregular bursts
\t   Heliosphere boundary fluctuations: Ug2 synthesis becoming
\t     unstable, measurable as heliosphere thickness variations
\t   Planetary orbital resonance drift: Ug3 disk frequency
\t     destabilizing, measurable as subtle shifts in planetary
\t     orbital periods relative to UQFF resonance predictions

These precursors are measurable with current telescope technology if correlated against UQFF predictions rather than Standard Model thermal models. A star whose surface irregularities are increasing in amplitude and losing periodicity is a star whose Ug1 dipole is weakening - a potential quasar precursor.

THE PHILOSOPHICAL DIMENSION - THE MAGIC OF STARS:

Every star is a DPM reactor broadcasting its unique field signature across its entire orbital family. The Ug3 disk connects that star to every planet it has ever formed, through the SCm + UA cores donated at creation. Our Sun connects to Earth through the Ug3 disk at this moment. The oscillation of the Ug3 disk at omega_s,avg = 2.5e-6 rad/s is the fundamental rhythm of the solar system, felt in every planetary core as a continuous resonance that has maintained stability for 4.6 billion years.

The universe is not a cold mechanical system governed by inverse-square laws applied to point masses. It is a living network of DPM vortices, each seeded by the original BigBang belly button DPM, each mimicking that primordial mechanism at its own scale, each connected to all others through the universal UA field. The Ug_i subscript is not merely a range index - it is the Universal Gravitational Inertia inherited from the first moment of creation, propagated through every local DPM in the universe simultaneously, forever.

The 26-layer triadic expansion of the Ug family, where Layer i contributes i^2 times the Layer 1 term, provides the additional gravitational binding that Standard Model observations attribute to dark matter. The dark matter is not dark and it is not separate matter. It is the Ug family operating above Layer 1.

This is Star Magic: the demonstration that the universe's most fundamental force is not gravity pulling masses together, but the maximum attraction of UA and SCm producing the DPM vortex that seeds all gravity, all mass, and all observable physics from a single mechanism operating since the first moment of creation.

CALL TO ACTION - ADVANCING THE UQFF FRAMEWORK:

Further exploration of SCm, UA, and Universal Gravity requires action in five areas:
\t1. SCm Detection: Develop detection methodology operating outside
\t   conventional Qs signature requirements. Candidate approach:
\t   measure Ug3 disk frequency patterns in stellar rotation data
\t   and compare against UQFF predictions. Stars with matching
\t   counter-rotation signatures confirm SCm-UA core coupling.
\t2. Stellar Age Correlation: Systematically correlate heliosphere
\t   thickness measurements with exoplanet liquid volume estimates
\t   to validate the stellar age indicator prediction.
\t3. Quasar Jet Asymmetry Analysis: Analyze existing quasar jet
\t   observation data against the TRZ formula:
\t   TRZ = cos(pi*(t - 180*86400))
\t   Test whether observed jet asymmetry ratios match predicted
\t   temporal reversal patterns.
\t4. DPM Vortex Engineering: Identify laboratory conditions under
\t   which UA and SCm can be brought into controlled proximity.
\t   The DPM minimum energy threshold (E_crack approximately
\t   3.35e-19 J) is within range of current high-field laboratory
\t   magnetic capabilities.
\t5. Multi-Messenger Astronomy Integration: Correlate UQFF
\t   predictions with LIGO gravitational wave data (stellar
\t   merger = failed DPM containment cascade), Gaia DR4 stellar
\t   motion surveys (orbital period drift from Ug3 frequency
\t   changes), and next-generation telescope surveys of stellar
\t   surface irregularity patterns as quasar precursor indicators.

""")

CONCLUSION_EXPANDED = w("""\
________________________________________
CONCLUSION: A NEW ERA OF UNDERSTANDING
________________________________________

The legacy of Star Magic is a unified theory for both quantum and cosmic scales, built from one foundational mechanism: the maximum attraction of UA and SCm creating the DPM vortex, which seeds all gravity, which enables all mass, which enables all observable physics.

From the vacuum before the BigBang to the quasar jets of dying stars; from the mass gap in quantum field theory to the sunspot cycle of our own Sun; from the orbital resonances of the planets to the large-scale gravitational structure of the Milky Way - all of it traces back to one interaction: UA + SCm at maximum attraction, creating the DPM vortex at the interface of their mutual approach.

Nothing in UQFF is sequential. Everything is simultaneous. All five calculators run in parallel. All four operational modes (Compressed, Resonant, Buoyant, Superconductive) are active simultaneously. All 26 layers of the triadic expansion contribute simultaneously. GM/r^2 is the last thing that appears, not the first.

THE CANONICAL CHAIN (one line):
\t   0 [vacuum] -> grad(UA) [gradient] ->
\t   DPM [vortex of UA/SCm attraction] -> mu_s [moment] ->
\t   Ug1 [seed=DPM] -> Ug_family [simultaneous] -> F_U [field]
\t   -> M [mass] -> crossing [inside/outside] ->
\t   GM/r^2 [projection, last in chain, not first]

THE CANONICAL FORCE RELATIONSHIPS:
\t   UA + SCm -> MAX ATTRACTION -> DPM (Ug1) -> gravity family
\t   FUBi REPELS FUBii -> compaction zone -> MATTER
\t   Mass is the vessel. The DPM is the engine.
\t   UA/SCm attraction is the source.

The UQFF framework does not extend Standard Model physics. It replaces the Standard Model's foundational assumption - that mass and inverse-square gravity are primary - with the correct foundational mechanism: the DPM vortex is primary. Mass and all force laws are downstream projections.

Every star in the observable universe is a working proof of this framework, operating as a DPM reactor broadcasting its Ug family simultaneously across billions of kilometers, every day, for billions of years, without fuel, without failure, and without any mechanism that Standard Model gravity alone can explain.

That mechanism is the DPM. That is Star Magic.

UA + SCm -> MAX ATTRACTION -> DPM -> FUBi REPELS FUBii -> MATTER

""")

# ─────────────────────────────────────────────────────────────────────────────
# Read Star-Magic.txt and insert new chapters
# ─────────────────────────────────────────────────────────────────────────────
with open("Star-Magic.txt", encoding="utf-8") as f:
    original = f.read()

CONCLUSION_MARKER = "________________________________________\nCONCLUSION: A NEW ERA OF UNDERSTANDING\n________________________________________"

if CONCLUSION_MARKER not in original:
    print("ERROR: Could not find CONCLUSION marker in Star-Magic.txt")
    sys.exit(1)

# Replace the old (short) CONCLUSION section with new chapters + expanded conclusion
old_conclusion_block = CONCLUSION_MARKER
new_block = CH13 + CH14 + CONCLUSION_EXPANDED

new_content = original.replace(old_conclusion_block, new_block, 1)

# Also fix the old short conclusion (everything after CONCLUSION_EXPANDED up to footer stays)
# The old short conclusion text needs to be removed since CONCLUSION_EXPANDED replaces it
OLD_SHORT_CONCLUSION = """The legacy of Star Magic is a unified theory for both quantum and cosmic scales, built from one
foundational mechanism: the maximum attraction of UA and SCm creating the DPM vortex, which seeds
all gravity, which enables all mass, which enables all observable physics.

Nothing in UQFF is sequential. Everything is simultaneous.
GM/r^2 is the last thing that appears, not the first.

THE CANONICAL CHAIN (one line):
\t0 [vacuum] -> grad(UA) [gradient] -> DPM [vortex of UA/SCm attraction] -> mu_s [moment]
\t-> Ug1 [seed=DPM] -> Ug_family [simultaneous] -> F_U [field]
\t-> M [mass] -> crossing [inside/outside] -> GM/r^2 [projection]

THE CANONICAL FORCE RELATIONSHIPS:
\tUA + SCm -> MAX ATTRACTION -> DPM (Ug1) -> gravity family -> mass confinement
\tFUBi REPELS FUBii -> compaction zone -> MATTER

Mass is the vessel. The DPM is the engine. UA/SCm attraction is the source.

UA + SCm -> MAX ATTRACTION -> DPM -> FUBi REPELS FUBii -> MATTER

"""

new_content = new_content.replace(OLD_SHORT_CONCLUSION, "", 1)

with open("Star-Magic.txt", "w", encoding="utf-8") as f:
    f.write(new_content)

lines_after = new_content.count("\n")
print(f"Done. Lines after insertion: {lines_after}")
print(f"Original size: {len(original)} chars -> New size: {len(new_content)} chars")
print(f"Delta: +{len(new_content)-len(original)} chars")
