#!/usr/bin/env python3
"""
_uqff_reference_documentation.py - PAPERS Registry [SESSION 202+]

MIRRORED LINE-BY-LINE with _uqff_primitives.py
Each line N = papers for constant N in primitives.py
"""

from dataclasses import dataclass
from typing import List

@dataclass
class ReferenceDocument:
    name: str
    papers: List[str]

class ReferenceDocumentationRegistry:
    PAPERS = [
        ReferenceDocument("F_TRZ", ["Session 237-241: Time-reversal zone suppression factor derivation"]),
        ReferenceDocument("PHI_RES", ["PAPER_591: Fine-structure constant derivation, resonance phase factor"]),
        ReferenceDocument("SSQ", ["Cosmological calibration: Squared-Sum Vacuum Topology"]),
        ReferenceDocument("N_LAYERS", ["26-dimensional fundamental framework"]),
        ReferenceDocument("PI", ["Mathematical constant: 3.14159..."]),
        ReferenceDocument("F_TRZ_INV", ["Reciprocal of F_TRZ for phase calculations"]),
        ReferenceDocument("ALPHA_UQFF", ["PAPER_591: Parameter-free fine-structure constant from 26-layer projection"]),
        ReferenceDocument("radiative_correction", ["Session 241: Radiative correction factor for physical constants"]),
        ReferenceDocument("C_LIGHT", ["CODATA 2022: Speed of light (exact by definition)"]),
        ReferenceDocument("H_PLANCK", ["CODATA 2022: Planck constant (exact)"]),
        ReferenceDocument("HBAR", ["CODATA 2022: Reduced Planck constant"]),
        ReferenceDocument("K_BOLTZMANN", ["CODATA 2022: Boltzmann constant (exact)"]),
        ReferenceDocument("G_NEWTON", ["CODATA 2022: Gravitational constant"]),
        ReferenceDocument("ELEMENTARY_CHARGE", ["CODATA 2022: Elementary charge (exact)"]),
        ReferenceDocument("FINE_STRUCTURE", ["Fine-structure constant: α = 1/137.035999177"]),
        ReferenceDocument("AVOGADRO", ["CODATA 2022: Avogadro constant (exact)"]),
        ReferenceDocument("MOLAR_GAS_CONSTANT", ["CODATA 2022: Universal gas constant (exact)"]),
        ReferenceDocument("RHO_VAC_SCM", ["Session 237-285: DPM Quantum Chain SCm vacuum density, structural G9"]),
        ReferenceDocument("RHO_VAC_UA", ["Session 237-285: DPM Quantum Chain UA vacuum density (|SO(5)| factor)"]),
        ReferenceDocument("BETA_I", ["Session 237-241: Buoyancy amplification factor calibration"]),
        ReferenceDocument("LAMBDA_I", ["Structural: Manifold coupling constant"]),
        ReferenceDocument("RHO_AETHER", ["Universal aether density (rho_A) from dpm_vacuum_manifold v3.0"]),
        ReferenceDocument("V_AETHER", ["Superconductive aether speed: c/3 = 1.0e8 m/s"]),
        ReferenceDocument("E_CRACK", ["dpm_vacuum_manifold v3.0: Aether shear energy density"]),
        ReferenceDocument("THZ_PHONON", ["Holmlid LENR physics: 1.25 THz phonon frequency (Compton edge)"]),
        ReferenceDocument("E_PHONON", ["Holmlid bridge: Energy of 1.25 THz phonon = h × 1.25 THz"]),
        ReferenceDocument("OMEGA_STELLAR", ["Stellar angular frequency parameter: 2.5e-6 rad/s"]),
        ReferenceDocument("PHI_RESONANCE", ["PAPER_591: On-resonance Gaussian resonance phase factor"]),
        ReferenceDocument("S26_3", ["26-dimensional Ramanujan amplification factor (VDS_26)"]),
        ReferenceDocument("KER_SCM", ["Coherent energy resonance: 630 eV from SCm sector"]),
        ReferenceDocument("KAPPA", ["Session 237: Decay/coupling strength = 0.0005 per day"]),
        ReferenceDocument("E_REACT_0", ["Astrophysical reactor efficiency scale: 1.0e46 W/m³"]),
        ReferenceDocument("M_ELECTRON", ["CODATA 2022: Electron mass"]),
        ReferenceDocument("M_PROTON", ["CODATA 2022: Proton mass"]),
        ReferenceDocument("M_NEUTRON", ["CODATA 2022: Neutron mass"]),
        ReferenceDocument("M_MUON", ["CODATA 2022: Muon mass"]),
        ReferenceDocument("M_TAU", ["Standard Model: Tau lepton mass (approx)"]),
        ReferenceDocument("M_SUN", ["Astronomical: Solar mass"]),
        ReferenceDocument("R_SUN", ["Astronomical: Solar radius"]),
        ReferenceDocument("M_EARTH", ["Astronomical: Earth mass"]),
        ReferenceDocument("R_EARTH", ["Astronomical: Earth radius"]),
        ReferenceDocument("AU", ["Astronomical: Astronomical unit (Earth-Sun distance)"]),
        ReferenceDocument("HUBBLE_H0", ["Cosmology: Hubble parameter H₀ = 67.4 km/s/Mpc (Planck 2018)"]),
        ReferenceDocument("LAMBDA", ["Cosmology: Cosmological constant"]),
        ReferenceDocument("STEFAN_BOLTZMANN", ["Radiation physics: Stefan-Boltzmann constant (exact)"]),
        ReferenceDocument("HEAVISIDE_AMPLIFIER", ["Session 785+: Gap in Um implementations (needs phase-transition amplifier)"]),
        ReferenceDocument("F_U_Ug1_component", ["Session 210+: Magnetic dipole component physics"]),
        ReferenceDocument("F_U_Ug2_component", ["Session 210+: Charge-reactivity coupling physics"]),
        ReferenceDocument("F_U_Ug3_component", ["Session 210+: Magnetic string rotation (90°)"]),
        ReferenceDocument("F_U_Ug4_component", ["Session 210+: Vacuum concentration physics"]),
        ReferenceDocument("F_U_Ubi_component", ["Session 210+: Buoyancy force derivation"]),
        ReferenceDocument("F_U_Um_component", ["Session 210+: Universal magnetism physics"]),
        ReferenceDocument("F_DPM_base", ["DPM di-pseudo-monopole base force derivation"]),
        ReferenceDocument("DPM_frequency_omega1", ["First pseudomonopole oscillation frequency"]),
        ReferenceDocument("DPM_frequency_omega2", ["Second pseudomonopole oscillation frequency"]),
        ReferenceDocument("DPM_current_I", ["DPM current generation in di-pseudo-monopole pairs"]),
        ReferenceDocument("DPM_area_A", ["DPM circuit area in quantum field structure"]),
        ReferenceDocument("E_VAC_SCM", ["SCm aether energy density scaling"]),
        ReferenceDocument("E_VAC_UA", ["UA aether energy density scaling"]),
        ReferenceDocument("V_AETHER_SPRING", ["Aether elasticity / spring constant"]),
        ReferenceDocument("OMEGA_M", ["Planck 2018: Cosmic microwave background + structure"]),
        ReferenceDocument("OMEGA_LAMBDA", ["Planck 2018: Type Ia supernovae + acoustic scale"]),
        ReferenceDocument("OMEGA_B", ["Planck 2018: Big Bang nucleosynthesis + CMB"]),
        ReferenceDocument("OMEGA_K", ["WMAP + Planck: Flatness of universe"]),
        ReferenceDocument("TCMB", ["Cowie 1995 + CODATA 2022: CMB temperature measurement"]),
        ReferenceDocument("SIGMA8", ["Planck 2018: Galaxy cluster abundance"]),
        ReferenceDocument("N_S", ["Planck 2018: Temperature/polarization power spectrum"]),
        ReferenceDocument("ALPHA_EM", ["Session 475, 552: Fine structure constant from CODATA 2022"]),
        ReferenceDocument("ALPHA_S", ["PDG 2022: Strong coupling constant (MS-bar scheme)"]),
        ReferenceDocument("SIN2_THETA_W", ["Particle Data Group: Weak mixing angle"]),
        ReferenceDocument("M_W", ["PDG 2022: W boson mass from precision electroweak"]),
        ReferenceDocument("M_Z", ["PDG 2022: Z boson mass from LEP + Tevatron"]),
        ReferenceDocument("M_HIGGS", ["ATLAS + CMS (2012): Higgs discovery at 125.1 GeV"]),
        ReferenceDocument("M_TOP", ["CDF + D0 + LHC: Top quark mass measurement"]),
        ReferenceDocument("M_BOTTOM", ["PDG 2022: Bottom quark mass (running mass, 2 GeV)"]),
        ReferenceDocument("M_CHARM", ["PDG 2022: Charm quark mass"]),
        ReferenceDocument("M_STRANGE", ["PDG 2022: Strange quark mass"]),
        ReferenceDocument("M_UP", ["PDG 2022: Up quark mass"]),
        ReferenceDocument("M_DOWN", ["PDG 2022: Down quark mass"]),
        ReferenceDocument("M_DEUTERON", ["CODATA 2022: Deuteron mass from atomic precision spectroscopy"]),
        ReferenceDocument("BOHR_RADIUS", ["Session 346, 618: Bohr model / hydrogen spectrum"]),
        ReferenceDocument("RYDBERG_ENERGY", ["Session 345, 619: Hydrogen Balmer series"]),
        ReferenceDocument("COMPTON_WAVELENGTH", ["Compton scattering 1923: Electron-photon collisions"]),
        ReferenceDocument("G_EARTH", ["Session 563, 675: Standard gravity (ISO 80000-3)"]),
        ReferenceDocument("M_MOON", ["Session 681: Lunar missions (Apollo, GRAIL)"]),
        ReferenceDocument("PARSEC", ["Session 575: Hipparcos parallax distance unit"]),
        ReferenceDocument("LIGHT_YEAR", ["Astronomical distance: 1 year × speed of light"]),
        ReferenceDocument("HUBBLE_TIME", ["Age of universe ≈ 13.8 Gyr from H₀"]),
        ReferenceDocument("E", ["Session 533, 631: Euler constant (natural logarithm base)"]),
        ReferenceDocument("LN_2", ["Session 443, 537, 640: Binary logarithm constant"]),
        ReferenceDocument("LN_10", ["Session 449, 538, 641: Decimal logarithm constant"]),
        ReferenceDocument("LOG2_E", ["Session 444: Information theory constant"]),
        ReferenceDocument("CATALAN", ["Session 353, 448, 539: Catalan's constant (infinite series)"]),
        ReferenceDocument("APERY", ["Session 354, 540: Apéry constant ζ(3) (irrational)"]),
        ReferenceDocument("EULER_MASCHERONI", ["Session 357, 447: Euler-Mascheroni constant γ"]),
        ReferenceDocument("GOLDEN_RATIO", ["Session 523, 635: Fibonacci spiral limit"]),
        ReferenceDocument("SQRT_2", ["Session 637: Pythagorean constant (√2)"]),
        ReferenceDocument("SQRT_3", ["Session 638: Cubic diagonal (√3)"]),
        ReferenceDocument("SQRT_5", ["Session 639: Golden ratio root (√5)"]),
        ReferenceDocument("PARKHOMOV_N_CLUSTERS", ["Session 481-587: Nickel-hydrogen LENR cluster density (Parkhomov 2014-2015)"]),
        ReferenceDocument("PARKHOMOV_EXCESS_HEAT_W", ["Session 481-587: Parkhomov E-Cat replication excess power"]),
        ReferenceDocument("PF_LOADING_THRESHOLD", ["McKubre 1992-1998: PdD loading ratio for LENR activation"]),
        ReferenceDocument("PF_ACTIVE_FRACTION", ["Pons-Fleischmann 1989: Fraction of Pd sites active in fusion"]),
        ReferenceDocument("PF_PD_DENSITY", ["Materials science: Palladium crystal density"]),
        ReferenceDocument("PF_EXCESS_HEAT_W", ["Pons-Fleischmann 1989: Electrochemical cell excess power"]),
        ReferenceDocument("MIZUNO_COOLING_TIME", ["Mizuno 2000s: Palladium cathode thermal equilibration"]),
        ReferenceDocument("ROSSI_COP_RATIO", ["Rossi 2011-2012: E-Cat COP (energy out / energy in)"]),
        ReferenceDocument("HOLMLID_KER_EV", ["Session 481-587: Holmlid K-cavity coherent energy resonance (LENR signature)"]),
        ReferenceDocument("HOLMLID_KER_J", ["Session 481-587: 630 eV resonance in joules"]),
        ReferenceDocument("QCD_DECONFINEMENT_TEMP", ["Lattice QCD: Quark-gluon plasma transition temperature"]),
        ReferenceDocument("QCD_DECONFINEMENT_ENERGY", ["Lattice QCD: Thermodynamic transition energy density"]),
        ReferenceDocument("MIT_BAG_CONSTANT", ["MIT bag model: Quark confinement energy scale"]),
        ReferenceDocument("SQM_DENSITY", ["Witten 1984: Strange quark matter bulk density (neutron star core)"]),
        ReferenceDocument("SQM_ESCAPE_VELOCITY", ["Strange matter physics: SQM surface escape velocity"]),
        ReferenceDocument("QGP_VISCOSITY_OVER_ENTROPY", ["Gauge/gravity duality: QGP transport properties (RHIC, LHC)"]),
        ReferenceDocument("S26_3_CALIBRATION_FACTOR", ["Vacuum Density Series: 26D Ramanujan amplification calibration"]),
        ReferenceDocument("VDS_CONVERGENCE_TERMS", ["Session 237-241: Number of terms for VDS accuracy"]),
        ReferenceDocument("PHONON_COUPLING_COEFFICIENT", ["Holmlid LENR: Phonon-to-vacuum coupling strength"]),
        ReferenceDocument("GRAVITATIONAL_WAVE_STRAIN_LIGO", ["LIGO 2016: GW150914 strain sensitivity (Advanced LIGO)"]),
        ReferenceDocument("GW_FREQUENCY_LIGO_BAND", ["LIGO design: Primary observing frequency band"]),
        ReferenceDocument("DARK_MATTER_HALO_DENSITY", ["Galactic rotation curves + lensing: Local dark matter density"]),
        ReferenceDocument("DARK_MATTER_VELOCITY_DISPERSION", ["Milky Way dynamics: Halo velocity dispersion (~230 km/s)"]),
        ReferenceDocument("BANDGAP_SI", ["Session 463: Silicon semiconductor band gap (300 K)"]),
        ReferenceDocument("BANDGAP_GAAS", ["Session 464: Gallium arsenide optoelectronics band gap"]),
        ReferenceDocument("BANDGAP_DIAMOND", ["Session 465: Diamond insulator / wide-bandgap semiconductor"]),
        ReferenceDocument("SUPERCONDUCTOR_CRITICAL_TEMP_YBCO", ["Yttrium barium copper oxide high-Tc superconductor (1987)"]),
        ReferenceDocument("SUPERCONDUCTOR_LONDON_DEPTH", ["Superconductivity: London penetration depth (typ. 160 nm)"]),
        ReferenceDocument("ALPHA_DECAY_RATE", ["Star-Magic.txt Line 42-50: Ug1 temporal decay equation (α = 0.001 day⁻¹, 700-day half-life)"]),
        ReferenceDocument("KAPPA_VACUUM_RATE", ["Star-Magic.txt Line 305-310: E_react exponential decay (κ = 5e-4 day⁻¹, 2000-day half-life)"]),
        ReferenceDocument("GAMMA_MAGNETISM_RATE", ["Star-Magic.txt Line 521-530: Um universal magnetism timescale (γ = 5e-5 day⁻¹, 38-year half-life)"]),
        ReferenceDocument("EPSILON_SOLAR_WIND_COUPLING", ["Star-Magic.txt Line 501-505: Solar wind enhancement factor in Ug2 bubble dynamics"]),
        ReferenceDocument("OMEGA_BAKTUN_CYCLE", ["QCalcGeom.py Epoch-5 solver: Mayan Baktun epochal oscillation (5125.36-year period)"]),
        ReferenceDocument("MAYAN_EPOCH5_START", ["QCalcGeom.py v2.1.0 (Rank 61-70): Epoch 5 (2012 CE) timing correction + ring geometry"]),
    ]
    
    @classmethod
    def all(cls) -> List[ReferenceDocument]:
        return cls.PAPERS
    
    @classmethod
    def get(cls, name: str):
        for p in cls.PAPERS:
            if p.name == name:
                return p
        return None
