"""uqff_registry_graph — R4 falsifiability graph builder (UNIFIED REGISTRY PROGRAM).

Emits (idempotent, read-only inputs):
  UNIFIED_REGISTRY_GRAPH.csv          edge list: primitive->constant, primitive->row, constant->paper
  UNIFIED_REGISTRY_FALSIFIABILITY.md  per-primitive break report

Edge sources:
  (1) explicit dependency map of uqff_registry_primitives formulas (primitive -> derived constant)
  (2) token scan of UNIFIED_REGISTRY.csv row names/sources (primitive -> registry row)
  (3) canonical-route papers x corpus citation counts (constant -> paper -> citing files)
"""
import csv
import os
import re
import sys

os.chdir(os.path.dirname(os.path.abspath(__file__)))

# (1) primitive -> derived constant (from uqff_registry_primitives formula structure)
DERIVED_DEPS = {
    "D_BSFG": ["D_crit", "SO_5"],
    "F_TRZ": ["SO_5"],
    "K_MEX": ["Phi_res", "SO_5", "D_phys"],
    "KAPPA": ["SO_5", "F_TRZ"],
    "RHO_UA": ["SO_5", "rho_SCm"],
    "LAMBDA_VAC": ["SO_5", "rho_SCm"],
    "K_SPRING": ["SO_5", "omega_SCm", "Phi_res"],
    "G_UQFF": ["D_crit", "Phi_res", "SSq"],
    "C_UQFF_DERIVED": ["D_crit", "Phi_res"],
    "MU_0": ["F_TRZ"],
    "K_B_UQFF": ["SSq", "Phi_res", "F_TRZ", "D_phys"],
    "HBAR_UQFF_S629": ["D_BSFG", "F_TRZ", "D_phys", "SSq"],
    "H0_GRID": ["F_TRZ"],
    "LAMBDA_SIMPLE": ["SO_5", "F_TRZ"],
    "B_CRIT": ["D_phys", "SO_5"],
    "T_SCM_K": ["omega_SCm"],
}

PRIMITIVE_TOKENS = {
    "D_phys": ("d_phys",), "D_crit": ("d_crit", "26d", "_26_"),
    "N_CH": ("n_ch",), "SO_5": ("so_5", "so5"), "A_5": ("a_5", "a5_"),
    "rho_SCm": ("rho_scm", "rho_vac_scm"), "beta_i": ("beta_i", "beta_"),
    "Phi_res": ("phi_res", "phi_5_6"), "F_TRZ": ("f_trz", "trz"),
    "SSq": ("ssq",), "S_26": ("s_26", "s26"), "omega_SCm": ("omega_scm",),
    "kappa": ("kappa",), "K_MEX": ("k_mex", "kmex"), "D_BSFG": ("d_bsfg", "bsfg"),
}

ROUTE_PAPERS = {
    "G_UQFF": "PAPER_593", "C_UQFF_DERIVED": "PAPER_592", "MU_0": "PAPER_2108",
    "K_B_UQFF": "PAPER_1209EE", "HBAR_UQFF_S629": "PAPER_590",
    "H0_GRID": "PAPER_2093", "LAMBDA_SIMPLE": "PAPER_1156", "KAPPA": "PAPER_2112",
    "LAMBDA_VAC": "PAPER_2120", "B_CRIT": "PAPER_2126", "K_SPRING": "PAPER_1203",
    "T_SCM_K": "PAPER_1072", "K_MEX": "PAPER_1522", "D_BSFG": "PAPER_1521",
}

KNOWN_INVARIANTS = {
    "F_TRZ": 61,   # (1+F_TRZ) successor-ratio canonical sites (PAPER_2128)
    "SO_5": 61,    # same sites via (SO_5+1)/SO_5 reading
}


def main():
    edges = []
    for const, prims in sorted(DERIVED_DEPS.items()):
        for p in prims:
            edges.append(("primitive", p, "constant", const, "module_formula"))

    row_hits = {p: 0 for p in PRIMITIVE_TOKENS}
    with open("UNIFIED_REGISTRY.csv", encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            hay = (r["quantity"] + "_" + r["paper_source"]).lower()
            for prim, toks in PRIMITIVE_TOKENS.items():
                if any(t in hay for t in toks):
                    row_hits[prim] += 1
                    edges.append(("primitive", prim, "registry_row", r["quantity"], r["origin"]))

    cites = {}
    with open("UNIFIED_REGISTRY_CORPUS_CITATIONS.csv", encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            cites[r["paper"]] = int(r["cited_by_files"])
    paper_edges = []
    for const, paper in sorted(ROUTE_PAPERS.items()):
        n = cites.get(paper.split("EE")[0] if "1209" in paper else paper, 0)
        paper_edges.append((const, paper, n))
        edges.append(("constant", const, "route_paper", paper, f"cited_by={n}"))

    edges.sort()
    with open("UNIFIED_REGISTRY_GRAPH.csv", "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["src_kind", "src", "dst_kind", "dst", "edge_info"])
        w.writerows(edges)

    lines = [
        "# UNIFIED_REGISTRY_FALSIFIABILITY.md — R4 per-primitive break report",
        "",
        "**Generated by:** `uqff_registry_graph.py` (idempotent). "
        "**Question answered:** *if primitive X were revised, what breaks?*",
        "",
        "| Primitive | Derived constants dependent | Registry rows touched | Known canonical invariants | Gate exposure |",
        "|---|:-:|:-:|:-:|---|",
    ]
    for prim in sorted(PRIMITIVE_TOKENS):
        dconsts = [c for c, ps in DERIVED_DEPS.items() if prim in ps]
        inv = KNOWN_INVARIANTS.get(prim, 0)
        gate = "U_i=2.75e-7 pin + 61-site (1+F_TRZ) family" if prim in ("F_TRZ", "SO_5") else \
               "magic-number EXACT pins" if prim in ("D_phys", "D_crit", "A_5", "N_CH") else \
               "canonical-value pins"
        lines.append(f"| {prim} | {len(dconsts)} ({', '.join(dconsts) if dconsts else '-'}) "
                     f"| {row_hits.get(prim, 0)} | {inv} | {gate} |")
    lines += [
        "",
        "## Route-paper citation leverage (constant -> canonical paper -> citing whitepapers)",
        "",
        "| Constant | Canonical route | Citing files |",
        "|---|---|:-:|",
    ]
    for const, paper, n in sorted(paper_edges, key=lambda x: -x[2]):
        lines.append(f"| {const} | {paper} | {n} |")
    lines += [
        "",
        "## Headline",
        "",
        f"Total graph edges: {len(edges)}. Every primitive participates in multiply-pinned",
        "identities; a single-primitive revision propagates through the derived constants,",
        "the registry rows above, the (1+F_TRZ) 61-site invariant family, and the",
        "3,186-assertion fidelity gate simultaneously. Over-determination is the",
        "falsifiability mechanism: wrong values cannot hide (see PAPER_2119/2126/2128).",
        "",
    ]
    with open("UNIFIED_REGISTRY_FALSIFIABILITY.md", "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(lines))

    print(f"edges={len(edges)} | row-hit totals: " +
          ", ".join(f"{p}={n}" for p, n in sorted(row_hits.items(), key=lambda kv: -kv[1])[:6]))
    import hashlib
    print("graph_sha256=" + hashlib.sha256(open("UNIFIED_REGISTRY_GRAPH.csv", "rb").read()).hexdigest()[:16])


if __name__ == "__main__":
    main()
