/**
 * Monte Carlo REST route for uqff_server.js
 * Drop-in: add to uqff_server.js routes section
 *
 * Usage:
 *   POST /api/cosmogenesis/montecarlo
 *   Body (optional): {"n_samples": 100000, "seed": 42}
 *
 * Generated by montecarlo_rest_exporter.py
 */

const { execFile } = require('child_process');
const path = require('path');

const MC_SCRIPT = path.join(__dirname, 'cosmogenesis_montecarlo_v2.py');
const MC_RESULTS = path.join(__dirname, 'cosmogenesis_mc_v2_results.json');
const PYTHON = process.env.PYTHON_PATH || 'python';

/**
 * Handle POST /api/cosmogenesis/montecarlo
 * Runs the Python MC engine and returns JSON results.
 */
function handleMonteCarloRequest(req, res, body) {
    // Run MC script
    execFile(PYTHON, [MC_SCRIPT], {
        cwd: __dirname,
        timeout: 120000,  // 2 min max
        maxBuffer: 10 * 1024 * 1024,  // 10 MB
    }, (error, stdout, stderr) => {
        if (error) {
            res.writeHead(500, {'Content-Type': 'application/json'});
            res.end(JSON.stringify({
                error: 'MC execution failed',
                detail: error.message,
            }));
            return;
        }

        // Read the results JSON
        const fs = require('fs');
        try {
            const results = JSON.parse(fs.readFileSync(MC_RESULTS, 'utf8'));
            results.endpoint = '/api/cosmogenesis/montecarlo';
            results.api_version = '1.0.0';
            res.writeHead(200, {'Content-Type': 'application/json'});
            res.end(JSON.stringify(results, null, 2));
        } catch (readErr) {
            res.writeHead(500, {'Content-Type': 'application/json'});
            res.end(JSON.stringify({
                error: 'Failed to read MC results',
                detail: readErr.message,
            }));
        }
    });
}

/**
 * Handle GET /api/cosmogenesis/health
 */
function handleCosmogenesisHealth(req, res) {
    const fs = require('fs');
    const hasScript = fs.existsSync(MC_SCRIPT);
    res.writeHead(200, {'Content-Type': 'application/json'});
    res.end(JSON.stringify({
        status: 'ok',
        service: 'uqff_server_mc_route',
        mc_script_available: hasScript,
        results_file: MC_RESULTS,
    }));
}

module.exports = { handleMonteCarloRequest, handleCosmogenesisHealth };
