#!/usr/bin/env python3
"""
Phase 4: Generate C++ PhysicsTerm classes from validated Wolfram entities
Input: wolfram_extraction/validated_entities.json
Output: sourceXXX_wolfram.cpp files + master registration header
"""

import json
import os
import re
from pathlib import Path
from datetime import datetime

def safe_cpp_identifier(name):
    """Convert name to safe C++ identifier"""
    safe = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    safe = re.sub(r'^(\d)', r'_\1', safe)  # Prefix digit with underscore
    safe = re.sub(r'__+', '_', safe)  # Collapse multiple underscores
    return safe.strip('_')

def get_category_enum(entity_type):
    """Map entity type to PhysicsTermCategory enum"""
    mapping = {
        'constant': 'PhysicsTermCategory::FUNDAMENTAL_CONSTANTS',
        'particle': 'PhysicsTermCategory::PARTICLE_PHYSICS',
        'system': 'PhysicsTermCategory::ASTROPHYSICAL_SYSTEMS',
        'quantity': 'PhysicsTermCategory::QUANTUM_MECHANICS'
    }
    return mapping.get(entity_type.lower(), 'PhysicsTermCategory::OTHER')

def generate_constant_class(name, entity, class_name):
    """Generate C++ class for a physical constant"""
    # class_name now passed as parameter to handle duplicates
    # Handle both lowercase and capitalized keys
    value = entity.get('value', entity.get('Value', '0.0'))
    unit = entity.get('unit', entity.get('Unit', 'dimensionless'))
    description = entity.get('description', entity.get('Description', name)).replace('\\', '\\\\').replace('"', '\\"')
    
    return f"""
// Wolfram Knowledgebase: {name}
class {class_name} : public PhysicsTerm {{
public:
    {class_name}() {{}}
    
    double compute(double t, const std::map<std::string, double>& params) const override {{
        // Canonical value from Wolfram Knowledgebase
        return {value};
    }}
    
    std::string getName() const override {{
        return "{name}";
    }}
    
    std::string getDescription() const override {{
        return "{description} [{unit}]";
    }}
    
    bool validate(const std::map<std::string, double>& params) const override {{
        // Wolfram-validated constant
        return true;
    }}
}};
"""

def generate_system_class(name, entity, class_name):
    """Generate C++ class for an astrophysical system"""
    # class_name now passed as parameter to handle duplicates
    # Handle both lowercase and capitalized keys
    description = entity.get('description', entity.get('Description', name)).replace('\\', '\\\\').replace('"', '\\"')
    mass = entity.get('mass', entity.get('Mass', '1.0e30'))
    radius = entity.get('radius', entity.get('Radius', '1.0e6'))
    
    return f"""
// Wolfram Knowledgebase: {name}
class {class_name} : public PhysicsTerm {{
public:
    {class_name}() {{}}
    
    double compute(double t, const std::map<std::string, double>& params) const override {{
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : {mass};
        const double R = params.count("R_ns") ? params.at("R_ns") : {radius};
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }}
    
    std::string getName() const override {{
        return "{name}";
    }}
    
    std::string getDescription() const override {{
        return "{description}";
    }}
    
    bool validate(const std::map<std::string, double>& params) const override {{
        return true;
    }}
}};
"""

def generate_cpp_file(source_file, constants, systems, output_dir, global_class_name_counts):
    """Generate complete C++ file for a source group"""
    file_name = f"{source_file}_wolfram.cpp" if source_file != "general" else "wolfram_general.cpp"
    file_path = output_dir / file_name
    
    class_names = []
    
    # Build file content
    content = [
        f"// ===================================================================",
        f"// Auto-generated Wolfram Physics Terms from {source_file}",
        f"// Generated by: wolfram_extraction_phase4.py",
        f"// Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"// ===================================================================",
        f"// Source: {source_file}",
        f"// Constants: {len(constants)}",
        f"// Systems: {len(systems)}",
        f"// Total Terms: {len(constants) + len(systems)}",
        f"// ===================================================================",
        f"",
        f"#include <memory>",
        f"#include <string>",
        f"#include <iostream>",
        f"",
        f"// Forward declarations (assume these exist in main codebase)",
        f"class PhysicsTerm;",
        f"class PhysicsTermRegistry;",
        f"struct SystemParams;",
        f"enum class PhysicsTermCategory;",
        f"",
        f"// ===================================================================",
        f"// Constant Definitions",
        f"// ===================================================================",
        f""
    ]
    
    # Generate constant classes - track names and avoid duplicates globally
    const_names = []
    
    for const in constants:
        # Handle both lowercase and capitalized keys for name
        name = const.get('name', const.get('Name', 'UnknownConstant'))
        base_class_name = f"Wolfram_{safe_cpp_identifier(name)}"
        
        # Handle duplicates by appending counter (global tracking)
        if base_class_name in global_class_name_counts:
            global_class_name_counts[base_class_name] += 1
            class_name = f"{base_class_name}_{global_class_name_counts[base_class_name]}"
        else:
            global_class_name_counts[base_class_name] = 0
            class_name = base_class_name
        
        class_names.append(class_name)
        const_names.append(name)  # Track original name
        content.append(generate_constant_class(name, const, class_name))
    
    content.extend([
        "",
        "// ===================================================================",
        "// Astrophysical System Definitions",
        "// ===================================================================",
        ""
    ])
    
    # Generate system classes - track names and avoid duplicates globally
    system_names = []
    for system in systems:
        # Handle both lowercase and capitalized keys for name
        name = system.get('name', system.get('Name', 'UnknownSystem'))
        base_class_name = f"Wolfram_{safe_cpp_identifier(name)}"
        
        # Handle duplicates by appending counter (global tracking)
        if base_class_name in global_class_name_counts:
            global_class_name_counts[base_class_name] += 1
            class_name = f"{base_class_name}_{global_class_name_counts[base_class_name]}"
        else:
            global_class_name_counts[base_class_name] = 0
            class_name = base_class_name
        
        class_names.append(class_name)
        system_names.append(name)  # Track original name
        content.append(generate_system_class(name, system, class_name))
    
    # Generate registration function
    func_name = f"registerWolframTerms_{safe_cpp_identifier(source_file)}"
    content.extend([
        "",
        f"// ===================================================================",
        f"// Registration function for {source_file} Wolfram terms",
        f"// ===================================================================",
        f"void {func_name}(PhysicsTermRegistry& registry) {{",
    ])
    
    # Register with original names
    all_names = const_names + system_names
    for idx, class_name in enumerate(class_names):
        original_name = all_names[idx]
        content.append(f"    registry.registerTerm(\"{original_name}\", std::make_unique<{class_name}>(), \"wolfram\");")
    
    content.extend([
        f"    ",
        f"    std::cout << \"Registered {len(class_names)} Wolfram terms from {source_file}\" << std::endl;",
        f"}}",
        f""
    ])
    
    # Write to file
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(content))
    
    return {
        'file': file_name,
        'function': func_name,
        'constants': len(constants),
        'systems': len(systems),
        'total': len(class_names)
    }

def generate_master_header(file_stats, output_dir):
    """Generate master registration header"""
    header_path = output_dir / "wolfram_master_registration.h"
    
    content = [
        "// ===================================================================",
        "// Master Registration Header for All Wolfram Physics Terms",
        "// Auto-generated by: wolfram_extraction_phase4.py",
        f"// Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "// ===================================================================",
        "",
        "#ifndef WOLFRAM_MASTER_REGISTRATION_H",
        "#define WOLFRAM_MASTER_REGISTRATION_H",
        "",
        "#include <iostream>",
        "",
        "// Forward declaration",
        "class PhysicsTermRegistry;",
        "",
        "// Registration function declarations"
    ]
    
    for source_file in sorted(file_stats.keys()):
        func_name = file_stats[source_file]['function']
        content.append(f"extern void {func_name}(PhysicsTermRegistry& registry);")
    
    content.extend([
        "",
        "// ===================================================================",
        "// Master registration function",
        "// Call this to register ALL Wolfram terms",
        "// ===================================================================",
        "inline void registerAllExtractedWolframTerms(PhysicsTermRegistry& registry) {",
        '    std::cout << "Registering Wolfram Physics Terms..." << std::endl;',
        ""
    ])
    
    for source_file in sorted(file_stats.keys()):
        func_name = file_stats[source_file]['function']
        content.append(f"    {func_name}(registry);")
    
    content.extend([
        "",
        '    std::cout << "All Wolfram terms registered successfully." << std::endl;',
        "}",
        "",
        "#endif // WOLFRAM_MASTER_REGISTRATION_H"
    ])
    
    with open(header_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(content))
    
    return header_path

def main():
    # Paths
    input_json = Path("wolfram_extraction/validated_entities.json")
    output_dir = Path("wolfram_extraction/generated_classes")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("=" * 70)
    print("Phase 4: C++ Class Generation")
    print("=" * 70)
    print()
    
    # Load validated entities
    if not input_json.exists():
        print(f"ERROR: {input_json} not found!")
        print("Run Phase 3 (wolfram_extraction_phase3.ps1) first.")
        return 1
    
    with open(input_json, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Handle both lowercase and capitalized keys
    constants = data.get('validatedConstants', data.get('ValidatedConstants', []))
    systems = data.get('validatedSystems', data.get('ValidatedSystems', []))
    
    print(f"Validated constants: {len(constants)}")
    print(f"Validated systems: {len(systems)}")
    print()
    
    # Group entities by source file
    entity_groups = {}
    
    for const in constants:
        # Handle both lowercase and capitalized keys
        source = const.get('sourceFile', const.get('SourceFile', 'general'))
        if source not in entity_groups:
            entity_groups[source] = {'constants': [], 'systems': []}
        entity_groups[source]['constants'].append(const)
    
    for system in systems:
        # Handle both lowercase and capitalized keys
        source = system.get('sourceFile', system.get('SourceFile', 'general'))
        if source not in entity_groups:
            entity_groups[source] = {'constants': [], 'systems': []}
        entity_groups[source]['systems'].append(system)
    
    print(f"Entity groups found: {len(entity_groups)}")
    print()
    
    # Generate C++ files
    file_stats = {}
    total_classes = 0
    global_class_name_counts = {}  # Track class names across ALL files
    
    for source_file in sorted(entity_groups.keys()):
        group = entity_groups[source_file]
        consts = group['constants']
        syss = group['systems']
        
        if len(consts) == 0 and len(syss) == 0:
            continue
        
        print(f"Processing {source_file} ({len(consts)} constants, {len(syss)} systems)...")
        
        stats = generate_cpp_file(source_file, consts, syss, output_dir, global_class_name_counts)
        file_stats[source_file] = stats
        total_classes += stats['total']
        
        print(f"  ✓ Generated: {stats['file']}")
    
    print()
    print("=" * 70)
    print("Generation Summary")
    print("=" * 70)
    print(f"Total C++ files generated: {len(file_stats)}")
    print(f"Total PhysicsTerm classes: {total_classes}")
    print()
    
    # Generate master header
    header_path = generate_master_header(file_stats, output_dir)
    print(f"Master registration header: {header_path}")
    print()
    
    # Save summary JSON
    summary_path = output_dir / "generation_summary.json"
    summary = {
        'timestamp': datetime.now().isoformat(),
        'totalFiles': len(file_stats),
        'totalClasses': total_classes,
        'fileDetails': file_stats,
        'sourceGroups': sorted(entity_groups.keys())
    }
    
    with open(summary_path, 'w', encoding='utf-8') as f:
        json.dump(summary, f, indent=2)
    
    print(f"Summary saved to: {summary_path}")
    print()
    
    print("=" * 70)
    print("Next Steps")
    print("=" * 70)
    print(f"1. Review generated files in: {output_dir}")
    print("2. Add files to CMakeLists.txt target_sources")
    print("3. Include wolfram_master_registration.h in MAIN_1_CoAnQi.cpp")
    print("4. Call registerAllExtractedWolframTerms in main function")
    print("5. Rebuild and verify 6597/6597 registration success")
    print()
    
    return 0

if __name__ == "__main__":
    exit(main())
