#!/usr/bin/env python3
"""scan_missing_whitepapers.py — find paper IDs cited but not present as .md.

READ-ONLY scan across:
  - uqff_pure_calculator.py
  - Gold_Standard_Pure_UQFF.md
  - manuscript v2 PDF (text extract via pdftotext if available, else skip)
  - grok master summaries
  - CLOSURE_ATLAS.md, AXIOMS_AND_THEOREMS.md, SESSION_LOG.md
  - all whitepapers (cross-reference among themselves)

Writes a report listing PAPER_XXXX IDs that are referenced but have no .md file.
Daniel must write whitepapers — this script ONLY flags gaps.
"""
import re
from pathlib import Path
from collections import Counter, defaultdict

REPO = Path("/sessions/vibrant-keen-bohr/mnt/Star-Magic")
WP   = REPO / "whitepapers"
SDIST = Path("/sessions/vibrant-keen-bohr/mnt/outputs/uqff_sdist/uqff-5.29.0")
OUT  = Path("/sessions/vibrant-keen-bohr/mnt/outputs/uqff_recompute/MISSING_WHITEPAPERS_REPORT.md")

PAPER_RE = re.compile(r"PAPER[_\-\s]?(\d{3,4})", re.IGNORECASE)

# 1. Build the set of EXISTING paper IDs (have .md file in whitepapers/)
existing = set()
existing_files = {}
for p in WP.glob("PAPER_*.md"):
    m = re.match(r"PAPER_(\d{3,4})", p.stem)
    if m:
        pid = m.group(1).zfill(4)
        existing.add(pid)
        existing_files.setdefault(pid, []).append(p.name)
print(f"Existing whitepapers in repo: {len(existing)} unique IDs across {sum(len(v) for v in existing_files.values())} files")

# 2. Sources to scan for citations
sources = [
    ("uqff_pure_calculator.py",  REPO / "uqff_pure_calculator.py"),
    ("Gold_Standard_Pure_UQFF.md", REPO / "Gold_Standard_Pure_UQFF.md"),
    ("CLOSURE_ATLAS.md",         REPO / "CLOSURE_ATLAS.md"),
    ("AXIOMS_AND_THEOREMS.md",   REPO / "AXIOMS_AND_THEOREMS.md"),
    ("SESSION_LOG.md",           REPO / "SESSION_LOG.md"),
    ("CLAUDE.md",                REPO / "CLAUDE.md"),
    ("NEXT_PRIORITIES.md",       REPO / "NEXT_PRIORITIES.md"),
    ("grok_8461fe4e_c903.md",    REPO / "grok_8461fe4e_c903.md"),
    ("grok_b8e305e6_1f29.md",    REPO / "grok_b8e305e6_1f29.md"),
    ("WHITEPAPER_INDEX.md",      REPO / "WHITEPAPER_INDEX.md"),
    ("COVERAGE_GAPS.md",         REPO / "COVERAGE_GAPS.md"),
    ("PROVENANCE_AUDIT.md",      REPO / "PROVENANCE_AUDIT.md"),
    ("Star-Magic.txt",           REPO / "Star-Magic.txt"),
    ("STAR-MAGIC2.txt",          REPO / "STAR-MAGIC2.txt"),
]

cited = Counter()       # paper_id -> count of citations
cite_origins = defaultdict(list)  # paper_id -> list of source files

for label, fp in sources:
    if not fp.exists():
        print(f"  skip (not found): {label}")
        continue
    try:
        txt = fp.read_text(encoding="utf-8", errors="replace")
    except Exception as e:
        print(f"  skip (read err): {label}: {e}")
        continue
    cites = set()  # unique IDs in this file
    for m in PAPER_RE.finditer(txt):
        pid = m.group(1).zfill(4)
        cites.add(pid)
        cited[pid] += 1
    for pid in cites:
        cite_origins[pid].append(label)
    print(f"  {label}: {len(cites)} unique paper IDs cited")

# 3. Also scan all whitepapers for cross-references
print("\nScanning all whitepapers/ for cross-references...")
wp_files = list(WP.glob("PAPER_*.md"))
for wp_file in wp_files:
    try:
        txt = wp_file.read_text(encoding="utf-8", errors="replace")
    except Exception:
        continue
    # find paper IDs cited in this file (excluding the file's own ID)
    own_m = re.match(r"PAPER_(\d{3,4})", wp_file.stem)
    own_id = own_m.group(1).zfill(4) if own_m else None
    cites_local = set()
    for m in PAPER_RE.finditer(txt):
        pid = m.group(1).zfill(4)
        if pid != own_id:
            cites_local.add(pid)
            cited[pid] += 1
    for pid in cites_local:
        cite_origins[pid].append(f"WP:{wp_file.name}")

# 4. Compute missing (cited but not existing)
all_cited = set(cited.keys())
missing = all_cited - existing
present = all_cited & existing
print(f"\n=== Citation analysis ===")
print(f"Total unique paper IDs cited anywhere: {len(all_cited)}")
print(f"Present as .md file in whitepapers/:    {len(present)}")
print(f"Missing (cited but no .md):              {len(missing)}")
print(f"In repo but never cited (orphan):       {len(existing - all_cited)}")

# 5. Show the missing ones sorted by citation count
missing_sorted = sorted(missing, key=lambda x: -cited[x])
print(f"\n--- TOP 30 most-cited MISSING papers ---")
print(f"{'PAPER':<10} {'cites':>5}  sources (top 3)")
print("-"*90)
for pid in missing_sorted[:30]:
    sources_brief = list(set(cite_origins[pid]))[:3]
    print(f"PAPER_{pid:<5} {cited[pid]:>5}  {', '.join(sources_brief)[:75]}")

# 6. Write report
out_lines = [
    "# Missing whitepapers — cited but no .md file",
    "",
    "**Generated by Claude in MY sandbox / repo helper section.**",
    "**Daniel writes the physics; this script only flags gaps.**",
    "",
    f"## Stats",
    "",
    f"- Whitepapers present: {len(existing)} unique IDs",
    f"- Whitepapers cited anywhere: {len(all_cited)} unique IDs",
    f"- **Missing (cited but no .md):** {len(missing)}",
    f"- Orphan (.md present, never cited): {len(existing - all_cited)}",
    "",
    "## Top 50 missing papers by citation count",
    "",
    "| PAPER | Cites | Top sources |",
    "|---|---:|---|",
]
for pid in missing_sorted[:50]:
    sources_brief = list(set(cite_origins[pid]))[:3]
    out_lines.append(f"| PAPER_{pid} | {cited[pid]} | {', '.join(sources_brief)} |")

out_lines.extend([
    "",
    "## All missing papers (alphabetical)",
    "",
])
for pid in sorted(missing):
    out_lines.append(f"- `PAPER_{pid}` (cited {cited[pid]}× in {len(set(cite_origins[pid]))} sources)")

out_lines.extend([
    "",
    "## Orphan papers (present but never cited)",
    "",
    "These exist as .md files but no source file cites them. They might be foundational",
    "context, historical scaffolding, or have been superseded.",
    "",
])
orphans = sorted(existing - all_cited)
for pid in orphans[:50]:
    out_lines.append(f"- `PAPER_{pid}` — files: {', '.join(existing_files.get(pid, []))}")
if len(orphans) > 50:
    out_lines.append(f"- … and {len(orphans)-50} more")

OUT.write_text("\n".join(out_lines))
print(f"\nWrote: {OUT}")
