---
name: Feature Request
description: Suggest an enhancement to the theoretical framework
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an enhancement to the Star-Magic
        framework.

  - type: textarea
    id: description
    attributes:
      label: Enhancement Description
      description: A clear description of the proposed enhancement
      placeholder: What would you like to see added or improved?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of enhancement is this?
      options:
        - Mathematical Refinement
        - New Application
        - Experimental Validation
        - Documentation Improvement
        - Clarification
        - Other
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this enhancement valuable?
      placeholder: |
        Explain the scientific or practical benefit of this
        enhancement
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: How would you implement this enhancement?
      placeholder: |
        - Equations or formulations
        - References to existing work
        - Implementation details
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?
      placeholder: |
        Describe any alternative solutions you've thought about
    validations:
      required: false
