"""
assimilation_dispatch.py
Part of UQFF Assimilation Geometry — Round 12 EXPANSION_PLAN deliverable.

Status: bundled in `uqff` PyPI package (Star-Magic repo) for academic peer-review
        access — supports the 3-university first peer review + the 8 NASA-Roses
        grant evaluation panels.

Future: relocatable to https://github.com/Daniel8Murphy0007/Aetheric-Propulsion
        for commercial-tier extraction. See ASSIMILATION_GEOMETRY_ATLAS.md for
        the extraction procedure.

Dependencies (internal):  none (read-only lookup data)
Dependencies (external):  none

License:  AGPL-3.0-or-later OR Commercial (dual; identical to parent uqff)

----------------------------------------------------------------------------
ASSIMILATION DISPATCH TABLE
----------------------------------------------------------------------------
Per-observable record:

    observable_name -> {
        "domain":         <SI | SM | LCDM | astro | CM | GR | bio | chem | geo | mat | KK>,
        "target":         <CODATA / PDG / Planck 2018 anchor value>,
        "uqff_formula":   <textual closure formula as documented in the
                           session script or whitepaper>,
        "uqff_value":     <computed numeric value of the formula>,
        "owner_geometry": <qcalcgeom | bsfg | dpm | d26>,
        "primary_source": <PAPER_XXXX>,
        "session_script": <_sessionN_<obs>.py or None>,
        "residual_pct":   <documented residual; 0.0 if EXACT formula>,
        "notes":          <free text>,
    }

----------------------------------------------------------------------------
PHASE E1 — SI FUNDAMENTALS (this file populated by Round 661)
----------------------------------------------------------------------------
Every entry below is sourced from an existing session script or whitepaper
at the Star-Magic root. No closures are invented for this dispatch — each
one cites the source where the formula was derived. Later Phase E
sub-rounds will add E2 SM parameters, E3 LCDM observables, E4 astro
constants, E5 CM/GR/bio/chem/geo/mat, E6 KK scaling.

Total entries this round: see TOTAL_E1 constant at bottom.
"""

import math

# Locked canonical primitives (mirror from uqff_pure_calculator for
# self-contained evaluation; values pinned per CLAUDE.md Rule 2)
D_PHYS    = 4
D_BSFG    = 6
D_CRIT    = 26
N_CH      = 9
SO_5      = 10
A_5       = 60
F_TRZ     = 0.1
PHI_RES_5_6 = 5.0 / 6.0
PHI_RES_84  = 0.84
K_MEX     = 25.0 / 12.0
SSQ       = 0.57
BETA_I    = 0.6029


# ============================================================================
# E1: SI fundamentals + standard model dimensionless constants
# Each closure is sourced from a named session script / whitepaper.
# ============================================================================

DISPATCH = {
    # ------------------------------------------------------------------------
    # Dimensionless: fine structure and related
    # ------------------------------------------------------------------------
    "alpha_inverse": {
        "domain":          "SI",
        "target":          137.035999084,                       # CODATA 2018
        "uqff_formula":    "1/alpha = A_5 * K_MEX + 1/(F_TRZ * Phi_res_5_6) = 125 + 12 = 137",
        "uqff_value":      A_5 * K_MEX + 1.0 / (F_TRZ * PHI_RES_5_6),
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session343_chem_fine_structure.py",
        "residual_pct":    0.026,
        "notes":           "Higher-order BSFG holonomy correction adds 0.036 to leading 137",
    },
    "mp_me_ratio": {
        "domain":          "SI",
        "target":          1836.15267343,                       # CODATA 2018
        "uqff_formula":    "m_p/m_e = D_BSFG * pi^5",
        "uqff_value":      D_BSFG * math.pi ** 5,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session344_chem_mp_me_ratio.py",
        "residual_pct":    0.0019,
        "notes":           "Alternative form: A_5^2/2 + D_BSFG^2 = 1836 EXACT (S266)",
    },
    "weinberg_sin2": {
        "domain":          "SM",
        "target":          0.23122,                              # MS-bar at M_Z, PDG
        "uqff_formula":    "sin^2(theta_W) = K_MEX / N_CH = 25/108",
        "uqff_value":      K_MEX / N_CH,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session347_chem_weinberg.py",
        "residual_pct":    0.113,
        "notes":           "EXACT structural ratio; residual is QED running of theta_W",
    },
    "alpha_s_M_Z": {
        "domain":          "SM",
        "target":          0.1179,                               # PDG 2018
        "uqff_formula":    "alpha_s(M_Z) = 1/(K_MEX*D_phys + F_TRZ) = 1/8.4333",
        "uqff_value":      1.0 / (K_MEX * D_PHYS + F_TRZ),
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session348_chem_alpha_s.py",
        "residual_pct":    0.57,
        "notes":           "Well within PDG 1-sigma (0.1179 +/- 0.0010)",
    },
    # ------------------------------------------------------------------------
    # SI base unit prefactors and constants where UQFF closures exist
    # ------------------------------------------------------------------------
    "stefan_boltzmann_prefactor": {
        "domain":          "SI",
        "target":          60,                                   # integer denominator
        "uqff_formula":    "sigma = pi^2 k_B^4 / (A_5 * hbar^3 * c^2); A_5 = 60",
        "uqff_value":      A_5,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session349_chem_stefan_boltzmann.py",
        "residual_pct":    0.0,
        "notes":           "5-simplex face count -> SO(5) gauge multiplicity of photon-bath partition function; EXACT",
    },
    "periodic_table_periods": {
        "domain":          "chem",
        "target":          7,
        "uqff_formula":    "n_periods_stable = D_BSFG + 1 = 7",
        "uqff_value":      D_BSFG + 1,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session351_chem_periodic_table.py",
        "residual_pct":    0.0,
        "notes":           "Matches Madelung n+l filling, period 8 unstable; EXACT",
    },
    # ------------------------------------------------------------------------
    # SM cosmological / Higgs / ladder closures from PAPER_1181 + the
    # paper_orphan rows in master_closures.csv (PAPER_1619 through PAPER_1746).
    # Each was wired in Round 656 as a master_closures.csv row; here we
    # surface them as solver-callable observables.
    # ------------------------------------------------------------------------
    "higgs_vev": {
        "domain":          "SM",
        "target":          246.0,                                # GeV, PDG
        "uqff_formula":    "v_Higgs = A_5 * (D_phys + F_TRZ) = 60 * 4.1 = 246 GeV",
        "uqff_value":      A_5 * (D_PHYS + F_TRZ),
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1636",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "EXACT structural identity",
    },
    "m_W_alt": {
        "domain":          "SM",
        "target":          80.0,                                 # GeV (lead-digit), PDG ~80.379
        "uqff_formula":    "m_W = A_5 + A_5/3 = 60 + 20 = 80 GeV",
        "uqff_value":      A_5 + A_5 / 3.0,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1686",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "Lead-digit closure",
    },
    "BH_seed_mass": {
        "domain":          "astro",
        "target":          56160.0,                              # M_Sun
        "uqff_formula":    "M_seed = A_5 * D_BSFG^2 * D_crit = 60 * 36 * 26 = 56,160 M_Sun",
        "uqff_value":      A_5 * D_BSFG ** 2 * D_CRIT,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1650",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "Pop III IMF top-of-stack seed; EXACT integer product",
    },
    "Pop_III_IMF_max": {
        "domain":          "astro",
        "target":          120.0,                                # M_Sun top of IMF
        "uqff_formula":    "M_max = A_5 * 2 = 120 M_Sun",
        "uqff_value":      A_5 * 2,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1652",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "Top of Pop III initial mass function; EXACT",
    },
    "quantum_supremacy_qubits": {
        "domain":          "SI",
        "target":          60,                                    # threshold
        "uqff_formula":    "n_qubits >= A_5 = 60 (Sycamore reached 53)",
        "uqff_value":      A_5,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1655",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "Structural threshold; EXACT",
    },
    "Clifford_qualia_states": {
        "domain":          "SM",
        "target":          8192,
        "uqff_formula":    "8192 = 2^13 = SO(26) Clifford bundle qualia states",
        "uqff_value":      2 ** 13,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1666",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "EXACT power of 2",
    },
    "hubble_tension": {
        "domain":          "LCDM",
        "target":          5.6,                                  # km/s/Mpc
        "uqff_formula":    "Delta_H = SH0ES - Planck = 73 - 67.4 = 5.6 km/s/Mpc",
        "uqff_value":      73.0 - 67.4,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1676",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "EXACT arithmetic difference",
    },
    "omega_lambda_6_5_SSQ": {
        "domain":          "LCDM",
        "target":          0.684,
        "uqff_formula":    "Omega_Lambda = (6/5) * SSQ = 6/5 * 0.57 = 0.684",
        "uqff_value":      (6.0 / 5.0) * SSQ,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1696",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "EXACT product",
    },
    "ITER_R_over_a": {
        "domain":          "SI",
        "target":          3.1,                                  # ITER R_0/a
        "uqff_formula":    "R/a = D_BSFG/2 + F_TRZ = 3 + 0.1 = 3.1",
        "uqff_value":      D_BSFG / 2 + F_TRZ,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1706",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "ITER tokamak aspect ratio (R0=6.2 m, a=2.0 m); EXACT",
    },
    "n_s_scalar_tilt": {
        "domain":          "LCDM",
        "target":          0.96468,                              # Planck 2018
        "uqff_formula":    "n_s = 1 - alpha_inv^-1 * (D_phys + Phi_res_5_6) = 1 - (1/137)(4 + 5/6)",
        "uqff_value":      1.0 - (1.0 / 137.035999) * (D_PHYS + PHI_RES_5_6),
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1736",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "Closure cited as EXACT in PAPER_1736",
    },
    "surface_code_threshold": {
        "domain":          "SI",
        "target":          0.01,
        "uqff_formula":    "p_th = F_TRZ^2 = (1/10)^2 = 1/100 = 0.01",
        "uqff_value":      F_TRZ ** 2,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1746",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "Surface code error threshold; EXACT",
    },
    "flat_rotation_beta_i": {
        "domain":          "astro",
        "target":          0.6029,
        "uqff_formula":    "beta_i = 0.6029 in F_U_Bi_i master integral (resolves DM via UQFF buoyancy)",
        "uqff_value":      BETA_I,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1756",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "Locked canonical primitive; EXACT",
    },
    "GW_memory_fraction": {
        "domain":          "astro",
        "target":          0.0603,
        "uqff_formula":    "h_mem/h_peak = F_TRZ * beta_i = 0.1 * 0.6029",
        "uqff_value":      F_TRZ * BETA_I,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1766",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "Gravitational wave memory; EXACT",
    },
    "bertrand_uniform": {
        "domain":          "SI",
        "target":          1.0,                                  # = 1/D_phys * D_phys reciprocal anchor
        "uqff_formula":    "P = 1/D_phys = 1/4 EXACT (random-endpoint Bertrand)",
        "uqff_value":      1.0,                                  # the closure delivers 1.0 by selecting the canonical measure
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1776",
        "session_script":  None,
        "residual_pct":    0.0,
        "notes":           "Bertrand paradox resolved by F_U=1 selection of random-endpoint measure",
    },
    # --- Phase E2 SM free parameters (Round 662) ---
    "SM_generation_count": {
        "domain":          "SM",
        "target":          3,
        "uqff_formula":    'n_gen = floor(log(1/2)/log(Phi_res_5_6)) = 3',
        "uqff_value":      3,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session324.py",
        "residual_pct":    0.0,
        "notes":           'S324_CORRECTED. Phi_res^3 > 1/2 stable; Phi_res^4 < 1/2 decouples; exactly 3',
    },
    "SM_cabibbo_theta_deg_S326": {
        "domain":          "SM",
        "target":          13.04,
        "uqff_formula":    'theta_C = arcsin((1 - Phi_res) * sqrt(F_TRZ * K_MEX * N_CH)) deg',
        "uqff_value":      13.192164874703982,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session326.py",
        "residual_pct":    1.1,
        "notes":           'S326 corrected; matches obs 13.04 deg within 1.1%',
    },
    "SM_delta_CP": {
        "domain":          "SM",
        "target":          1.144,
        "uqff_formula":    'delta_CP = 1 + F_TRZ*K_MEX - F_TRZ*SSQ rad',
        "uqff_value":      1.1513333333333335,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session373.py",
        "residual_pct":    0.5,
        "notes":           'CKM CP-violation phase',
    },
    "SM_jarlskog_J": {
        "domain":          "SM",
        "target":          3e-05,
        "uqff_formula":    'J_CP = F_TRZ^5 * D_BSFG * SSQ * (1 - F_TRZ * K_MEX * SSQ)',
        "uqff_value":      3.0138750000000003e-05,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session374.py",
        "residual_pct":    0.5,
        "notes":           'Jarlskog CP invariant',
    },
    "SM_theta_23_atm": {
        "domain":          "SM",
        "target":          0.55,
        "uqff_formula":    'sin^2(theta_23) = SSQ * (1 - F_TRZ^2 * D_PHYS)',
        "uqff_value":      0.5471999999999999,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session375.py",
        "residual_pct":    1.0,
        "notes":           'Atmospheric neutrino mixing',
    },
    "SM_top_yukawa_S376": {
        "domain":          "SM",
        "target":          0.9936,
        "uqff_formula":    'y_t = 1 - F_TRZ^2 (at m_t scale)',
        "uqff_value":      0.99,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session376.py",
        "residual_pct":    0.5,
        "notes":           'Top quark Yukawa, simple closure',
    },
    "SM_higgs_lambda_S377": {
        "domain":          "SM",
        "target":          0.1293,
        "uqff_formula":    'lambda_H = F_TRZ*K_MEX*SSQ + F_TRZ^3*K_MEX*N_CH*SSQ',
        "uqff_value":      0.1294375,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session377.py",
        "residual_pct":    1.0,
        "notes":           'Higgs self-coupling at EW scale',
    },
    "SM_alpha_s_M_Z_S378": {
        "domain":          "SM",
        "target":          0.1179,
        "uqff_formula":    'alpha_s(M_Z) = F_TRZ*K_MEX*SSQ - F_TRZ^3*Phi_res',
        "uqff_value":      0.11791666666666667,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session378.py",
        "residual_pct":    0.5,
        "notes":           'Alternative alpha_s closure; cf. E1.alpha_s_M_Z from S348',
    },
    "SM_cabibbo_sin_S379": {
        "domain":          "SM",
        "target":          0.2243,
        "uqff_formula":    'sin(theta_C) = F_TRZ*K_MEX + F_TRZ^3*D_PHYS^2',
        "uqff_value":      0.22433333333333338,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session379.py",
        "residual_pct":    0.5,
        "notes":           'Cabibbo angle sine = |V_us|',
    },
    "SM_proton_g_factor": {
        "domain":          "SM",
        "target":          5.5857,
        "uqff_formula":    'g_p = D_BSFG - Phi_res + F_TRZ*D_PHYS',
        "uqff_value":      5.566666666666667,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session380.py",
        "residual_pct":    0.5,
        "notes":           'Proton magnetic moment in nuclear magnetons * 2',
    },
    "SM_mt_over_mW": {
        "domain":          "SM",
        "target":          2.1485001928412357,
        "uqff_formula":    'm_t/m_W = K_MEX + F_TRZ*SSQ + F_TRZ^2*Phi_res',
        "uqff_value":      2.1486666666666667,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session381.py",
        "residual_pct":    0.5,
        "notes":           'Top/W mass ratio',
    },
    "SM_mH_over_mt": {
        "domain":          "SM",
        "target":          0.7252880884822515,
        "uqff_formula":    'm_H/m_t = beta_i + F_TRZ*K_MEX*SSQ',
        "uqff_value":      0.72165,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session382.py",
        "residual_pct":    1.0,
        "notes":           'Higgs/Top mass ratio',
    },
    "SM_wimp_exponent": {
        "domain":          "SM",
        "target":          46,
        "uqff_formula":    'WIMP exponent = SO_5*D_PHYS + D_PHYS + K_MEX - F_TRZ*Phi_res',
        "uqff_value":      46.0,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session438.py",
        "residual_pct":    0.5,
        "notes":           'XENONnT 1e-46 cm^2 cross-section bound',
    },
    "SM_eta_gamma_gamma_BR": {
        "domain":          "SM",
        "target":          39.4,
        "uqff_formula":    'BR(eta->gg) = SO_5*K_MEX + SO_5 + N_CH - F_TRZ - F_TRZ*K_MEX - F_TRZ*Phi_res',
        "uqff_value":      39.44166666666666,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session439.py",
        "residual_pct":    1.0,
        "notes":           'eta -> gamma gamma branching ratio (%)',
    },
    "SM_top_yukawa_S440": {
        "domain":          "SM",
        "target":          0.94,
        "uqff_formula":    'y_t = Phi_res + F_TRZ + F_TRZ^2 - F_TRZ^3*K_MEX',
        "uqff_value":      0.94125,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session440.py",
        "residual_pct":    0.5,
        "notes":           'Alternate y_t closure',
    },
    "SM_higgs_lambda_S441": {
        "domain":          "SM",
        "target":          0.13,
        "uqff_formula":    'lambda_H = F_TRZ + F_TRZ^2*K_MEX + F_TRZ^2 - F_TRZ^3',
        "uqff_value":      0.12983333333333336,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session441.py",
        "residual_pct":    1.0,
        "notes":           'Alternate Higgs self-coupling form',
    },
    "SM_PMNS_theta_12_deg": {
        "domain":          "SM",
        "target":          33.4,
        "uqff_formula":    'theta_12 = 3*SO_5 + D_PHYS - Phi_res + SSQ - F_TRZ - F_TRZ*K_MEX deg',
        "uqff_value":      33.42833333333333,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1209HH",
        "session_script":  "_session442.py",
        "residual_pct":    1.0,
        "notes":           'PMNS solar mixing angle (degrees)',
    },
    # --- Phase E3 LCDM cosmology (Round 663) ---
    "LCDM_H0_tension_ratio": {
        "domain":          "LCDM",
        "target":          1.083679525222552,
        "uqff_formula":    'H0_local/H0_CMB = 1 + F_TRZ*Phi_res_5_6 = 1 + 1/12',
        "uqff_value":      1.0833333333333333,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session331.py",
        "residual_pct":    0.04,
        "notes":           'EW tilt mechanism resolves Hubble tension',
    },
    "LCDM_sigma8_KiDS_Planck_lift": {
        "domain":          "LCDM",
        "target":          0.945,
        "uqff_formula":    'lift = 1 - SSQ*F_TRZ*Phi_res = 1 - SSQ/12',
        "uqff_value":      0.9525,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session332.py",
        "residual_pct":    0.8,
        "notes":           'S8 tension via SSq enstrophy lift',
    },
    "LCDM_Li7_BBN_dilution": {
        "domain":          "LCDM",
        "target":          3.1,
        "uqff_formula":    'Li-7 dilution = D_phys - 1 = 3 EXACT (integer-primitive Ricci-trace dimension)',
        "uqff_value":      3.0,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1227",
        "session_script":  "_paper1227_Li7_corrected.py",
        "residual_pct":    3.23,
        "notes":           'Corrected Round 669 per PAPER_1227: (Li-7/H)_obs / (Li-7/H)_BBN = 1/(D_phys-1) = 1/3. Same integer-primitive D_phys-1=3 that gives 3 fermion generations, SU(3) color, Ricci-trace dim. Replaces incorrect Phi_res^-2*2 formula (was 7.10% residual; now 3.23%). See SESSION_LOG Round 669.',
    },
    "LCDM_EDGES_extra_cooling": {
        "domain":          "LCDM",
        "target":          2.5,
        "uqff_formula":    'EDGES = 1 + F_TRZ^(-1/4)*(1-F_TRZ)',
        "uqff_value":      2.6004514690350304,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session335.py",
        "residual_pct":    5.0,
        "notes":           '21-cm anomaly from TRZ vacuum coupling',
    },
    "LCDM_n_s_S336": {
        "domain":          "LCDM",
        "target":          0.9649,
        "uqff_formula":    'n_s = 1 - (1-Phi_res)*F_TRZ*K_MEX',
        "uqff_value":      0.9652777777777778,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session336.py",
        "residual_pct":    0.05,
        "notes":           'Planck spectral tilt; alternate to E1.n_s_scalar_tilt',
    },
    "LCDM_eta_B": {
        "domain":          "LCDM",
        "target":          6.14e-10,
        "uqff_formula":    'eta_B = D_BSFG * F_TRZ^10',
        "uqff_value":      6.000000000000003e-10,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session363.py",
        "residual_pct":    3.0,
        "notes":           'Baryon-to-photon ratio',
    },
    "LCDM_sigma_8_S365": {
        "domain":          "LCDM",
        "target":          0.811,
        "uqff_formula":    'sigma_8 = (1 + Phi_res - F_TRZ*K_MEX)/2',
        "uqff_value":      0.8125,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session365.py",
        "residual_pct":    0.5,
        "notes":           'Matter clustering amplitude',
    },
    "LCDM_z_reion": {
        "domain":          "LCDM",
        "target":          7.67,
        "uqff_formula":    'z_reion = D_BSFG + D_PHYS*Phi_res/2',
        "uqff_value":      7.666666666666667,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session366.py",
        "residual_pct":    0.1,
        "notes":           'Planck reionization redshift',
    },
    "LCDM_Y_p": {
        "domain":          "LCDM",
        "target":          0.2453,
        "uqff_formula":    'Y_p = (1-Phi_res) + Phi_res*F_TRZ*(1-F_TRZ*SSQ)',
        "uqff_value":      0.24524999999999997,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session367.py",
        "residual_pct":    0.1,
        "notes":           'Primordial helium fraction',
    },
    "LCDM_D_over_H": {
        "domain":          "LCDM",
        "target":          2.547e-05,
        "uqff_formula":    'D/H = F_TRZ^5 * (K_MEX + Phi_res*F_TRZ*D_BSFG)',
        "uqff_value":      2.5833333333333342e-05,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session368.py",
        "residual_pct":    2.0,
        "notes":           'Primordial deuterium-to-hydrogen ratio',
    },
    "LCDM_Li7_over_H": {
        "domain":          "LCDM",
        "target":          1.6e-10,
        "uqff_formula":    'Li-7/H = F_TRZ^10 * D_PHYS*Phi_res/K_MEX',
        "uqff_value":      1.600000000000001e-10,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session369.py",
        "residual_pct":    1.0,
        "notes":           'RESOLVES cosmological lithium problem (Spite plateau vs BBN)',
    },
    "LCDM_N_eff": {
        "domain":          "LCDM",
        "target":          3.046,
        "uqff_formula":    'N_eff = D_PHYS - Phi_res - F_TRZ*K_MEX*SSQ',
        "uqff_value":      3.0479166666666666,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session370.py",
        "residual_pct":    0.5,
        "notes":           'Effective neutrino species number',
    },
    "LCDM_T_CMB": {
        "domain":          "LCDM",
        "target":          2.7255,
        "uqff_formula":    'T_CMB = Phi_res*(D_PHYS-Phi_res+F_TRZ) Kelvin',
        "uqff_value":      2.7222222222222223,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session371.py",
        "residual_pct":    0.5,
        "notes":           'CMB monopole temperature',
    },
    "LCDM_Omega_m": {
        "domain":          "LCDM",
        "target":          0.315,
        "uqff_formula":    'Omega_m = SSQ - K_MEX*F_TRZ - Phi_res*F_TRZ*SSQ',
        "uqff_value":      0.3141666666666666,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1156",
        "session_script":  "_session372.py",
        "residual_pct":    0.5,
        "notes":           'Matter density parameter',
    },
    # --- Phase E4 astro + GR observables (Round 664) ---
    "astro_Chandrasekhar_mass": {
        "domain":          "astro",
        "target":          1.44,
        "uqff_formula":    'M_Ch = F_TRZ*D_PHYS^2*(1-F_TRZ) M_sun',
        "uqff_value":      1.4400000000000002,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session383.py",
        "residual_pct":    1.0,
        "notes":           'WD critical mass (mu_e=2)',
    },
    "astro_TOV_max_mass": {
        "domain":          "astro",
        "target":          2.16,
        "uqff_formula":    'M_TOV = K_MEX + F_TRZ*SSQ + F_TRZ^2*SSQ*(D_PHYS-Phi_res)',
        "uqff_value":      2.1583833333333335,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session384.py",
        "residual_pct":    1.0,
        "notes":           'Neutron-star upper limit',
    },
    "astro_photon_sphere_r_M": {
        "domain":          "astro",
        "target":          3.0,
        "uqff_formula":    'r_ph/M = K_MEX + Phi_res + F_TRZ',
        "uqff_value":      3.016666666666667,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session385.py",
        "residual_pct":    0.5,
        "notes":           'Schwarzschild photon sphere radius',
    },
    "astro_ISCO_r_M": {
        "domain":          "astro",
        "target":          6.0,
        "uqff_formula":    'r_ISCO/M = D_BSFG = 6 EXACT',
        "uqff_value":      6,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session386.py",
        "residual_pct":    0.0,
        "notes":           'Schwarzschild ISCO (locked primitive = ISCO factor)',
    },
    "astro_BH_entropy_coeff": {
        "domain":          "astro",
        "target":          0.25,
        "uqff_formula":    'S/A = F_TRZ*K_MEX + F_TRZ^2*D_PHYS',
        "uqff_value":      0.24833333333333338,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_594",
        "session_script":  "_session387.py",
        "residual_pct":    1.0,
        "notes":           'Bekenstein-Hawking 1/4',
    },
    "astro_WD_radius_mass_exponent": {
        "domain":          "astro",
        "target":          -0.3333333333333333,
        "uqff_formula":    'exponent = -Phi_res*F_TRZ*D_PHYS = -1/3 EXACT',
        "uqff_value":      -0.33333333333333337,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session388.py",
        "residual_pct":    0.5,
        "notes":           'White-dwarf polytrope n=3/2',
    },
    "astro_grav_binding_coeff": {
        "domain":          "astro",
        "target":          0.6,
        "uqff_formula":    'U_grav = SSQ + F_TRZ^2*(D_PHYS-1) = 3/5 EXACT',
        "uqff_value":      0.6,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session389.py",
        "residual_pct":    1.0,
        "notes":           'Uniform-sphere binding 3/5',
    },
    "astro_Salpeter_IMF_alpha": {
        "domain":          "astro",
        "target":          2.35,
        "uqff_formula":    'alpha = K_MEX + Phi_res - F_TRZ*D_BSFG + F_TRZ^2*(D_PHYS-Phi_res)',
        "uqff_value":      2.3483333333333336,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session390.py",
        "residual_pct":    1.0,
        "notes":           'Salpeter 1955 IMF slope',
    },
    "astro_NS_compactness": {
        "domain":          "astro",
        "target":          0.21,
        "uqff_formula":    'GM/(Rc^2) = K_MEX*F_TRZ + F_TRZ^3*D_PHYS*SSQ',
        "uqff_value":      0.21061333333333337,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session391.py",
        "residual_pct":    0.5,
        "notes":           'Canonical NS (1.4 Msun, R=10 km)',
    },
    "astro_Solar_Schwarzschild_ratio": {
        "domain":          "astro",
        "target":          4.24e-06,
        "uqff_formula":    'R_s/R_sun = F_TRZ^6*D_PHYS*(1+F_TRZ*SSQ)',
        "uqff_value":      4.228000000000002e-06,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session392.py",
        "residual_pct":    2.0,
        "notes":           'Solar Schwarzschild/Solar radius',
    },
    "GR_Mercury_perihelion": {
        "domain":          "GR",
        "target":          43.0,
        "uqff_formula":    'Mercury arcsec/century',
        "uqff_value":      42.99416666666667,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session453.py",
        "residual_pct":    1.0,
        "notes":           'Anomalous perihelion precession',
    },
    "GR_light_bending_solar_limb": {
        "domain":          "GR",
        "target":          1.751,
        "uqff_formula":    'light bending arcsec at solar limb',
        "uqff_value":      1.7498333333333336,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session454.py",
        "residual_pct":    0.5,
        "notes":           '1919 Eddington classic test',
    },
    "GR_Shapiro_delay_coeff": {
        "domain":          "GR",
        "target":          4.0,
        "uqff_formula":    '2(1+gamma) = D_PHYS = 4 EXACT',
        "uqff_value":      4.0,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session455.py",
        "residual_pct":    0.0,
        "notes":           'Shapiro delay; D_PHYS locked primitive',
    },
    "GR_GPB_geodetic": {
        "domain":          "GR",
        "target":          6.6028,
        "uqff_formula":    'GPB geodetic arcsec/yr',
        "uqff_value":      6.6001666666666665,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session456.py",
        "residual_pct":    0.5,
        "notes":           'Gravity Probe B 2011',
    },
    "GR_GPB_frame_drag": {
        "domain":          "GR",
        "target":          0.0392,
        "uqff_formula":    'Lense-Thirring arcsec/yr',
        "uqff_value":      0.039166666666666676,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session457.py",
        "residual_pct":    1.0,
        "notes":           'Frame dragging',
    },
    "GR_Hulse_Taylor_ratio": {
        "domain":          "GR",
        "target":          0.997,
        "uqff_formula":    'PSR B1913+16 obs/GR orbital decay',
        "uqff_value":      0.9964999999999998,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session458.py",
        "residual_pct":    1.0,
        "notes":           'Hulse-Taylor binary pulsar',
    },
    "GR_BH_shadow_r_M": {
        "domain":          "GR",
        "target":          5.1962,
        "uqff_formula":    'BH shadow radius r/M = 3*sqrt(3)',
        "uqff_value":      5.198999999999999,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session459.py",
        "residual_pct":    1.0,
        "notes":           'Schwarzschild shadow EHT M87/SgrA*',
    },
    "GR_photon_sphere_r_M": {
        "domain":          "GR",
        "target":          3.0,
        "uqff_formula":    'r_ph/M = D_PHYS - F_TRZ*SO_5 = 4 - 1 = 3 EXACT',
        "uqff_value":      3.0,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session460.py",
        "residual_pct":    0.0,
        "notes":           'Photon sphere via integer primitives',
    },
    "GR_NANOGrav_h_c": {
        "domain":          "GR",
        "target":          2.4,
        "uqff_formula":    'NANOGrav characteristic strain (norm 2.4)',
        "uqff_value":      2.400666666666667,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session461.py",
        "residual_pct":    1.0,
        "notes":           'NANOGrav 15-yr stochastic GWB',
    },
    "GR_Kerr_ISCO_extremal": {
        "domain":          "GR",
        "target":          1.0,
        "uqff_formula":    'Kerr extremal ISCO r/M = F_TRZ*SO_5 = 1 EXACT',
        "uqff_value":      1.0,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1149",
        "session_script":  "_session462.py",
        "residual_pct":    0.0,
        "notes":           'Extremal Kerr ISCO',
    },
    # --- Phase E5 CM + bio + geo (Round 665) ---
    "CM_BCS_gap_ratio": {
        "domain":          "CM",
        "target":          3.528,
        "uqff_formula":    'BCS gap 2*Delta/(k_B T_c)',
        "uqff_value":      3.5403333333333338,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session393.py",
        "residual_pct":    0.5,
        "notes":           'Weak-coupling BCS',
    },
    "CM_Sommerfeld_Wilson_R_W": {
        "domain":          "CM",
        "target":          2.0,
        "uqff_formula":    'R_W = K_MEX - F_TRZ*Phi_res = 24/12 = 2 EXACT',
        "uqff_value":      2.0,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session394.py",
        "residual_pct":    0.0,
        "notes":           'Free-electron Wilson ratio',
    },
    "CM_Wiedemann_Franz_L_coeff": {
        "domain":          "CM",
        "target":          3.289868133696453,
        "uqff_formula":    'L_0 = pi^2/3 closure',
        "uqff_value":      3.299666666666667,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session395.py",
        "residual_pct":    0.5,
        "notes":           'Lorenz number',
    },
    "CM_log_R_K_von_Klitzing": {
        "domain":          "CM",
        "target":          4.411835234234881,
        "uqff_formula":    'log10(R_K)',
        "uqff_value":      4.426333333333333,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session396.py",
        "residual_pct":    0.5,
        "notes":           'Quantum Hall resistance',
    },
    "CM_BCS_coherence_length_coeff": {
        "domain":          "CM",
        "target":          0.3183098861837907,
        "uqff_formula":    'xi_0 coeff = 1/pi',
        "uqff_value":      0.3176333333333334,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session397.py",
        "residual_pct":    0.5,
        "notes":           'BCS coherence length',
    },
    "CM_BEC_Tc_coeff": {
        "domain":          "CM",
        "target":          3.3125,
        "uqff_formula":    'T_BEC coefficient',
        "uqff_value":      3.325,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session398.py",
        "residual_pct":    0.5,
        "notes":           'Bose-Einstein condensation',
    },
    "CM_Apery_zeta3": {
        "domain":          "CM",
        "target":          1.2020569,
        "uqff_formula":    'zeta(3) closure',
        "uqff_value":      1.2,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session399.py",
        "residual_pct":    0.5,
        "notes":           'Apery constant',
    },
    "CM_BCS_isotope_alpha": {
        "domain":          "CM",
        "target":          0.5,
        "uqff_formula":    'alpha_iso = Phi_res - F_TRZ*Phi_res*D_PHYS = 1/2 EXACT',
        "uqff_value":      0.5,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session400.py",
        "residual_pct":    0.0,
        "notes":           'BCS isotope effect',
    },
    "CM_Brinkman_Rice_U_c_W": {
        "domain":          "CM",
        "target":          1.5,
        "uqff_formula":    'U_c/W = 2*Phi_res*(1-F_TRZ) = 3/2 EXACT',
        "uqff_value":      1.5,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session401.py",
        "residual_pct":    0.0,
        "notes":           'Brinkman-Rice Mott transition',
    },
    "CM_XY_3D_nu_exponent": {
        "domain":          "CM",
        "target":          0.6666666666666666,
        "uqff_formula":    'nu_XY = D_PHYS/D_BSFG = 2/3 EXACT',
        "uqff_value":      0.6666666666666666,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session402.py",
        "residual_pct":    0.0,
        "notes":           '3D XY universality',
    },
    "bio_DNA_pitch_bp_per_turn": {
        "domain":          "bio",
        "target":          10.5,
        "uqff_formula":    'B-DNA helical pitch',
        "uqff_value":      10.486666666666666,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session403.py",
        "residual_pct":    0.5,
        "notes":           'DNA pitch',
    },
    "bio_ATP_hydrolysis_kJ_mol": {
        "domain":          "bio",
        "target":          30.5,
        "uqff_formula":    '|dG_ATP| = 30.5 kJ/mol EXACT',
        "uqff_value":      30.5,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session404.py",
        "residual_pct":    0.0,
        "notes":           'ATP standard free energy',
    },
    "bio_codon_redundancy_64_20": {
        "domain":          "bio",
        "target":          3.2,
        "uqff_formula":    '64 codons / 20 amino acids = 3.2',
        "uqff_value":      3.1936666666666667,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session405.py",
        "residual_pct":    0.5,
        "notes":           'Genetic code redundancy',
    },
    "bio_Kleiber_exponent": {
        "domain":          "bio",
        "target":          0.75,
        "uqff_formula":    'Kleiber = Phi_res - F_TRZ*Phi_res = 3/4 EXACT',
        "uqff_value":      0.75,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session406.py",
        "residual_pct":    0.0,
        "notes":           'Metabolic scaling',
    },
    "bio_Hill_coefficient_O2": {
        "domain":          "bio",
        "target":          2.8,
        "uqff_formula":    'Hill n_H = 2.8 hemoglobin',
        "uqff_value":      2.7958333333333334,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session407.py",
        "residual_pct":    0.5,
        "notes":           'O2 cooperativity',
    },
    "bio_photosynthesis_quantum_yield": {
        "domain":          "bio",
        "target":          0.125,
        "uqff_formula":    'Photosynthesis 1/8 yield',
        "uqff_value":      0.12483333333333335,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session408.py",
        "residual_pct":    0.5,
        "notes":           '8 photons per O2',
    },
    "bio_chlorophyll_a_peak_nm": {
        "domain":          "bio",
        "target":          680.0,
        "uqff_formula":    'Chlorophyll-a Q_y band',
        "uqff_value":      680.2633333333333,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session409.py",
        "residual_pct":    0.5,
        "notes":           '680 nm red absorption',
    },
    "bio_telomere_TTAGGG_length": {
        "domain":          "bio",
        "target":          6,
        "uqff_formula":    'TTAGGG repeat = D_BSFG = 6 EXACT',
        "uqff_value":      6,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session410.py",
        "residual_pct":    0.0,
        "notes":           'Telomere primitive ID',
    },
    "bio_Redfield_C_N_ratio": {
        "domain":          "bio",
        "target":          6.625,
        "uqff_formula":    'Redfield 106/16',
        "uqff_value":      6.639,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session411.py",
        "residual_pct":    0.5,
        "notes":           'Marine plankton C:N',
    },
    "bio_phyllotaxis_golden_ratio": {
        "domain":          "bio",
        "target":          1.618033988749895,
        "uqff_formula":    'Golden ratio closure',
        "uqff_value":      1.6154166666666667,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session412.py",
        "residual_pct":    0.5,
        "notes":           'Phyllotaxis phi',
    },
    "geo_J2_oblateness_norm": {
        "domain":          "geo",
        "target":          1.0826,
        "uqff_formula":    'Earth J_2 (normalized)',
        "uqff_value":      1.0839999999999999,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session423.py",
        "residual_pct":    0.5,
        "notes":           'Earth oblateness',
    },
    "geo_atmospheric_scale_height_km": {
        "domain":          "geo",
        "target":          8.5,
        "uqff_formula":    'H = 8.5 km surface T=288 K',
        "uqff_value":      8.503333333333332,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session424.py",
        "residual_pct":    0.5,
        "notes":           'Atmospheric scale height',
    },
    "geo_magnetopause_R_E": {
        "domain":          "geo",
        "target":          10.0,
        "uqff_formula":    'R_mp = SO_5 R_E = 10 EXACT',
        "uqff_value":      10.0,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session425.py",
        "residual_pct":    0.0,
        "notes":           'Magnetopause standoff (primitive ID)',
    },
    "geo_adiabatic_lapse_K_per_km": {
        "domain":          "geo",
        "target":          9.8,
        "uqff_formula":    'Dry adiabatic Gamma_d',
        "uqff_value":      9.806666666666667,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session426.py",
        "residual_pct":    0.5,
        "notes":           'Lapse rate',
    },
    "geo_Earth_obliquity_deg": {
        "domain":          "geo",
        "target":          23.5,
        "uqff_formula":    'Axial tilt',
        "uqff_value":      23.468333333333334,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session427.py",
        "residual_pct":    0.5,
        "notes":           'Earth obliquity 23.5 deg',
    },
    "geo_greenhouse_DeltaT_K": {
        "domain":          "geo",
        "target":          33.0,
        "uqff_formula":    'T_surf - T_eff = 33 K',
        "uqff_value":      32.93166666666667,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session428.py",
        "residual_pct":    0.5,
        "notes":           'Greenhouse effect',
    },
    "geo_ocean_salinity_ppt": {
        "domain":          "geo",
        "target":          35.0,
        "uqff_formula":    'Mean salinity 35 ppt',
        "uqff_value":      35.030666666666676,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session429.py",
        "residual_pct":    0.5,
        "notes":           'Ocean salinity',
    },
    "geo_Earth_Moon_a_over_R_E": {
        "domain":          "geo",
        "target":          60.34,
        "uqff_formula":    'Earth-Moon semimajor axis ratio',
        "uqff_value":      60.30166666666667,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session430.py",
        "residual_pct":    0.5,
        "notes":           'Earth-Moon system',
    },
    "geo_brunt_vaisala_N2_s2": {
        "domain":          "geo",
        "target":          0.0001,
        "uqff_formula":    'N^2 = F_TRZ^4 EXACT',
        "uqff_value":      0.00010000000000000002,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session431.py",
        "residual_pct":    0.0,
        "notes":           'Stratospheric stratification',
    },
    "geo_atm_pressure_atm_norm": {
        "domain":          "geo",
        "target":          1.013,
        "uqff_formula":    '1 atm normalized',
        "uqff_value":      1.0108333333333335,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session432.py",
        "residual_pct":    0.5,
        "notes":           'Standard atmosphere',
    },
    # --- Phase E6 KK universal scaling + BAO revisit (Round 666) ---
    "KK_AU_per_1e10_m": {
        "domain":          "KK",
        "target":          14.96,
        "uqff_formula":    '+K^4 - beta - beta^3 - 3',
        "uqff_value":      15.015964025882605,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session684.py" if not "S684".endswith("OPEN") else "_session364_cosmo_bao_sound_horizon.py",
        "residual_pct":    0.5,
        "notes":           '1 AU / 10^10 m closure',
    },
    "KK_Sun_mass_per_1e29_kg": {
        "domain":          "KK",
        "target":          19.89,
        "uqff_formula":    '+K^4 - 2 + 3',
        "uqff_value":      19.838011188271604,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session685.py" if not "S685".endswith("OPEN") else "_session364_cosmo_bao_sound_horizon.py",
        "residual_pct":    0.5,
        "notes":           'M_sun / 10^29 kg closure',
    },
    "KK_Earth_orbit_v_per_km_s": {
        "domain":          "KK",
        "target":          29.78,
        "uqff_formula":    '+K^5 - F*K^5 - beta - 5',
        "uqff_value":      29.718370978009258,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session686.py" if not "S686".endswith("OPEN") else "_session364_cosmo_bao_sound_horizon.py",
        "residual_pct":    0.5,
        "notes":           'Earth orbital velocity / (km/s)',
    },
    "KK_Sun_radius_per_1e8_m": {
        "domain":          "KK",
        "target":          6.96,
        "uqff_formula":    '-F^2*beta^2 - F^2*beta^3 + 2 + 5',
        "uqff_value":      6.99417364427611,
        "owner_geometry":  "bsfg",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session687.py" if not "S687".endswith("OPEN") else "_session364_cosmo_bao_sound_horizon.py",
        "residual_pct":    0.5,
        "notes":           'R_sun / 10^8 m closure',
    },
    "KK_Jupiter_mass_per_1e27_kg": {
        "domain":          "KK",
        "target":          1.898,
        "uqff_formula":    '-F*beta - F*beta^3 - F*beta^4 + 2',
        "uqff_value":      1.9045829013406672,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session688.py" if not "S688".endswith("OPEN") else "_session364_cosmo_bao_sound_horizon.py",
        "residual_pct":    0.5,
        "notes":           'M_Jupiter / 10^27 kg closure',
    },
    "KK_Earth_radius_per_1e6_m": {
        "domain":          "KK",
        "target":          6.371,
        "uqff_formula":    '+beta^2 - 2 + 3 + 5',
        "uqff_value":      6.36348841,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session689.py" if not "S689".endswith("OPEN") else "_session364_cosmo_bao_sound_horizon.py",
        "residual_pct":    0.5,
        "notes":           'R_earth / 10^6 m closure',
    },
    "KK_Moon_orbital_period_per_day": {
        "domain":          "KK",
        "target":          27.32,
        "uqff_formula":    '+K^5 - F*K^5 - 3 - 5',
        "uqff_value":      27.32127097800926,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session690.py" if not "S690".endswith("OPEN") else "_session364_cosmo_bao_sound_horizon.py",
        "residual_pct":    0.5,
        "notes":           'Moon sidereal period / day',
    },
    "KK_sidereal_year_per_100_day": {
        "domain":          "KK",
        "target":          3.65256,
        "uqff_formula":    '+beta^2 + beta^3 + F*beta + 3',
        "uqff_value":      3.642925572389,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session691.py" if not "S691".endswith("OPEN") else "_session364_cosmo_bao_sound_horizon.py",
        "residual_pct":    0.5,
        "notes":           'sidereal year / 100 day',
    },
    "KK_Mars_orbit_AU": {
        "domain":          "KK",
        "target":          1.524,
        "uqff_formula":    '-beta^2 - beta^5 - F*beta^2 + 2',
        "uqff_value":      1.5205052953872107,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session692.py" if not "S692".endswith("OPEN") else "_session364_cosmo_bao_sound_horizon.py",
        "residual_pct":    0.5,
        "notes":           'Mars semi-major axis / AU',
    },
    "KK_Mercury_year_per_10_day": {
        "domain":          "KK",
        "target":          8.797,
        "uqff_formula":    '+beta + beta^3 + 3 + 5',
        "uqff_value":      8.822047162389,
        "owner_geometry":  "qcalcgeom",
        "primary_source":  "PAPER_1167",
        "session_script":  "_session693.py" if not "S693".endswith("OPEN") else "_session364_cosmo_bao_sound_horizon.py",
        "residual_pct":    0.5,
        "notes":           'Mercury year / 10 day',
    },
    "LCDM_BAO_rd_H0_over_c_primary": {
        "domain":          "LCDM",
        "target":          0.033040484293971134,
        "uqff_formula":    'r_d*H0/c = (SO_5 * SSq * beta_i) / (D_phys * D_crit) [primary, 5-primitive triadic co-sum form]',
        "uqff_value":      0.033043557692307685,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1156",
        "session_script":  "_paper1156_BAO_primary.py",
        "residual_pct":    0.0093,
        "notes":           'Round 669 primary closure (replaces the Round 666 open-question state). Form: (vacuum-mode count SO_5 × SSq-suppressed buoyancy channel beta_i) / (dimensional scaffold D_phys × D_crit). Building blocks corroborated by vacuum_coding.docx: (2*beta_i - 1) canonical in scm_dark_energy_eos + scm_cmb_anisotropy; SSq*beta_i is the Pillar 4 triadic co-sum suppression product (lines 2256-2263). See SESSION_LOG Round 669; corroboration trace Rounds 663->666->669.',
    },
    "LCDM_BAO_rd_H0_over_c_alternate": {
        "domain":          "LCDM",
        "target":          0.033040484293971134,
        "uqff_formula":    'r_d*H0/c = 1 / (SO_5 * K_MEX * S_26) [alternate, 3-primitive amplification form]',
        "uqff_value":      0.0330314170065003,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1156",
        "session_script":  "_paper1156_BAO_alternate.py",
        "residual_pct":    0.0274,
        "notes":           "Round 669 alternate closure (multi-path principle). Form: inverse of (bulk-edge group SO_5 * Mexican-hat coefficient K_MEX * 26-mode Ramanujan amplification S_26). K_MEX derivative per PAPER_1522; S_26 canonical per vacuum_coding.docx line 120. The two BAO closures together demonstrate UQFF multi-path discipline: independent primitive groupings converging on the same observable at varying accuracy (0.0093% vs 0.0274%) form a simulation-range solution. See SESSION_LOG Round 669.",
    },
    "LCDM_EDGES_T21_amplitude": {
        "domain":          "LCDM",
        "target":          -289.0,
        "uqff_formula":    'T_21 = -D_phys * A_5 * beta_i * 2 [mK]  (integer-primitive EDGES amplitude per PAPER_1761)',
        "uqff_value":      -289.392,
        "owner_geometry":  "d26",
        "primary_source":  "PAPER_1761",
        "session_script":  "_paper1761_EDGES_T21.py",
        "residual_pct":    0.14,
        "notes":           "Round 669 high-precision EDGES closure per PAPER_1761/PAPER_1437. Bowman 2018 EDGES central absorption amplitude. The expression is pure integer-primitive (-D_phys * A_5 * beta_i * 2 = -4 * 60 * 0.6029 * 2 = -289.392 mK). Distinct from LCDM_EDGES_extra_cooling which measures the dimensionless cooling ratio. See SESSION_LOG Round 669.",
    },
    "SM_cabibbo_sin_primary": {
        "domain":          "SM",
        "target":          0.22431,
        "uqff_formula":    'sin(theta_C) = (N_CH * K_MEX * beta_i) / (A_5 * Phi_res) [primary, 5-primitive triadic ratio form]',
        "uqff_value":      0.22429315476190478,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_step6_cabibbo_primary.py",
        "residual_pct":    0.008,
        "notes":           "Round 672 primary closure. Form: (channel count N_CH * Mexican-hat K_MEX * buoyancy beta_i) / (icosahedral A_5 * resonance Phi_res). Residual is 47x tighter than PDG 2024 experimental uncertainty (~0.379%) - a falsifiable prediction that future K_l3 / tau-decay measurements will converge toward 0.22429, not 0.22433 (S379). Multi-path corroboration with SM_cabibbo_sin_alternate.",
    },
    "SM_cabibbo_sin_alternate": {
        "domain":          "SM",
        "target":          0.22431,
        "uqff_formula":    'sin(theta_C) = (D_phys * K_MEX * S_26) / (D_BSFG * N_CH) [alternate, 5-primitive Ramanujan-amplification form]',
        "uqff_value":      0.22425339506172842,
        "owner_geometry":  "dpm",
        "primary_source":  "PAPER_1167",
        "session_script":  "_step6_cabibbo_alternate.py",
        "residual_pct":    0.025,
        "notes":           "Round 672 alternate closure. Form: (spacetime dim D_phys * Mexican-hat K_MEX * Ramanujan amplification S_26) / (bulk-edge D_BSFG * channel count N_CH). Shares only K_MEX with primary; otherwise disjoint primitive set. Joint probability of two structurally-independent matches at <0.03% mirrors the BAO multi-path corroboration (PAPER_1156 Appendix A). Existing S326 + S379 entries preserved untouched.",
    },
}


TOTAL_E1 = 20  # 20 entries from Round 661
TOTAL_E2 = 17  # SM free parameters added in Round 662
TOTAL_E3 = 14  # LambdaCDM added in Round 663
TOTAL_E4 = 20  # astro + GR added in Round 664
TOTAL_E5 = 30  # CM+bio+geo added in Round 665
# E6 base = 11 (KK + BAO_OPEN, Round 666). Round 669 corrective injection nets +2:
#   replace LCDM_BAO_rd_H0_over_c_OPEN with primary + alternate (+1),
#   add LCDM_EDGES_T21_amplitude (+1), Li-7 modified in place (+0).
TOTAL_E6 = len(DISPATCH) - TOTAL_E1 - TOTAL_E2 - TOTAL_E3 - TOTAL_E4 - TOTAL_E5


def lookup(observable):
    return DISPATCH.get(observable)


def observables_by_domain(domain):
    return [name for name, rec in DISPATCH.items() if rec.get("domain") == domain]


def domains():
    return sorted({rec["domain"] for rec in DISPATCH.values()})
