// ===================================================================
// Auto-generated Wolfram Physics Terms from source172.cpp
// Generated by: wolfram_extraction_phase4.py
// Date: 2025-11-24 19:25:48
// ===================================================================
// Source: source172.cpp
// Constants: 0
// Systems: 36
// Total Terms: 36
// ===================================================================

#include <memory>
#include <string>
#include <iostream>

// Forward declarations (assume these exist in main codebase)
class PhysicsTerm;
class PhysicsTermRegistry;
struct SystemParams;
enum class PhysicsTermCategory;

// ===================================================================
// Constant Definitions
// ===================================================================


// ===================================================================
// Astrophysical System Definitions
// ===================================================================


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_42 : public PhysicsTerm {
public:
    Wolfram_NGC_42() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_43 : public PhysicsTerm {
public:
    Wolfram_NGC_43() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_44 : public PhysicsTerm {
public:
    Wolfram_NGC_44() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_45 : public PhysicsTerm {
public:
    Wolfram_NGC_45() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_46 : public PhysicsTerm {
public:
    Wolfram_NGC_46() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_47 : public PhysicsTerm {
public:
    Wolfram_NGC_47() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_48 : public PhysicsTerm {
public:
    Wolfram_NGC_48() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_49 : public PhysicsTerm {
public:
    Wolfram_NGC_49() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_50 : public PhysicsTerm {
public:
    Wolfram_NGC_50() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_51 : public PhysicsTerm {
public:
    Wolfram_NGC_51() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_52 : public PhysicsTerm {
public:
    Wolfram_NGC_52() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: Nebula
class Wolfram_Nebula : public PhysicsTerm {
public:
    Wolfram_Nebula() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "Nebula";
    }
    
    std::string getDescription() const override {
        return "Nebula";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_53 : public PhysicsTerm {
public:
    Wolfram_NGC_53() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: Nebula
class Wolfram_Nebula_1 : public PhysicsTerm {
public:
    Wolfram_Nebula_1() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "Nebula";
    }
    
    std::string getDescription() const override {
        return "Nebula";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: M42
class Wolfram_M42 : public PhysicsTerm {
public:
    Wolfram_M42() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "M42";
    }
    
    std::string getDescription() const override {
        return "M42";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: Nebula
class Wolfram_Nebula_2 : public PhysicsTerm {
public:
    Wolfram_Nebula_2() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "Nebula";
    }
    
    std::string getDescription() const override {
        return "Nebula";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_54 : public PhysicsTerm {
public:
    Wolfram_NGC_54() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_55 : public PhysicsTerm {
public:
    Wolfram_NGC_55() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_56 : public PhysicsTerm {
public:
    Wolfram_NGC_56() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: Nebula
class Wolfram_Nebula_3 : public PhysicsTerm {
public:
    Wolfram_Nebula_3() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "Nebula";
    }
    
    std::string getDescription() const override {
        return "Nebula";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: M74
class Wolfram_M74 : public PhysicsTerm {
public:
    Wolfram_M74() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "M74";
    }
    
    std::string getDescription() const override {
        return "M74";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_57 : public PhysicsTerm {
public:
    Wolfram_NGC_57() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_58 : public PhysicsTerm {
public:
    Wolfram_NGC_58() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: M82
class Wolfram_M82_2 : public PhysicsTerm {
public:
    Wolfram_M82_2() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "M82";
    }
    
    std::string getDescription() const override {
        return "M82";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: Nebula
class Wolfram_Nebula_4 : public PhysicsTerm {
public:
    Wolfram_Nebula_4() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "Nebula";
    }
    
    std::string getDescription() const override {
        return "Nebula";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_59 : public PhysicsTerm {
public:
    Wolfram_NGC_59() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_60 : public PhysicsTerm {
public:
    Wolfram_NGC_60() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: Nebula
class Wolfram_Nebula_5 : public PhysicsTerm {
public:
    Wolfram_Nebula_5() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "Nebula";
    }
    
    std::string getDescription() const override {
        return "Nebula";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_61 : public PhysicsTerm {
public:
    Wolfram_NGC_61() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: Nebula
class Wolfram_Nebula_6 : public PhysicsTerm {
public:
    Wolfram_Nebula_6() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "Nebula";
    }
    
    std::string getDescription() const override {
        return "Nebula";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: M42
class Wolfram_M42_1 : public PhysicsTerm {
public:
    Wolfram_M42_1() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "M42";
    }
    
    std::string getDescription() const override {
        return "M42";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: Nebula
class Wolfram_Nebula_7 : public PhysicsTerm {
public:
    Wolfram_Nebula_7() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "Nebula";
    }
    
    std::string getDescription() const override {
        return "Nebula";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_62 : public PhysicsTerm {
public:
    Wolfram_NGC_62() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_63 : public PhysicsTerm {
public:
    Wolfram_NGC_63() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: NGC
class Wolfram_NGC_64 : public PhysicsTerm {
public:
    Wolfram_NGC_64() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "NGC";
    }
    
    std::string getDescription() const override {
        return "NGC";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// Wolfram Knowledgebase: Nebula
class Wolfram_Nebula_8 : public PhysicsTerm {
public:
    Wolfram_Nebula_8() {}
    
    double compute(double t, const std::map<std::string, double>& params) const override {
        // Astrophysical system modeling from Wolfram data
        const double M = params.count("M_ns") ? params.at("M_ns") : 1.0e30;
        const double R = params.count("R_ns") ? params.at("R_ns") : 1.0e6;
        
        // Basic gravitational potential energy
        const double G = 6.67430e-11;  // m^3 kg^-1 s^-2
        return -G * M * M / R;
    }
    
    std::string getName() const override {
        return "Nebula";
    }
    
    std::string getDescription() const override {
        return "Nebula";
    }
    
    bool validate(const std::map<std::string, double>& params) const override {
        return true;
    }
};


// ===================================================================
// Registration function for source172.cpp Wolfram terms
// ===================================================================
void registerWolframTerms_source172_cpp(PhysicsTermRegistry& registry) {
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_42>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_43>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_44>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_45>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_46>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_47>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_48>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_49>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_50>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_51>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_52>(), "wolfram");
    registry.registerTerm("Nebula", std::make_unique<Wolfram_Nebula>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_53>(), "wolfram");
    registry.registerTerm("Nebula", std::make_unique<Wolfram_Nebula_1>(), "wolfram");
    registry.registerTerm("M42", std::make_unique<Wolfram_M42>(), "wolfram");
    registry.registerTerm("Nebula", std::make_unique<Wolfram_Nebula_2>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_54>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_55>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_56>(), "wolfram");
    registry.registerTerm("Nebula", std::make_unique<Wolfram_Nebula_3>(), "wolfram");
    registry.registerTerm("M74", std::make_unique<Wolfram_M74>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_57>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_58>(), "wolfram");
    registry.registerTerm("M82", std::make_unique<Wolfram_M82_2>(), "wolfram");
    registry.registerTerm("Nebula", std::make_unique<Wolfram_Nebula_4>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_59>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_60>(), "wolfram");
    registry.registerTerm("Nebula", std::make_unique<Wolfram_Nebula_5>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_61>(), "wolfram");
    registry.registerTerm("Nebula", std::make_unique<Wolfram_Nebula_6>(), "wolfram");
    registry.registerTerm("M42", std::make_unique<Wolfram_M42_1>(), "wolfram");
    registry.registerTerm("Nebula", std::make_unique<Wolfram_Nebula_7>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_62>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_63>(), "wolfram");
    registry.registerTerm("NGC", std::make_unique<Wolfram_NGC_64>(), "wolfram");
    registry.registerTerm("Nebula", std::make_unique<Wolfram_Nebula_8>(), "wolfram");
    
    std::cout << "Registered 36 Wolfram terms from source172.cpp" << std::endl;
}
