// ===================================================================
// Master Registration Header for All Wolfram Physics Terms
// Auto-generated by: wolfram_extraction_phase4.py
// Date: 2025-11-24 19:25:48
// ===================================================================

#ifndef WOLFRAM_MASTER_REGISTRATION_H
#define WOLFRAM_MASTER_REGISTRATION_H

#include <iostream>

// Forward declaration
class PhysicsTermRegistry;

// Registration function declarations
extern void registerWolframTerms_source4(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source5(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source6(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source7(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source8(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source9(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source10(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source11(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source12(PhysicsTermRegistry& registry);
extern void registerWolframTerms_Source167_cpp(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source10_cpp(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source168_cpp(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source169_cpp(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source170_cpp(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source171_cpp(PhysicsTermRegistry& registry);
extern void registerWolframTerms_source172_cpp(PhysicsTermRegistry& registry);

// ===================================================================
// Master registration function
// Call this to register ALL Wolfram terms
// ===================================================================
inline void registerAllExtractedWolframTerms(PhysicsTermRegistry& registry) {
    std::cout << "Registering Wolfram Physics Terms..." << std::endl;

    // Core physics terms (source4-12)
    registerWolframTerms_source4(registry);
    registerWolframTerms_source5(registry);
    registerWolframTerms_source6(registry);
    registerWolframTerms_source7(registry);
    registerWolframTerms_source8(registry);
    registerWolframTerms_source9(registry);
    registerWolframTerms_source10(registry);
    registerWolframTerms_source11(registry);
    registerWolframTerms_source12(registry);

    // Advanced systems (source167-172)
    registerWolframTerms_Source167_cpp(registry);
    registerWolframTerms_source10_cpp(registry);
    registerWolframTerms_source168_cpp(registry);
    registerWolframTerms_source169_cpp(registry);
    registerWolframTerms_source170_cpp(registry);
    registerWolframTerms_source171_cpp(registry);
    registerWolframTerms_source172_cpp(registry);

    std::cout << "All Wolfram terms registered successfully." << std::endl;
}

#endif // WOLFRAM_MASTER_REGISTRATION_H